### ISSUE TITLE
Implement "Calculation Inputs" in user interface

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#114]
Allow user to view calculation inputs on the main web page.

Include the ability to display, or not via the View : Calculation Inputs menu item.

**Comment by 1fifoto** [comment]
Bri: What is this one? "Implement "Calculation Inputs" in user interface"

Bri: Is this "Constants"?

Mike: Yes, "Constants", aka D vector. By the time that we get to density in Solids, I expect that we will want to be able to change it.  Also, Solids is supposed to lay the groundwork for material tables in Springs.

**Comment by 1fifoto** [comment]
After a discussion with Mike, we decided to remove the "View : Calculation Inputs menu item" and treat it as part of "View : Display Sub-Problem". 

Merged into master, closing.
