### ISSUE TITLE
System-wide input validation

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#131]
Find all "onChange" functions and check input for validity. Follow what was done in Action Trade. Specifically look into Action Seek, File Preferences and the main page.

**Comment by 1fifoto** [comment]
Here is one onChange from ActionTrade

        onArbitraryChange(i, event) {
    //        console.log('=========================== i=',i,' event=',event.target.value);
    //        console.log('state=',this.state);
            var design;
            const { store } = this.context;
            design = store.getState();
            var dir = [];
            var value;
            dir = this.state.ldir.map((entry,index)=>{
                var value;
                if (index === i) {
                    value = entry * parseFloat(event.target.value);
                    value = isNaN(value) ? this.state.dir[index] : value;
    //                console.log('i1=',i,' entry=',entry,' index=',index,' value=',value);
                    return value;
                }
                value = this.state.dir[index];
    //            console.log('i2=',i,' entry=',entry,' index=',index,' value=',value);
                return value;
            })
    //        console.log('dir=',dir);
            value = dir.reduce((value,dir) => {return Math.abs(dir) > value ? Math.abs(dir) : value}, 0.0);
    //        console.log('value=',value);
            this.setState({
                dir: dir,
                arbitraryContinueDisabled: value < design.system_controls.smallnum
            });
        }

**Comment by grumpyinca** [comment]
When making changes to Independent Variables on the main page, investigate if the JavaScript method .toPrecision() will provide a more attractive / less cluttered presentation.

**Comment by grumpyinca** [comment]
It is possible that changes for this issue could be combined with changes for issue #31.

**Comment by grumpyinca** [comment]
Alexey has suggested that input validation disallow input of negative numbers for quantities where they don't make sense.  Note that because there will always be a small number of cases like **Add_Coils@Solid** which sometimes require negative inputs, a very selective approach is needed.

**Comment by grumpyinca** [comment]
The intent of this issue is being / has been implemented in other branches, notably #31 and #590.
Closing with no code change associated with this issue.
