### ISSUE TITLE
Create prototype select-from-table feature

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#143]
We wish the Solid design type (problem) to have a user friendly way to select a material from a table and set the corresponding Density value.  See details in docs/design: [Idea for simple showcase problems](https://thegrumpys.github.io/odop/design/GeometricSolidsProblem).

This feature may be a prototype for features required by the Spring design type as well as the Select (standard) Size and Select Catalog features.

Note: a previous write-up of this issue seems to have disappeared.  This is a second attempt to create it.

**Comment by 1fifoto** [comment]
Merged in master, closing
