### ISSUE TITLE
Unexpected mis-match between Material & Density

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#151]
Steps to re-create:

Open a rectangular solid design type
Select a non-default Material.  Observe associated density.
SaveAs under a different name.
Open startup.  Observe that Material and Density now mis-match.

**Comment by 1fifoto** [comment]
The material sets the density, but not the opposite. Working as designed.

**Comment by grumpyinca** [comment]
I am not understanding why (how) the new density (non-default; SavedAs under a different name) carried over into the startup design.  In other words, why did I not get the same density that appears in a startup that happens right after launching a new browser session ?

**Comment by grumpyinca** [comment]
OK, now I have a better understanding.  At some point we need to have a conversation about [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and whether or not design change is required.

**Comment by 1fifoto** [comment]
This has been fixed with the changes for #156, closing
