### ISSUE TITLE
Unable to save changes in File : Preferences

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#153]
version 2.0; Heroku
iPad
Changes seem to reset after Apply and Close.
Seems to affect all values.

**Comment by 1fifoto** [comment]
Unable to reproduce. I need an exact sequence of user interface steps to reproduce.

**Comment by grumpyinca** [comment]
Unable to reproduce using MS Edge and localhost:3000.
Unable to reproduce using MS Edge and Heroku.

This isssue is looking like it is unique to my antique iPad and its older version of Safari.
I expect that this issue can be closed.
