### ISSUE TITLE
Consider tooltips on main page

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#158]
AndyR has suggested that the main page would benefit by tooltips on column headers.

Per discussion, tooltips might allow some of the column headers to be abbreviated and thus create a bit more flexibility in the layout.

Note:  I believe that tooltips are not supported on touch devices (tablet, phone) because there is no concept of "hover" as there is when working with a mouse.

**Comment by 1fifoto** [comment]
See #159 for possible solutions

**Comment by 1fifoto** [comment]
Merged into master, closing
