### ISSUE TITLE
Consider more prominent section boundaries on main page

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#159]
AndyR described his first impression of the main page of the Rectangular Solid design type.  

It took him some time to grasp that the main page was broken into sections (Independent Variables, Dependent Variables, Calculation Inputs & Results) and not just a large mass of entry fields.  Andy suggested that it might be helpful to have more prominent boundaries between the sections.

**Comment by 1fifoto** [comment]
Merged into master, closing
