### ISSUE TITLE
Consider Firefox-specific support

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#163]
AndyR was required to reduce font size in his Firefox browser in order to prevent the Max Constraint column from wrapping to the bottom.  Note: It is not known if he started with default font sizes or not.

Previous experience has shown that rendering of the main page in the Firefox browser is somewhat different (wider, shorter) than rendering of the page in the Chrome and Edge browsers.

Should Firefox-specific features be incorporated ?  Should the rendering of the main page be adapted to some sort of "lowest common denominator" ?

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
TomP, also a Firefox user, mentioned that he was required to reduce his font size setting to get the entire Rectangular Solid main page on (maximized) screen at the same time.  By the time he got the entire page on screen, font legibility was marginal.
