### ISSUE TITLE
Consider locking menu bar to top of window

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#167]
Currently, it is necessary for the user to scroll to the top of the main page in order to use the menu.  For small design types like PCyl, this is not an issue.  For larger design types like Spring, this incurs a fair amount of scrolling.

If it were possible to lock the menu bar at the top of the window, it might be possible for the user to do less scrolling by staying positioned in the zone of greatest interest.

**Comment by 1fifoto** [comment]
Merged into master, closing
