### ISSUE TITLE
Add tooltips for all design parameters, state variables and constants in initialState

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#168]
See #159, #158, and #163 for tooltip capability. This is a separate issue from adding tooltips for each and every title thorughout the programming. This issue is solely for updating the initialState.js file with "tooltip:" "<text>" entries.
![screen shot 2018-08-24 at 2 21 04 pm](https://user-images.githubusercontent.com/1581602/44603752-5ad4b080-a7a9-11e8-942b-23b19efafe5d.png)

**Comment by grumpyinca** [comment]
Merged into master.  Closing.
