### ISSUE TITLE
Update all Title tooltips with descriptive text

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#169]
Littered throughout the code are tooltips for each and every title. Search for UncontrolledTooltip and update the text between the <UncontrolledTooltip> and </UncontrolledTooltip> tags. Note: This is separate from adding tooltips into the initialState.js file, because it is in the programming.
![screen shot 2018-08-24 at 2 17 12 pm](https://user-images.githubusercontent.com/1581602/44603569-beaaa980-a7a8-11e8-9d4a-b00a7d7186e6.png)

**Comment by grumpyinca** [comment]
The actual words for each tooltip, case (capitalization) and use of line breaks may be open to debate.  I tried to make the words user friendly and somewhat non-technical.

Merged & pushed to remote master.  Closing.
