### ISSUE TITLE
Consider reallocating field widths in Result section

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#172]
Perhaps it is possible to allocate less space to titles ("Feasibility:" and "Termination Condition:" so that more width can be allocated to the ncode value.  Example of current situation:

![image](https://user-images.githubusercontent.com/39974784/44622225-5ec80780-a869-11e8-9fa8-1ec3f4eb90f3.png)

**Comment by 1fifoto** [comment]
I'm leaving this to you to make it "look purdy".

**Comment by grumpyinca** [comment]
I was not able to get colSpan working.  While I am not delighted with the following compromise, I think that overall, it is a slight improvement.

![image](https://user-images.githubusercontent.com/39974784/45055469-b7a35700-b044-11e8-8e1e-f98ea66ba880.png)

![image](https://user-images.githubusercontent.com/39974784/45055558-ff29e300-b044-11e8-92be-66c575e87d2c.png)

**Comment by grumpyinca** [comment]
Merged to master. pushed to remote.  Closing.
