### ISSUE TITLE
Suppress display of values for disabled constraints

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#173]
For both Design Parameters and State Variables, if the checkbox for a constraint is not checked, no value (cmin, cmax) should appear.  The box should appear to be empty (null or blank, not the value zero).

Once constraints are (re-)enabled, it is appropriate for the old cmin and cmax values to reappear.

**Comment by 1fifoto** [comment]
Merge into master, fixed in 166, closing

**Comment by 1fifoto** [comment]
Merge in master, closing
