### ISSUE TITLE
Investigate unexpected result with Spring problem Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#177]
When testing Spring by following the DOS program's Tutor8 as a guide, the case 
SEEK Maximum Force_2 
produces an unexpected result (Force_2 = 0.0).  Minor changes in the starting point produce the same result.

This could be an indication of a significant problem and needs further investigation.  Note that this is an example of Seek on an independent variable (aka Design Parameter).

An attempt to use the Piston-Cylinder design type to replicate the results with a roughly parallel case failed.  An attempt to use the Rectangular Solid design type to replicate the results with a roughly parallel case also failed.

**Comment by grumpyinca** [comment]
I created a (Spring) database entry with name Seek_Max_Force2.  If you open and invoke Seek Max Force_2, it fails (returns Force_2 = 0) in both master and branch 177.

**Comment by grumpyinca** [comment]
I encountered more anomalies when working with Seek in branch 171.  Following Demo4 as a guide, Seek produced wildly incorrect (infeasible) results on Seek Min Weight in the middle of the session.  Seek operation seemed correct for the last case of the session.

I suggest enabling the console output that matches the intermediate results produced by the PL/I code.  Perhaps it would be reasonable to make the console output dependent on the value of IOOPT or some unused component of the x vector.  Perhaps this output will suggest where the calculations diverge from what is expected.

**Comment by grumpyinca** [comment]
I recreated the (Spring) database entry.  The name is now Tutor8BeforeSeekMaxForce_2.

Note that the (Spring) database entry Tutor8BadResultAfterSeekMaxForce2 fails to open with the message: " GET of 'Tutor8BadResultAfterSeekMaxForce2' design failed with message: 'Unable to get property 'toFixed' of undefined or null reference' "

**Comment by 1fifoto** [comment]
re: note in previous comment. The Tutor8BadResultAfterSeekMaxForce2 file contains "value":null, which is causing the problem. Whatever process you used to create the file is the source of the problem.

...{"input":false,"name":"FS_CycleLife","value":null,"units":"ratio","lmin":0,"lmax":0,"cmin":1.02,"cmax":1.5,"ioclass":0,"sdlim":1,"tooltip":"Factor of safety to achieve the target cycle life category","equationset":true,"hidden":false,"smin":1.02,"smax":1.5}...

**Comment by grumpyinca** [comment]
Repairs committed, merged to master, pushed to remote.  Closing.
