### ISSUE TITLE
Error message when opening (Solid) startup

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#178]
"GET of 'startup' design failed with message: 'Cannot read property 'forEach' of undefined' "

Attempt to fix it by over-writing (Solid) startup with initialState failed.

After acknowledging error message, Solid seems to load initialState and then function properly.

**Comment by 1fifoto** [comment]
I think I have fixed this, please retry.

**Comment by grumpyinca** [comment]
I am now able to open "startup" in all three design types.  Thus the primary issue has been fixed.

However, there is one residual problem.  There were multiple designs available under the Solid design type.  I believe that they are old and, assuming that migration for this generation has not be implemented and tested, are best deleted so as not to carry over problems.

While design "startup" is open (noted in upper right) I select and attempt to delete the design "70PoundGoldBar".  The attempt fails with "DELETE of 'startup' design 'Solid' design type failed with message: 'Bad Request' ".

There is definitely something broken in there.  I get the feeling that something is causing the wrong design entry to be selected.  I don't know whether this is database corruption that would be cleared by deleting everything and starting fresh or there is actually something wrong in the code.

**Comment by 1fifoto** [comment]
OK, there was a long-standing problem in FileDelete. To test it out I deleted those old file. Please re-test and see if it now works for you.

**Comment by grumpyinca** [comment]
I tested on both localhost and Heroku.  Found no problems.  Closing 178.
