### ISSUE TITLE
Implement Functionally Determined Constraint Levels

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#180]
The Functionally Determined Constraint Levels feature was postponed to the Extension Spring design type.

The rectangular solid design type may provide a less complicated  test case.  See issue #179.

It may be desirable to work with PCyl-CLI before implementing in ODOP.

**Comment by 1fifoto** [comment]
I'm not interested in working on PCyl-CLI.

**Comment by grumpyinca** [comment]
Notes for Trade crash & traceback observed in current state of this branch.

Initialize ODOP in branch 180. With promptForDesign modal, select Spring\Extension and the design named TT_b4t (expanded in File:Properties as: Trade Test - before trade).  Note that this design was created by a search from TT_bis which was created by making three changes from initialState.  Invoke Trade.  Select either Proportional or Arbitrary (with no changes).  Accept default step size.  Observe: " TypeError: Cannot read property 'toFixed' of undefined
(anonymous function)
C:/Users/Mike/git/odop/client/src/menus/Action/ActionTrade.js:838 "

**Comment by grumpyinca** [comment]
Notes for crash & traceback observed in the current state of this branch.  I was unable to replicate this issue in the current master.

Initialize ODOP in branch 180.  With promptForDesign modal, select Spring\Extension. Use menu item Help : Demo and select demo6 (the default).  Click Next 3 times (reach page 04 of o9). Click on the FIX checkbox of Force_1.  Observe: TypeError: Cannot read property 'toString' of undefined
evaluateConstraintName
C:/Users/Mike/git/odop/client/src/store/middleware/evaluateConstraint.js:13

**Comment by grumpyinca** [comment]
The core FDCL work is complete.  Additional work on extension spring initialState, icons, and testing remains to be completed.

Merged to master, pushed to remote.  Closing.
