### ISSUE TITLE
"Restricted" variables listed as available for Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#186]
Variables defined in initialState.js with the property **"equationset": false** (formerly members of the d vector, a.k.a. "Constants") show up in the Seek drop-down as being available for selection.  This is incorrect and needs repair.

![image](https://user-images.githubusercontent.com/39974784/45123465-d6285180-b11b-11e8-9f31-1796fdcea802.png)

**Comment by 1fifoto** [comment]
Updated to check for equationset: true. Merged into master, closing.
![screen shot 2018-09-08 at 8 04 44 am](https://user-images.githubusercontent.com/1581602/45254451-00f1f000-b33e-11e8-9fcf-cc93a8ca29aa.png)
