### ISSUE TITLE
Do not display FIXed variables in the Seek selection list

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#194]
In the existing ODOP code. if the user attempts to Seek on a Fixed variable, Seek will return with a termination message that says something about Seek being inappropriate.

A cleaner, hopefully more user friendly approach is to not display FIXed variables in the Seek selection list so that the user is prevented from getting into that situation in the first place.

If this feature is implemented, please remove the code that implements the check and returns the message about Seek being inappropriate.

**Comment by 1fifoto** [comment]
Merged into master, closing
