### ISSUE TITLE
Implement View : Violations menu item

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#219]
As originally envisioned, the View : Violations menu item would be a check box on the View menu.  If checked, the violation columns on the main page ("Design:" tab) would be suppressed.  Other implementations are possible and perhaps preferred.

Notes:

1. It may be desirable and consistent to suppress the display of Result section "Objective Value" and OBJMIN at the same time.  Perhaps the OBJ and OBJMIN values could be incorporated into a tooltip on the feasibility string (the current tooltip on the "Feasibility:" label should be kept).

2. Issue #79 (Min and Max Constraint Table output when narrow has no names) describes how variable (symbol table) names need to be repeated when operating on a very narrow screen (cell phone) and the Constraint columns have been moved below.  It is possible that these two issues should be treated together.  Specifically, the screen width freed by removing the Violation column(s) could be utilized by variable names that really need to be repeated when operating on a narrow screen device.

**Comment by grumpyinca** [comment]
See issue #313.

**Comment by 1fifoto** [comment]
Question: Where should we store the View Violations setting? Should it be added to the Symbol Table as a hidden variable?

Separately, should we add the initialSystemControls, such as, ioopt to the Symbol Table too? I think so, but we'd need a new flag to indicate these are properties.

**Comment by grumpyinca** [comment]
I believe that the View Violations setting should be stored in initialSystemControls.  I am open to the idea that these values could be integrated into the Symbol Table.  I will create a new issue.

**Comment by 1fifoto** [comment]
Remove View Violations menu item and use File Preferences instead to set
show_violations in system_controls. Migrate all design types to have
show_violations in system_controls. Default to show_violations set to 1.

Coded and branch pushed to remote. Ready to integrate into master.

**Comment by grumpyinca** [comment]
Per phone conversation:
If it is easy to do, I think that we should include here a show_units that is parallel to show_violations.

Separately, I think that when ready, this branch should get merged into master.  I plan to rename a bunch of milestones so that the next release will be 3.3 rather than 3.2.4, thus denoting a change to the model and initialState.  Hopefully that approach will eliminate any need to base other branches from this one rather than master.

**Comment by 1fifoto** [comment]
Added to File > Preferences a show_units preference.

**Comment by grumpyinca** [comment]
Experiments in operating ODOP version 3.2.3 on my 720x1280 pixel cellphone lead me to believe that there is a need for an option to limit the header width.  

I propose show_FullHeader = 1 is the default and displays what is in place today.  show_FullHeader = 0 could display a width-limited subset.  Specifically, It would eliminate display of the ODOP logo and abbreviate tab names.  The "Design:" tab name could become "D:".  The "Report: 1 (mini)" tab name could become "R1", etc.

This change should reduce the occurrence of header line-wrap reducing the vertical screen space available for the rest of the page.  Vertical screen space available to the body of the main page becomes significant (critical!) when using the phone in landscape mode and also in entry mode (the virtual keyboard is displayed).

Finally, it seems attractive to replace the old View : Violations menu item with a new View : ScreenSize  menu item that allows the user to select between large screen and small screen operation.  Selecting LargeScreen would be the default and display everything (show_violations = 1, show_units = 1, show_FullHeader = 1).  Selecting SmallScreen would set the combination of: show_violations = 0, show_units = 0, show_FullHeader = 0.  The individual File : Preferences entries should remain to provide a more granular control over these quantities.  Perhaps it would be helpful for the View : ScreenSize modal dialog to have a Help button that links to an On-line Help article that explains its operation.  This button could follow the precedent set by Seek and Trade.

**Comment by 1fifoto** [comment]
Got a favor to ask, move the previous comment into two new issues. This one is getting too full of stuff. One for show_FullHeader = 1, and one for View : ScreenSize.

**Comment by 1fifoto** [comment]
Merged and closing

**Comment by 1fifoto** [comment]
Note: Updated with changes to offset.js for show_units and show_violations entries.
