### ISSUE TITLE
Unable to change label field in Execute script.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#233]
Using the successful example of changing a system preference in an Execute script (see Spring/tweakPrefs.js) I attempted to change a system property label with the syntax:

changeLabelsValue({COMMENT: "Compression Spring Demo"})

The result is a run time error in Spring/report.js that implies that the labels array is clobbered (TypeError: Cannot read property 'name' of undefined).

Per Slack conversation, I changed the last case in reducers.js to read:
        case CHANGE_LABELS_VALUE:
            return {
                ...state,
                labels: {
                    ...state.labels,
                    ...action.payload.labels
                }
            }

The results were similar … compile time error in report.js.

**Comment by 1fifoto** [comment]
Please try the following:

changeLabelsValue([{name: 'COMMENT', value: 'Compression Spring Demo'}])

**Comment by grumpyinca** [comment]
Changes made to reducers.js in branch 229.  Now merged to master and pushed to remote.  Closing.
