### ISSUE TITLE
Experiment with toPrecision() for Dependent Variables

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#239]
This is intended as a quick test to see if replacing toFixed() with toPrecision() improves the rendering of Dependent Variables without introducing any unintended consequences.

**Comment by grumpyinca** [comment]
I am disappointed !  While the handling of very small numbers is excellent … toPrecision(4) switches to scientific notation only after 5 zeros between the decimal point and first significant digit, the handling of very large numbers is not to my liking.  It switches to scientific notation as soon as there are more than 5 digits to the left of the decimal point.  Example:  
![image](https://user-images.githubusercontent.com/39974784/48667722-5f9bbe80-ea91-11e8-993c-e4daba05b405.png)

I do not plan to check this change into master at this time.  More thought is necessary.

**Comment by grumpyinca** [comment]
Here is an example that I worked out in an experimental version of report.js:  
    **var mikeForce2;
    if (p[o.Force_2].value < 10000.0 || p[o.Force_2].value >= 1000000.0) 
           mikeForce2 = p[o.Force_2].value.toPrecision(4);
    else mikeForce2 = p[o.Force_2].value.toFixed(0);**

I was not successful in developing the correct syntax to incorporate this approach into NameValueUnitsRowDependentVariable.js

**Comment by 1fifoto** [comment]
Add about class "NameValueUnitsRowDependentVariable" 

    Number.prototype.toODOPPrecision = function() {
        var value = this.valueOf();
        var odopValue;
        if (value < 10000.0 || value >= 1000000.0)
             odopValue = value.toPrecision(4);
        else odopValue = value.toFixed(0);
        return odopValue;
    };

**Comment by grumpyinca** [comment]
Working code:

Number.prototype.toODOPPrecision = function() { 
   var value = this.valueOf();
   var odopValue;
   if (value < 10000.0 || value >= 1000000.0)
        odopValue = value.toPrecision(4);
   else odopValue = value.toFixed(0);
   return odopValue;
};

**Comment by grumpyinca** [comment]
I noticed that Chrome is now reporting:  
./src/components/NameValueUnitsRowDependentVariable.js
Line 8:  Number prototype is read only, properties should not be added  no-extend-native.

This article:  
https://eslint.org/docs/rules/no-extend-native  
Seems to suggest that you can suppress the message.

**Comment by grumpyinca** [comment]
Adding:
/*eslint no-extend-native: ["error", { "exceptions": ["Number"] }]*/
suppresses the warning message.

**Comment by grumpyinca** [comment]
Merged to master; pushed to remote.  Closing.
