### ISSUE TITLE
DV marked as "hidden" leaves constraint fields visible

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#252]
If you mark a Dependent Variable as "hidden" in initialState, as expected, it does not display.  However, the corresponding entry fields for Min & Max constraints continue to display. 

Torsion spring example:
![image](https://user-images.githubusercontent.com/39974784/50195667-f22fb780-02f4-11e9-89ea-eb1cc4c345a8.png)

**Comment by 1fifoto** [comment]
Merged into master, closing
