### ISSUE TITLE
File : Save failure if single quote in COMMENT field

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#253]
Putting a single quote (apostrophe) in the File : Properties COMMENT field causes a File : Save failure.  

Messages on failure include:
Pop-up:
POST of 'Carlson_pg212HndbkSolution' 'Spring/Torsion' design failed with message: 'Internal Server Error'

Server command window:
SERVER: ===========================================================
SERVER: In POST /api/v1/designtypes/Spring/Torsion/designs/Carlson_pg212HndbkSolution
SERVER: 500 - INTERNAL SERVER ERROR

After the error has been encountered, all further database access will fail until after browser refresh (reset) of the main page.

I wonder if there are other special characters that will produce such failures.

The problem does not occur with a double quote.

**Comment by 1fifoto** [comment]
added to server.js design put, design post and note post

    value = value.replace("'","''"); // replace one single quote with an two single quotes throughout

Merged into master, closing
