### ISSUE TITLE
Resolve known security alerts / vulnerabilities in dependencies

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#276]
In the process, better document the procedures.

This will involve updating local Node libraries and re-publishing to Heroku.  

Even though this issue has been opened categorized as release 3.2, If addressed promptly, it should become release 3.1.2.

**Comment by 1fifoto** [comment]
From: https://nodejs.org/en/about/releases/. 
![Screen Shot 2019-10-20 at 8 43 46 AM](https://user-images.githubusercontent.com/1581602/67160415-06c64d00-f316-11e9-8495-be609500e7c4.png)

It looks like we should move to Node.js version 12. I am currently at Node.js version:

    Bris-MBP:~ briandwatt$ node -v
    v11.12.0

**Comment by 1fifoto** [comment]
Fixed in #247 Support Users.
