### ISSUE TITLE
Implement consistent naming convention for design files

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#283]
Capital first letter or not. Blanks or _ between words or not. Camel case or not.

**Comment by grumpyinca** [comment]
I propose a convention based on "upper camel case" as defined in [camelCase](https://en.wikipedia.org/wiki/Camel_case) but modified to use an underscore as a logical separation for capitalized abbreviations.  Thus expressing "OPOP spring design" in a design name would become: ODOP_SpringDesign.

**Comment by 1fifoto** [comment]
Merged into master, closing...
