### ISSUE TITLE
FELogin changes to add links to Sign-In page

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#287]
Experiment with changes to FELogin.js to add links to the Okta Sign-In page providing an explanation of ODOP user accounts (docs\About\userAccounts.md)

**Comment by 1fifoto** [comment]
Also remove links from PromptForDesign
![Screen Shot 2019-11-28 at 9 31 38 AM](https://user-images.githubusercontent.com/1581602/69818313-1b71ec80-11c2-11ea-8a8a-ab3fa8f9df48.png)

**Comment by 1fifoto** [comment]
Minor: change width of PromptForDesign modal to be large so "Open Design Optimization Platform" does not wrap to next line. Use the following:

    <Modal isOpen={this.state.modal} toggle={this.toggle} className={this.props.className} size="lg">

**Comment by 1fifoto** [comment]
Note: See later issue to enable/disable Prompt for Design links

Merged into master, closing...
