### ISSUE TITLE
Problems with design deletion

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#290]
Various problems associated with deleting design entries.  Both local and Heroku environments.

Easy to reproduce:  
Can't delete the last (non [ReadOnly]) design entry.  Create a first design.  Attempt to delete it.  Expect to see red error pop-up: "DELETE of '[object Object]' design 'Spring/Compression' design type failed with message: 'Not Found' ". 
Server window shows:
"SERVER: ========================================================
SERVER: In USE req.ip= ::ffff:127.0.0.1  req.method= DELETE  req.originalUrl= /api/v1/designtypes/Spring%2FCompression/designs/%5Bobject%20Object%5D
SERVER: In DELETE /api/v1/designtypes/Spring/Compression/designs/[object Object] user= 00u1oh7rgzjKvAAyv357
SERVER: 404 - NOT FOUND
SERVER: ========================================================"

Now create a second design.  Delete of the first design is now possible.

Not so easy to reproduce:
In local environment, while attempting to isolate the file deletion problems, the client and / or server can get hung up.  Spinner does not clear.  Closing browser window is not enough.  Break out of client console window causes backlog of messages to appear in the server console window.

**Comment by 1fifoto** [comment]
Good find. Dunno how this ever worked. Fixed, released to master, tagged 3.2.1, closing.
