### ISSUE TITLE
Add FELogin panel before each File Open/Save/SaveAs/Delete Menu item if logged out 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#293]
As currently implemented, an Okta session timeout (default 2 hours) leaves the user at risk of losing data.  It should be possible to mitigate this situation.  A bit of prototyping and testing may be required to find the best alternative.

Perhaps it is possible to test if the session is live before any operations (typically database access like File : Save, File : Open & File : Delete) that depend on Okta authorization.  If the session is not live, is it possible (reasonable) to go through the Okta Sign-in widget and get a call back to the main page without losing state (unsaved user input) ?
<hr>
This section transferred to a new issue.  See #329.   

 &nbsp; .

Perhaps it would be possible to create a menu item (perhaps named "File : User Account") that:
+ if signed in, displays: "Signed in as {username}" and a "Sign out" button
+ if the session is timed out, displays a "Sign-in" button

A user with unsaved data that has been away for a long period could pro-actively use this feature to renew the session before attempting to save.  Again, it would be necessary to preserve state during operation of the Okta Sign-in widget.  This feature would also provide a more intuitive sign-out opportunity as compared to the current need to get back to the promptForDesign modal.

**Comment by grumpyinca** [comment]
An "Auto-Save" feature is another approach to addressing this issue.  Auto-Save is attractive because it also addresses the risk of data loss associated with the user hitting the browser refresh button or browser back then forward.

For more detail on the Auto-Save idea, see:
https://thegrumpys.github.io/odop/design/AutoSaveFeature

**Comment by 1fifoto** [comment]
Started doing some work on this. Attempted at adding FELogin to FileOpen based on the code pattern in FEHome. That is, added checkAuthentication.

**Comment by grumpyinca** [comment]
Note the overlap with issue #296

**Comment by grumpyinca** [comment]
Expiration of the access token can be controlled as described in: [Okta JWT Access Token Expiration](https://support.okta.com/help/s/article/JWT-Token-not-respecting-Session-Lifetime-configured-in-the-Sign-On-Policy). 

Note that this is a simple extension the JWT access token expiration.  It does not include a refresh that would allow the expiration to extend with on-going session activity.  Thus, data loss is still possible.  Possible mechanisms to reduce the risk of data loss include potential enhancements:
  1 - JWT Refresh Token
  2 - Re-login after timeout with out loss of state
  3 - AutoSave

**Comment by grumpyinca** [comment]
Work on issue / branch #307 has eliminated much of the motivation for this approach.

Closing.
