### ISSUE TITLE
Investigate .toODOPPrecision() for Independent Variables

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#297]
The use of .toODOPPrecision() for Dependent Variables has been quite successful.  It was not applied to Independent Variables or Calculation Inputs because in most cases, it is necessary to maintain full precision internally.

This issue is being created to facilitate an investigation into use of .toODOPPrecision() for Independent Variables.  Specifically, the idea is to have the Independent Variable values normally displayed in .toODOPPrecision() format, but at the time that an Independent Variable is selected for change, that variable would be re-rendered in the cell at today's full precision.  Once the change had been made and the variable is unselected, it would be re-rendered at the normal .toODOPPrecision() precision.

With both Independent and Dependent Variables normally displayed at reduced precision, consideration should be given to reducing the associated column widths.

**Comment by 1fifoto** [comment]
Made changes to add in "focused" flag which is set to true when the input field has focus and false when the input field does not have focus (has blur). Then changes the value displayed: when "focused" display the value without toODOPPrecision(), and when not "focused" display the value with toODOPPrecision(). 

Updated branch, merged into master, pushed to remote, closing.

**Comment by grumpyinca** [comment]
See #298

**Comment by 1fifoto** [comment]
The toODOPPrecision() is broken. Reopening.

**Comment by grumpyinca** [comment]
Per Slack discussion, .toODOPPrecision() is not broken. The counter-intuitive behavior is the result of Spring/Compression Prop_Calc_Method set to 1 where any attempt to change a value is immediately over-written with the value from the materials table.

The counter-intuitive behavior may need to be addressed in a separate issue.

Already merged into master. Closing.
