### ISSUE TITLE
Enhance display of numeric Calculation Inputs with .toODOPPrecision()

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#298]
Similar to issue #297 but applied to Calculation Inputs that have a numeric value.

**Comment by 1fifoto** [comment]
Updates made, but the toODOPPrecision() is broken. Merged into master, but not closed.

**Comment by grumpyinca** [comment]
Per Slack discussion, .toODOPPrecision() is not broken.  The counter-intuitive behavior is the result of Spring/Compression Prop_Calc_Method set to 1 where any attempt to change a value is immediately over-written with the value from the materials table.

The counter-intuitive behavior may need to be addressed in a separate issue.

Already merged into master.  Closing.
