### ISSUE TITLE
Calculation inputs should change display of "reference values"

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#303]
The current behavior of Spring "Prop_Calc_Method" is not intuitive.  Most users attempting to alter a value that is determined by the material table will be confused by the value being immediately reset to the value in the table.  Similar problems are associated with the End_Type table.

Changing the display (gray out, disallow getting focus, create new "Reference Values" column, etc.) of those values that are determined by the materials table, end type table, etc. may resolve (mitigate?) the problem.

**Comment by grumpyinca** [comment]
Initial investigation suggests that the symbol table "input" value should control the desired behavior.  

Two areas of difficulty were encountered.  

  1 - Most significant, the symbol table is not passed into init.js where "Prop_Calc_Method" controls whether values come out of the materials table or are controlled by the user.  There may be work-arounds of various levels of kludge.  Directly changing code design to pass the symbol table into init.js would have wide-ranging impact.

  2 - Least significant.  There seems to be unanticipated behavior when (a bug?) when setting the "input" value (from false to true) for the first Calculation Input (Spring_Type).  See #xxx for additional details.

**Comment by 1fifoto** [comment]
This requires branch #303 to be integrated first.

**Comment by 1fifoto** [comment]
Quick test by setting the Calculation Input entry's "input" flag to true (note: this is inverted and goofy, but it's only a test) then the HTML input field is disabled, that is, read-only. 
![Screen Shot 2020-01-19 at 8 07 23 PM](https://user-images.githubusercontent.com/1581602/72693707-a783fe80-3af7-11ea-8d95-b5f31309fdf9.png)

Therefore this requires a model change to invert all Calculation Input flags which are currently set to false to be set to "true". Then only the Calculation Read-Only flags should be then set to false but some yet to be determined means.

**Comment by grumpyinca** [comment]
Per Bri in Slack conversation:
"The fix for catalog needs to be applied first before the Calc input change (a prototype of a possible change)"

Thus, the changes in branch #305 need to be applied before the changes in this branch (#303).  Perhaps it would be best to integrate #305 into master, then create a new branch from that in order to develop a final version of the Calculation Input changes.  This branch could be considered an investigation / prototype and closed without integrating anything into master.

**Comment by 1fifoto** [comment]
If this gets properly implemented we should not only specify whether or not a Calculation Input field is disable, but we should be able to hide or show them too.

**Comment by 1fifoto** [comment]
Merged and closed

**Comment by grumpyinca** [comment]
Note the overlap with issue #198 (now closed).
