### ISSUE TITLE
Investigate possible bug in Select Catalog code

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#305]
While pursuing #303, unexpected (funky!) behavior of the code implementing the Select Catalog feature was observed.  This should be investigated as a possible bug.  Specifically, when the "input" flag for the Calculation Input Spring_Type is changed from false to true in initialState, an error occurs at the time that the ODOP app launches.  

Branch #303 contains initial experiments attempting to isolate the problem.

**Comment by 1fifoto** [comment]
Checked in changes. The changes all over the palce (12 files) to check element.input along with element.equationset to differentiate Independent Variables (element.input && element.equationset), Dependent Variables (!element.input && element.equationset), and Calculation Inputs (!element.equationset).

**Comment by 1fifoto** [comment]
This requires branch #303 to be integrated first.

**Comment by grumpyinca** [comment]
Moving to milestone 3.2.3 so that this issue (#305) can be kept closely tied to #303.

**Comment by 1fifoto** [comment]
Merged and closed
