### ISSUE TITLE
Implement AutoSave feature

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#306]
As of this writing, there is not yet a complete specification for how an AutoSave feature should be implemented.  

For what exists, see the design article at:  [AutoSave](https://thegrumpys.github.io/odop/design/AutoSaveFeature)

Also, see the discussion in #293 and #94.

**Comment by 1fifoto** [comment]
Added TRADE action, invoke action at beginning of ActionTrade menu item, and add trade processing placeholder function in dispatcher.

**Comment by 1fifoto** [comment]
Removed TRADE action type. Instead adding SAVE_AUTO_SAVE, RESTORE_AUTO_SAVE, and DELETE_AUTO_SAVE action types.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
**From Slack Conversation:**

Logout, Load Initial State, Load Auto Save, File Open, File Save and File SaveAs causes the Auto Save File to be deleted after the function  
 
Action Search, Seek, Trade, Select Size and Select Catalog causes the Auto Save File to be created before the function   
 
Load Auto Save causes the Auto Save File to be restored.
 
All the rest of the functions are a No-op with regards to using the Auto Save File.
