### ISSUE TITLE
Okta session refresh and access token refresh

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#307]
As of the time that this issue is being opened, various alternatives to problems introduced by Okta session & token timeouts are still under consideration.  Thus, it is possible that code changes carried out on different branch(es) will ultimately supersede this issue.
<hr />
As this issue is first written, we know how to use the Okta Dashboard to extend the Okta session lifetime and the JWT access token lifetime.  However, these lifetimes are fixed and not dynamically extended by user activity.  If the current Okta implementation (checks access token for all File menu operations: Open, Save, SaveAs & Delete) is to be maintained, it will be desirable to "refresh" both the session lifetime and access token lifetime with continued user activity.  More on that point in the next comment.

.

The mechanism used to trigger session & access token refresh may overlap with the mechanism used to trigger AutoSave.  See #306. 

For background see: #293, #296.

Also see:   
[Okta Refresh Session](https://developer.okta.com/docs/reference/api/sessions/#refresh-session)
[Okta JWT Access Token Expiration](https://support.okta.com/help/s/article/JWT-Token-not-respecting-Session-Lifetime-configured-in-the-Sign-On-Policy)

Note that the second link contains additional links to interesting information.

**Comment by grumpyinca** [comment]
I have a hunch that refreshing the Access Token (or getting an entirely new token)  will also refresh the Okta session.

**Comment by grumpyinca** [comment]
Note that the design article on [AutoSave](https://thegrumpys.github.io/odop/design/AutoSaveFeature) has been expanded. This is significant for this issue because I believe there should be in overlap between the trigger mechanism for refresh and the trigger mechanism for AutoSave.

**Comment by grumpyinca** [comment]
Just for the record ... among others, the following pages were examined in today's conversation.  In my understanding, we are still looking for the correct API (not POST URL) to refresh the access token (assuming the session is also refreshed by that action).

[OpenID Connect & OAuth 2.0 API](https://developer.okta.com/docs/reference/api/oidc/#token)

[Get a Refresh Token](https://developer.okta.com/docs/guides/refresh-tokens/get-refresh-token/) says:  "The only flows that support Refresh tokens are the resource owner password flow, and the authorization code flow. This means that the following combinations of grant type and scope, when sent to /token endpoint, will return a refresh token"

[GitHub okta-react](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react)

**Comment by grumpyinca** [comment]
**Observations on today's state of development.**

After logout, Sitting at Sign-in Widget.  In console, repeating once per minute: 
browser-ponyfill.js:511 POST https://dev-729070.okta.com/api/v1/sessions/me/lifecycle/refresh 404

FEHome.js:41 In FEHome.componentDidUpdate before err= n {name: "AuthApiError", message: "Not found: Resource not found: me (Session)", errorSummary: "Not found: Resource not found: me (Session)", errorCode: "E0000007", errorLink: "E0000007", …}name: "AuthApiError"message: "Not found: Resource not found: me (Session)"errorSummary: "Not found: Resource not found: me (Session)"errorCode: "E0000007"errorLink: "E0000007"errorId: "oae-yDAKB8BQUyWlddqehXQcw"errorCauses: []xhr: {responseText: {…}, status: 404}__proto__: Error

Logout. Close & restart client.  Login. Open design.
Close browser tab.
Reopen browser tab.  No need to re-enter username & password.  Get to promptForDesign.
See message in console:
Uncaught TypeError: _this.props.onHide is not a function
    at Modal._this.handleClick (:3000/static/js/0.chunk
Possible to open design.

Close Browser tab.  Wait until after 5 minute timeout.  Re-launch localhost.
Get to promptForDesign, but see error messages: 
dev-729070.okta.com/api/v1/sessions/me:1 GET https://dev-729070.okta.com/api/v1/sessions/me 404
Normal operation remains possible even though the session has expired..

My impression is that in the situation where the session does not exist, control is getting to promptForDesign where it should be going to the Okta Sign-In Widget.

**Comment by 1fifoto** [comment]
Merged into master, closing
