### ISSUE TITLE
Remove unexpected tool-tip from .toODOPPrecision().

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#312]
Use of .toODOPPrecision() seems to be associated with an unexpected tool-tip referring to " ... nearest valid values ... ".  

The discussion in this [StackOverflow discussion](https://stackoverflow.com/questions/22835892/html5-input-type-number-pattern-not-being-enforced) may be related.

This issue provides a branch to experiment with eliminating the unexpected tool-tip.

**Comment by grumpyinca** [comment]
Based on a quick test in NameValueUnitsRowIndependentVariable.js, this works:

<Input className="text-right" type="number" **step="any"** value={this.state.focused ? this.props.element.value : this.props.element.value.toODOPPrecision()} onChange={this.onChange} onFocus={this.onFocus} onBlur={this.onBlur} /> : '' }

**Comment by 1fifoto** [comment]
Merged and closed.
