### ISSUE TITLE
Keep catalog number of selected entry; reset as appropriate

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#319]
The spring initialState has a hidden Calculation Input "name": "Catalog_Number" that was originally intended to hold the catalog number of an item selected from a catalog.

This idea needs to be expanded and implemented.  Other implementations are possible.  For example, the information could be posted as a File : Properties entry that then is included on Report 3.  Ideally, such a feature could be implemented in a way that is not design type specific.

Note that the "Catalog_Name" should be included as part of the data to be remembered.  Also, in the case where the user makes modifications to a table entry selected from a catalog, there needs to be a way to automatically reset the remembered "Catalog_Name"  & "Catalog_Number".

**Comment by 1fifoto** [comment]
Should the UI set the values modified by SelectCatalog to be read-only, AND/OR fixed.

**Comment by 1fifoto** [comment]
Merged into master, closing
