### ISSUE TITLE
Invert logic controlling input status

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#320]
The logic of:
`store.dispatch(changeSymbolInput("ASTM/Fed_Spec", true));`
is backwards from the natural way of thinking about making the field enabled for input.  It should be inverted.

**Comment by 1fifoto** [comment]
Coded and pushed to Github.

**Comment by 1fifoto** [comment]
Merged and closing

**Comment by 1fifoto** [comment]
Note: Updated with changes to offset.js for calc input changes of Solid model
