### ISSUE TITLE
Prepare to Integrate initialSystemControls into the Symbol Table

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#322]
For background, see #219.

It will likely be necessary to create one or more new flags.

There is a [docs/design article](https://thegrumpys.github.io/odop/design/SysControls) on this subject.

**Comment by 1fifoto** [comment]
This also allows them to have tooltips that describe the definition of the value

**Comment by 1fifoto** [comment]
Consider changing equationset to type with values "equationSet", "calcinput" and "systemControl".

**Comment by 1fifoto** [comment]
Merged in cascade of #219, #320, and #324 about offset.js goofs.

**Comment by 1fifoto** [comment]
Throughout the code we reference element.input then element.equationset. With this change I and flipping those to element.equationset then element.input. This is more consistent., because we need to know the type (was equationset) before we need to check whether it is input or not.

**Comment by 1fifoto** [comment]
Second phase of updates is to change "element.equationset" to "element.type === "eqiationset" and "!element.equationset" to "element.type === "calcinput" and get that to work without incident. This also includes migration changes.

**Comment by 1fifoto** [comment]
Merged and closed.
