### ISSUE TITLE
Improve order of spring Calc Input entries

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#323]
For each of the spring design types, it would be more logical to have End_Type positioned adjacent to the Calculation Input entries that are switched on when selecting "User_Specified".  Other changes are possible,

Considering the impact on initialState and the need to update Startup designs in the database, it may be desirable to combine this with any other pending changes that impact initialState.  If completed in the very near future, it may be possible to avoid migration.

**Comment by 1fifoto** [comment]
Merged and closed.
