### ISSUE TITLE
Replace ReactStrap with React-Bootstrap

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#324]
Start with a cost-benefit analysis.
  - Get Fluid images
  - other ?

[StackOverflow article](https://stackoverflow.com/questions/56061590/what-is-difference-between-reactstrap-and-react-bootstrap)

**Comment by 1fifoto** [comment]
Uninstalled reactstrap and installed react-boostrap. Surprisingly
nothing immediately blew up and failed. Wow!

**Comment by 1fifoto** [comment]
Sequence to switch to using react-bootstrap package for branch 324.
1. Cancel Client in Client window: Ctrl-C
1. In this client window, delete node_modules directory and all sub files and directories. In other words, delete all client npm packages. On Linux and Mac OS: rm -rf node-modules
1. In Eclipse, switch to branch 324.
1. Back in the client window, install all client npm packages: npm install
1. The in the client window, restart client: npm start

**Comment by 1fifoto** [comment]
Merged in #219 and #320 offset changes.

**Comment by 1fifoto** [comment]
Merged and closed
