### ISSUE TITLE
Entries in File : Properties do not expand

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#334]
With React-Bootstrap, the entries in File : Properties do not expand.  I liked ReactStrap's expanding field approach better.

**Comment by grumpyinca** [comment]
Want this:
![image](https://user-images.githubusercontent.com/39974784/74610865-d9af5e80-50ab-11ea-98df-fd6e0924038e.png)

Got this:
![image](https://user-images.githubusercontent.com/39974784/74610897-1f6c2700-50ac-11ea-994d-494137a5c55e.png)

**Comment by 1fifoto** [comment]
Change to use "textarea"

**Comment by 1fifoto** [comment]
Merged and closed
