### ISSUE TITLE
Improve handling of design type defaults

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#337]
Currently, the code does not properly handle the situation where designs of the default design type (spring/compression) are missing from the database.  In this situation, the Startup design of the first available design type should be selected.

Related:  
Perhaps the design type default should be specified as a Heroku environment variable as opposed to being hardwired.  See #294

**Comment by 1fifoto** [comment]
Don't forget to add the following Environment Variables to Heroku.

* REACT_APP_DESIGN_TYPE=Spring/Compression
* REACT_APP_DESIGN_NAME=Startup

Merged into master, closing

**Comment by grumpyinca** [comment]
Related to issue #282.
