### ISSUE TITLE
Extend coverage of usage log

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#342]
There is interest in extending coverage of the usage log.  More detail is provided in the first comment below.

Per discussion, different approaches are possible.  Performance implications and impact on the user experience are not yet fully understood.  Some prototyping work may be appropriate.  Google Analytics, with access provided through the react-ga package might provide more features and benefits as well as improved performance compared to inserting records in the current usage log table.  This might turn into a multi-phase development project.

If it turns out that that simple usage log updates applied at each menu invocation have unacceptable impact on the user experience, buffering may be a possible alternative.  If buffering is successful, there would be no need to develop an asynchronous approach to transmitting database updates.

The buffering idea is that each menu activation could push the appropriate information onto an in-memory  list.  At the time that each File menu operation does its currently implemented update to the usage log, the additional records from the list could be transmitted and the list cleared.  Thus, the extra data would be transmitted without new or additional database connections.  

Potentially, the logout sequence can be enhanced to execute a final update of any remaining data.

It is understood that such an implementation degrades to the current situation in the case where the user closes the app without executing a File menu operation or a logout operation.  Missing this information is viewed as an acceptable penalty to achieve the relatively low performance impact.

Also discussed was the notion that much of the desired information could be obtained in a non-user-identifiable way.  Specifically, it may be possible to simply maintain counts of menu invocations.

**Comment by 1fifoto** [comment]
Added logUsage to all Menu items
![Screen Shot 2020-02-29 at 10 40 29 PM](https://user-images.githubusercontent.com/1581602/75619666-84139100-5b44-11ea-8cd7-d0ff9538e453.png)

**Comment by grumpyinca** [comment]
Wow.  The performance impact seems completely invisible.

**Comment by 1fifoto** [comment]
On hold, pending evaluation of Google Analytics in #343
