### ISSUE TITLE
Warning: React does not recognize the `scheduleUpdate` prop on a DOM element

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#351]
Console messages, in red.

**Comment by grumpyinca** [comment]
After today's **npm update** I am seeing console messages:
index.js:1 Popper: "auto" placements require the "flip" modifier be present and enabled to work.

Perhaps related ... every time that I invoke a top-level menu, the Chromium Edge debugger triggers.  I am required to hit the "play" button multiple times to continue.

**Comment by 1fifoto** [comment]
Merged into master, closing
