### ISSUE TITLE
onHide error message in browser console

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#354]
Mostly cosmetic but worth looking into.  Hopefully, the fix is easy.

Modal.js:86 Uncaught TypeError: t.props.onHide is not a function
    at t.handleClick (Modal.js:86)

**Comment by 1fifoto** [comment]
When displaying PromptForDesign mouse click on the gray background to cause this error message in the Javascript console.

**Comment by 1fifoto** [comment]
![Screen Shot 2020-04-24 at 8 40 28 PM](https://user-images.githubusercontent.com/1581602/80268344-f350c180-866b-11ea-9fb1-319a38a5b846.png)

![Screen Shot 2020-04-24 at 8 40 54 PM](https://user-images.githubusercontent.com/1581602/80268346-f946a280-866b-11ea-8c4c-ef80bc4c668e.png)

On https://react-bootstrap.github.io/components/modal/ under 'Modal' it says: Specify 'static' for a backdrop that doesn't trigger an "onHide" when clicked.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
This problem seems to appear on every modal dialog box throughout the system.  I frequently trigger it when clicking to switch back from an over-lapping window.

**Comment by grumpyinca** [comment]
Fixed in branch #385.
