### ISSUE TITLE
Create config parameter for visible design types

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#355]
There is concern that non-spring design types are a distraction for spring design users.  Perhaps making these design types invisible will be helpful.

The exact implementation of this feature is not yet determined.  Perhaps it would controlled by a parameter added to the URL.  Perhaps it would be controlled by an environment variable.

**Notes:**
The current structure of the on-line Help assumes the availability of the Rectangular Solid design type.  If the Solid design type is not available, the Help files will need corresponding changes.

Issue #294 has a certain amount of over-lap with this issue.  A consistent implementation should be considered.

**Comment by 1fifoto** [comment]
Add new .env and .env.dist variable named REACT_APP_DESIGN_TYPES as a JSON array:

    REACT_APP_DESIGN_TYPES=["Piston-Cylinder","Solid","Spring/Compression","Spring/Extension","Spring/Torsion"]

As part of our release to Heroku we'll now need to set this configuration variable. If not set the default is ["Piston-Cylinder","Solid","Spring/Compression","Spring/Extension","Spring/Torsion"]

**Comment by 1fifoto** [comment]
Merged into master, closing
