### ISSUE TITLE
Warning message when invoking Action:Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#358]
April 14, 2020
Development / localhost:3000 
3.4 release in progress

set preference for IOOPT = 7
click Action: Seek menu item 
**Observed in console:**

index.js:1 Warning: Received `true` for a non-boolean attribute `outline`.

If you want to write it to the DOM, pass a string instead: outline="true" or outline={value.toString()}.
    in button (created by Button)
    in Button (at ActionSeek.js:96)
    in div (created by ModalFooter)
    in ModalFooter (at ActionSeek.js:95)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in ModalDialog (created by Modal)
    in div (created by Modal)
    in Transition (created by Fade)
    in Fade (created by DialogTransition)
    in DialogTransition (created by Modal)
    in Modal (created by ForwardRef)
    in ForwardRef (created by Modal)
    in Modal (created by Bootstrap(Modal))
    in Bootstrap(Modal) (at ActionSeek.js:72)
    in ActionSeek (created by Connect(ActionSeek))
    in Connect(ActionSeek) (at App.js:126)
    in div (created by DropdownMenu)
    in DropdownMenu (created by NavDropdown)
    in div (created by NavItem)
    in NavItem (created by ReactOverlaysDropdown)
    in ReactOverlaysDropdown (created by Dropdown)
    in Dropdown (created by NavDropdown)
    in NavDropdown (at App.js:124)
    in div (created by ForwardRef)
    in ForwardRef (created by Nav)
    in Nav (at App.js:108)
    in div (created by Context.Consumer)
    in Transition (created by Collapse)
    in Collapse (created by Context.Consumer)
    in NavbarCollapse (at App.js:107)
    in nav (created by Navbar)
    in Navbar (at App.js:104)
    in App (created by Connect(App))
    in Connect(App) (created by Secure)
    in Secure (created by withAuth(Connect(App)))
    in withAuth(Connect(App)) (at PromptForDesign.js:269)
    in Provider (at PromptForDesign.js:269)
    in PromptForDesign (created by Secure)
    in Secure (created by withAuth(PromptForDesign))
    in withAuth(PromptForDesign) (at FEHome.js:71)
    in div (at FEHome.js:71)
    in FEHome (created by Secure)
    in Secure (created by withAuth(FEHome))
    in withAuth(FEHome) (created by Context.Consumer)
    in Route (at FEApp.js:23)
    in div (created by Security)
    in Security (created by Context.Consumer)
    in withRouter(Security) (at FEApp.js:22)
    in Router (created by BrowserRouter)
    in BrowserRouter (at FEApp.js:21)
    in FEApp (at src/index.js:24)
    in div (at src/index.js:24)

**Comment by 1fifoto** [comment]
Merged into master, closing
