### ISSUE TITLE
Seek fails test. Results differ from previous release

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#359]
Seek failed automated test prompting further investigation.

In the test version, the development (localhost:3000) version and the staging version of the in-progress 3.4 release, Seek results are consistent but differ from previous results.  The Seek results of previous versions seem to be correct in that the solution is at the intersection of multiple constraints.  The in-progress 3.4 results seem incorrect in that the solution results are in mid-feasible region and incomplete in that not all independent variables have been changed.  For Seek test case #1 (PCyl seek min Stress), the previous results for stress (6270 psi) are significantly better than the in-progress 3.4 results (8469 psi).

An Eclipse **Compare With**  indicates that there are no changes in seek.js between release 3.3.2 and the current in-progress release 3.4.

If the Preference IOOPT is set >5, Seek will produce status information in the browser console.  

Based on comparing the status information, execution seems to go off the rails after message 05 (seek.js:65) and before message 06 (seek.js:77).  The code in that section makes reference to system controls and does a search.

Separate testing suggests that  the Search feature is operating properly.

**Comment by 1fifoto** [comment]
Old Seek Results using https://odop.herokuapp.com/

    seek.js:21 01 SEEK:    OBJ = 0
    seek.js:28 02A THE NUMBER OF FIXED INDEPENDENT VARIABLES IS: 0
    seek.js:29 02B THE NUMBER OF FREE INDEPENDENT VARIABLES IS: 6
    seek.js:63 03 THE CURRENT VALUE OF OD_Free IS: 1.1 inches
    seek.js:64 04 THE CURRENT ESTIMATED OPTIMUM IS: 0.9900000000000001 inches
    seek.js:65 05 ESTIMATING VALUE OF OPTIMUM ...
    seek.js:77 06 THE CURRENT VALUE OF OD_Free IS: 0.224226985440157 inches
    seek.js:78 07 THE CURRENT ESTIMATED OPTIMUM IS: 0.224226985440157 inches
    seek.js:110 11 SEEKING OPTIMUM OD_Free USING ESTIMATE OF: 0.224226985440157 inches
    seek.js:119 12 RETURN ON: OBJMIN 18 ITER.     OBJ =-0.00001618621708007658
    seek.js:121 13 CURRENT VALUE OF OD_Free IS 0.22386404677400246 inches

Current Seek Results using http://localhost:3000/

    seek.js:28 01 SEEK:    OBJ = 0
    seek.js:28 02A THE NUMBER OF FIXED INDEPENDENT VARIABLES IS: 0
    seek.js:29 02B THE NUMBER OF FREE INDEPENDENT VARIABLES IS: 6
    seek.js:63 03 THE CURRENT VALUE OF OD_Free IS: 1.1 inches
    seek.js:64 04 THE CURRENT ESTIMATED OPTIMUM IS: 0.9900000000000001 inches
    seek.js:65 05 ESTIMATING VALUE OF OPTIMUM ...
    seek.js:77 06 THE CURRENT VALUE OF OD_Free IS: 1.1 inches
    seek.js:78 07 THE CURRENT ESTIMATED OPTIMUM IS: 1.1 inches
    seek.js:110 11 SEEKING OPTIMUM OD_Free USING ESTIMATE OF: 1.1 inches
    seek.js:119 12 RETURN ON: OBJMIN - SHORT SEARCH     OBJ =0
    seek.js:121 13 CURRENT VALUE OF OD_Free IS 1.1 inches

**Comment by 1fifoto** [comment]
Added intermediate console.log debugging output

Version 3.2.3 Seek Results

    seek.js:65 05 ESTIMATING VALUE OF OPTIMUM ...
    seek.js:68 05A M_DEN= 99.00000000000001
    seek.js:72 05B M_DEN= 99.00000000000001
    seek.js:75 05C obj= -0.007735079974291013
    seek.js:78 05D M_NUM= 0.224226985440157
    seek.js:81 06 THE CURRENT VALUE OF OD_Free IS: 0.224226985440157 inches

Version 3.4 Seek Results

    seek.js:65 05 ESTIMATING VALUE OF OPTIMUM ...
    seek.js:68 05A M_DEN= 99.00000000000001
    seek.js:72 05B M_DEN= 99.00000000000001
    seek.js:75 05C obj= 0
    seek.js:78 05D M_NUM= 1.1
   seek.js:81 06 THE CURRENT VALUE OF OD_Free IS: 1.1 inches

**Comment by grumpyinca** [comment]
Merged to master, pushed to remote / origin.  Second round of testing looks good.  Closing.
