### ISSUE TITLE
Allow most operations without login

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#364]
Was titled: "Remove rough edges to user acceptance"

This issue covers changes that allow most operations without login.  Only File : Save, SaveAs & Delete require login.  Move major promptForDesign features to File : Open.

**Comment by grumpyinca** [comment]
**First pass notes & feedback**

Logged in or not, AutoSave does not appear to function

When "Login to select a personal design" appears  on File:Open, a link to an on-line help entry may provide more details.  Alternatively, a "Help" button below could provide a user with a way to access the desired info.

While I have lost track of the motivation, there was a change that made the promptForDesign modal wider.  If the same motivation is still there, a wider File:Open modal is perhaps desirable.

**Comment by grumpyinca** [comment]
**One more point**

It is my understanding that currently File : Save and File : SaveAs remove the AutoSave File after the function.  This applies to logged-in users only because not-logged-in users never get to that point.

If an AutoSave file was created when not-logged-in users invoke File : Save or File : SaveAs, then those users could transfer their work to a logged-in session.  Since such a feature is not particularly intuitive, the on-line Help entry referenced in my earlier comment will have to explain.

**Comment by grumpyinca** [comment]
**Related issues:**

#362 Help Menu Improvements
#xxx Change labels: Termination Condition, Obj, Objmin

**Comment by grumpyinca** [comment]
**Test results / feedback on development still in progress.**

File : Delete is disabled when logged in

LogOut doesn't appear to work (nothing seems to happen after click) until Reload.  

Logged in to staging system with same User ID in another tab.  Switched back.  See (in red):
POST of usage_log of note 'undefined' failed with message: 'Failed to fetch'
Later discovered that server command windows was blocked.  ^C produced responses to multiple backlogged interactions.

Can't reproduce:  First click on LogIn produces usageLog output in command window.  Second click required to get Okta Sign-in widget.

**Comment by 1fifoto** [comment]
Thanks for the feedback and for the numbers.
1. I need more information on what steps I must do to recreate this.
2. Fixed.
3. Investigating...
4. Investigating... I think this is related to # 3.
5. Performance problem with App and Reports being re-rendered over and over.
6. Investigating...

**Comment by grumpyinca** [comment]
**Steps to reproduce 1.**

- Start logged out
- Reload
- Login as Unit Tester
- File : Open; Browse available designs in Compression
- File : Open Extension, Load initialState
- File : Delete; observe that Compression private designs are available for selection
- Select one of those
- Click Delete; observe message

**Comment by grumpyinca** [comment]
On the subject of establishing the default design type and Startup design at session start or login ...

At login, there should be a design already established.  Perhaps it is:
- the Startup design 
- a user modification of the Startup design  
- a leftover from an immediately preceding logout   

can that already established design be maintained ?  

If starting a "fresh" session and there is AutoSave data available, could that data automatically become the current design ?  If so, does this mean that there is no need for a "Load AutoSave" button ?

**Comment by 1fifoto** [comment]
Re; 4. Extension & Torsion have the end-types that belong with Compression

Compression End Types showing problem
![Screen Shot 01 Compression](https://user-images.githubusercontent.com/1581602/83335225-e0379f80-a270-11ea-911b-2f073f7a1735.png)

Extension End Types showing problem
![Screen Shot 02 Extension](https://user-images.githubusercontent.com/1581602/83335231-eaf23480-a270-11ea-8f5a-cc635c5046bc.png)

Torsion End Types showing problem
![Screen Shot 03 Torsion](https://user-images.githubusercontent.com/1581602/83335235-f47b9c80-a270-11ea-8d1c-bd532eab972a.png)

**Comment by 1fifoto** [comment]
I have renamed the current 364 branch to 364-old. This branch contains the original attempt at providing most operations without login. Then I created a new branch 364 based upon the current or latest master. My intent is to move, copy, or merge code from 364-old to 364.

**Comment by 1fifoto** [comment]
Replace by #438, closing.
