### ISSUE TITLE
Change labels: Termination Message, Obj, Objmin

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#365]
There is concern that evaluators are negatively influenced by technical terms sitting right at the top of the main page (ResultTable.js).  

**Possible improvements:**

The label "Termination Message" should change to something shorter and less technical.  For example. "Status:", "Message:", "Solution Msg:" or "Msg:".  

The Objective Value and OBJMIN fields can be replaced with a "Solution Status" graphic (see comments below).  Alternatively, these fields can be suppressed until after the first use of Search, Seek, Select or Trade.  This change should serve to make the first impression and initial use of the app less intimidating.  Once displayed for the first time, these fields can remain visible.

**Comment by grumpyinca** [comment]
The label "Feasibility" at the upper left of the main "Design" page top status & information block might be less intimidating if changed to "Solution Status".

The numeric values of "Objective Value" (OBJ) and OBJMIN could appear as a tooltip.  The content of the text hosting the tooltip remains to be thought through.  Perhaps it could be formatted to look like a button with the text: "Status Details" or "Feasibility Details"

Consider adding a fourth feasibility category "Approaching Feasible".  It could have the same orange color as "Marginally feasible" and be associated with values of OBJ that are less than (4?) times OBJMIN.

Consider representing feasibility graphically with some kind of a progress bar.  For example:
```
                                V
  0____________|____________._________________________

```
In this case, the position of the V represents the current Objective Value.  The vertical bar is OBJMIN.  The dot is four times OBJMIN.  Feasible is represented with the V above the zero.  The scale of the horizontal line would be roughly logarithmic.  The whole thing could change color to match the current color scheme or perhaps have color coded zones.

**Comment by 1fifoto** [comment]
See: https://reactjsexample.com/tag/slider/
![Screen Shot 2020-11-07 at 2 18 38 PM](https://user-images.githubusercontent.com/1581602/98450678-2ccab500-2104-11eb-9354-5a40eae722d0.png)

**Comment by grumpyinca** [comment]
**Proposal for a new feasibility category and change to the feasibility color code.**

The current terminology and color scheme is:

OBJ value | &nbsp; | Category Term | &nbsp; | Color
--- | --- | --- | --- | ---
zero | &nbsp; | FEASIBLE| &nbsp; | Black
 < OBJMIN | &nbsp; | MARGINALLY FEASIBLE | &nbsp; | Orange
 \> OBJMIN | &nbsp; | NOT FEASIBLE | &nbsp; | Red

Dependent Variable fix violations are indicated (highlighted) with a cyan color

The proposed terminology and color scheme:

OBJ value | &nbsp; |  Category Term | &nbsp; | Color
--- | --- | --- | --- | ---
zero | &nbsp; | FEASIBLE| &nbsp; | Black
 < OBJMIN | &nbsp; | MARGINALLY FEASIBLE | &nbsp; | Green (or cyan)
 < 4x OBJMIN | &nbsp; | APPROACHING FEASIBLE | &nbsp; | Orange
 \> OBJMIN | &nbsp; | NOT FEASIBLE | &nbsp; | Red

Highlights for Dependent Variable fix violations should adopt the color of the current feasibility category.

Justification:
- Seek termination points are likely to incur modest constraint violations; there is a balance between the reward of improved performance versus the penalty of constraint violation.  The term "APPROACHING FEASIBLE" and orange color for this situation would be more appropriate and less threatening than the current "NOT FEASIBLE" and red color.

- Search terminates as soon as OBJMIN is reached.  User feedback indicates that the current term of MARGINALLY FEASIBLE and orange color is overly alarming.  The question was "_What do I need to do to make my design fully feasible_?".

**Comment by grumpyinca** [comment]
Note that on return from Seek, it is possible for the Objective Value (OBJ) to be less than zero (negative).  In the situation that OBJ is less than negative OBJMIN, the message 'TO FURTHER IMPROVE RESULT, RE-EXECUTE SEEK' is produced.  Re-executing Seek updates the estimate of the minimum (better dividing out the influence of the "merit function") allowing the constraints more influence in the solution and ultimately providing a result with an OBJ that is closer to zero..

This case should be tested to be sure that the Feasibility status indicator does not do something unreasonable.

**Comment by 1fifoto** [comment]
Things to do

* Change Feasibilty Tooltip to now include the four FEASSIBILITY strings.
* Add in status indicator.

**Comment by 1fifoto** [comment]
for the Objective Value (OBJ) to be less than zero (negative) => use absolute value of objective-value for the indicator

**Comment by 1fifoto** [comment]
See #449 for continuation and support of Feasibility Indicator in Results Table. Merged into master, closing.

**Comment by 1fifoto** [comment]
Remove "Termination" from "Message" - DONE.
