### ISSUE TITLE
Build local dev env for docs development

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#366]
Add Harp server for development

**Comment by grumpyinca** [comment]
**Web articles used in deploy docs to SpringDesignSoftware.org (Dreamhost server):**

[Git Hooks](https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks)

[Node on Dreamhost](https://help.dreamhost.com/hc/en-us/articles/360029083351-Installing-a-custom-version-of-NVM-and-Node-js)

[NVM](https://github.com/nvm-sh/nvm#install-script)

**Comment by grumpyinca** [comment]
**Notes from Node, etc. installation on SpringDesignSoftware.org (Dreamhost)**

1. NVM  Node Version Manager
- install NVM

2. Install node.js
- For a specific version of Node

(preceding steps done once)
<hr/>
(following steps in script)

3. Run NPM install
- For server

4. Run NPM
- npm run harp-compile

5. Copy results to website

**Comment by 1fifoto** [comment]
Merged into master, closing
