### ISSUE TITLE
Add File Import & Export

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#367]
**Export:** Capture data of current design as a file download.

**Import:** Retrieve such downloaded data so that it becomes the current design.

**Comment by grumpyinca** [comment]
**Test results / feedback on development still in progress.**

After I did the pull, the Report tabs were missing.  After another reload, all seems fine.

On the File : Import modal, if the "No file chosen" / file name field was on a separate line from the "Choose File" button, there would be more space to represent very long file names before they get clipped. 

I am not sure on this point but would "Select File" and "No file Selected" be more common or more consistent than "Choose File" and "No file Chosen" ?

No big deal, but would it make sense to have Export & Import section appear on the File menu before Preferences & Properties ?

Again I don't have a strong preference, but considering that it is necessary to Export before Import and that Export is earlier in the alphabet, does it make sense to have Export positioned ahead of Import on the File menu ? 

Don't forget that compile time warning: 
      ./src/menus/File/FileImport.js
      Line 2:44: 'Alert' is defined but never used no-unused-vars

This is all cosmetic stuff.  So far, I haven't found any functional problems with Export & Import.  I am really happy to have a capability that I had long ago written off as impossible.

**Comment by 1fifoto** [comment]
Did all except "Export positioned ahead of Import".

**Comment by grumpyinca** [comment]
I notice that for the Solid design type the three Report tabs are visible, but when clicked show "Not Implemented".  The current staging and production version do not display Report tabs.

**Comment by 1fifoto** [comment]
Merged into master, closing
