### ISSUE TITLE
Add "model: ODOP"

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#368]
We need a way to verify that a JSON file is an ODOP JSON file. So add "model: ODOP" and check it after parsing the JSON input.

**Comment by grumpyinca** [comment]
Note that issue #417 (Add units designation to initialState) impacts the same section of initialState.  Perhaps both changes should be handled at the same time.

**Comment by 1fifoto** [comment]
Included #417 as part of #368.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by 1fifoto** [comment]
Merged into master, closing
