### ISSUE TITLE
Add Google Ads code snippet

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#375]
Add Google Ads code snippet to link back to SpringDesignSoftware.org.

See 6/1/2020 email to Info@SpringDesignSoftware.org titled: "Codes with instructions [ ref:_00D361GSOX._5003x1yoJXB:ref ]".  The recommended code snippet is pasted in the next comment.

It is hoped (but not certain) that this will work to have Google's ranking algorithm not see a user coming to SpringDesignSoftware.org and clicking the "Launch Software" button as a "bounce" ... which is currently the case.

**Comment by 1fifoto** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-146047130-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-146047130-1', {
    'linker': {
      'domains': ['springdesignsoftware.org/','odop.herokuapp.com/']
    }
  });
</script>

**Comment by 1fifoto** [comment]
Also include domain: 'https://thegrumpys.github.io/odop/'

**Comment by 1fifoto** [comment]
See: https://developers.google.com/gtagjs/devguide/linker

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
See #377

**Comment by 1fifoto** [comment]
Update after discussion with Google Analytic consultants - the "tag team".

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-146047130-1"> 
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-146047130-1', {
        'linker': {
          'accept_incoming': true,
          'domains': ['springdesignsoftware.org','odop.herokuapp.com']
        }
      });
    </script>

**Comment by 1fifoto** [comment]
More updates, this time for Google Ad Words

    
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-659158420"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'AW-659158420');
    </script>
    <script>
      window.addEventListener('load',function(){
        if(jQuery('.okta-form-title.o-form-head').is(':visible')){
          gtag('event', 'conversion', {'send_to': 'AW-659158420/fPTOCOiopNQBEJTrp7oC'});
        }
      })
    </script>

**Comment by 1fifoto** [comment]
Merged into master, closing
