### ISSUE TITLE
Login failure when using Safari

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#377]
This issue was originally named:
"Login failure with iOS devices using Safari".

The failure has been observed with both iPhone and iPad running the current version of iOS (13.4.1) and using Safari.

We know that at some point in the not-too-distant past, recent iOS devices were successful at logging in with Safari.  The (Chromium based?) Brave browser is successful with iPhone 6s on iOS 13.4.1.  The Android 7.1.1 based Moto e4 is successful.  Apple Mac is successful with Chrome but not successful with Safari.

Further investigation is required.  Is it possible that the failure is related to a change in the ODOP code ?  It may be necessary to open a trouble ticket with Okta.

**Comment by 1fifoto** [comment]
Fails on my Apple MacBook Pro running Mac OS X 10.15.4 and Safari 13.1
![Screen Shot 2020-06-07 at 3 03 08 PM](https://user-images.githubusercontent.com/1581602/83979054-3049de00-a8d1-11ea-9908-a5663c0ed7d8.png)
![Screen Shot 2020-06-07 at 3 05 25 PM](https://user-images.githubusercontent.com/1581602/83979059-350e9200-a8d1-11ea-92ea-bc4d3aff5e74.png)

**Comment by 1fifoto** [comment]
The failure is in FEHome.js in its checkAuthentication function in the lines:

        if (session.status === "INACTIVE") {
    //        console.log('In FEHome.checkAuthentication INACTIVE session.status=',session.status);
            authenticated = authenticated && false; // Combine with session status
        }

If these lines are commented out the code works. If these lines are commented in the code fails.

**Comment by 1fifoto** [comment]
So I had to figure out an entirely new approach to getting the Okta uid because session was not valid. So I chose to use 

    var user = await this.props.auth.getUser();
    this.setState({
        uid: user.sub,
    });

**Comment by 1fifoto** [comment]
From slack

Bri  8:20 PM
OK, 377 is now done as V3.4.2 and put on heroku-staging, I've tested it on Chrome, Mac OS X Safari and iOS Safari, can you check it out on your system/iPad/iPhone. The change affected FEHome, PromptForDesign, and all File Menus.

8:20
I have not merged it into our advanced master branch. It is based upon tag 3.4, and branch 375. (edited) 

GrumpyInCA  8:38 PM
I will start testing now.
8:39
I just got off an extended Facetime call with the Chadwicks in N. Andover, MA.  They have lost phone service.
8:40
It looks like they are going to have to wait for Verizon to fix it.
8:43
MS chromium Edge on Windows 10 lets me log into the staging system with no problem.  It shows Software version  3.4.2. (edited) 

GrumpyInCA  8:49 PM
Chrome on Android 7.1.1 with Moto e4 lets me log into the staging system with no problem. It shows Software version  3.4.2.

GrumpyInCA  8:55 PM
Safari on iOS 13.4.1 with iPhone 6s lets me log into the staging system with no problem. It shows Software version  3.4.2.
8:57
Safari on iOS with iPad lets me log into the staging system with no problem. It shows Software version  3.4.2.
From my point of view, it looks like 3.4.2 can get pushed to production. (edited)

**Comment by 1fifoto** [comment]
Merged into master, closing
