### ISSUE TITLE
Scroll up when invoking Tutor/Demo/Execute

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#383]
Currently, if the user has scrolled down into a page before invoking a Tutorial, Demo or Execute session, there will be no change to the screen content when the user invokes the session.  This is counter-intuitive.  The user can get the impression that nothing happened.

One possible solution to this difficulty is to automatically scroll to the top of the page when the session starts.

**Comment by 1fifoto** [comment]
Possible insights from this StackOverflow entry: 

* https://stackoverflow.com/questions/53264924/react-setting-scrolltop-property-of-div-doesnt-work
* https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js

**Comment by 1fifoto** [comment]
UT does:

        $('.to-top').click(function() {
          $('html, body').animate({ scrollTop: 0 }, 'slow');
          return false;
        });

**Comment by 1fifoto** [comment]
Merged into master, closing
