### ISSUE TITLE
Fix End Type after File Import

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#385]
Also restore Design Type selector to File Open modal.
Also fix Design Type switching problems with Reports & Execute / Demo / Tutorial.
Also fix related problems in Save and Save As.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
Test results: 

The "Select design to delete:" dropdown correctly lists file to be deleted.  After clicking "Delete", a red error pop-up modal has the text: 
"**DELETE of 'Compress2_v3.5rc1' design 'undefined' design type failed with message: 'Not Found'**".

The console shows:
"Fetch finished loading: GET "https://odop-staging.herokuapp.com/api/v1/designtypes/Spring%2FCompression/designs"."
"DELETE https://odop-staging.herokuapp.com/api/v1/designtypes/undefined/designs/Compress2_v3.5rc1 404 (Not Found)"
"FileDelete.js:83 Fetch failed loading: DELETE "https://odop-staging.herokuapp.com/api/v1/designtypes/undefined/designs/Compress2_v3.5rc1"."

The server log shows nothing because this is on Heroku.

**Comment by grumpyinca** [comment]
Delete appears to work properly in v3.5rc2.  However, when using Import to switch Design Type, the selection of demo and tutorial files does not track.  In other words, after switching from extension to torsion and invoking the Help : Demo menu, the list of extension demo sessions appears even though a torsion design is current.  Attempting to execute one of those sessions produces an immediate return to the main page; no error message.

**Comment by grumpyinca** [comment]
Summary of 6/30/2020 testing of v3.5rc2plus:

With the exception of one rather cosmetic detail, Execute / Demo / Tutorial seem to be working properly, even after switching Design Types.  Both extension and torsion have demo sessions but no tutorial sessions.  In the production v3.4.4, for extension & torsion Help : Demo is enabled while Help : Tutorial is disabled (gray).  In the development v3.5rc2plus, both are enabled.  When invoking Help : Tutorial, the result is an empty selection list.  While not a big deal, the v.3.4.4 behavior is preferred.

There is a problem with File : Save As that does not require switching Design types to observe.
Start with browser reload
Load a design.  For example, compression Demo [ReadOnly]
Modify it (just to keep track. Perhaps change Comment property)
File : Save As with name "Y"
Notice that the design named Demo has been written "on top of" with the modified design.
Notice that there is no design named "Y".

**Comment by 1fifoto** [comment]
Repaired item 1 in "Summary of 6/30/2020 testing of v3.5rc2plus" above.

**Comment by grumpyinca** [comment]
Summary of 7/2/2020 testing with  v3.5rc3:

1. This "double Save" problem was discovered in staging, then reproduced in development master.  Steps to recreate:
browser reload
open a compression [Readonly] design.  I used Demo.
File : Save   (no problems observed)
File : Save   a second time.  Observe:
Red error pop-up modal with text: "POST of 'Demo' 'Spring/Compression' design failed with message: 'Bad Request' "
Console message: 
logUsage.js:10 Fetch finished loading: POST "http://localhost:3000/api/v1/usage_log".
FileSave.js:85 POST http://localhost:3000/api/v1/designtypes/Spring%2FCompression/designs/Demo 400 (Bad Request)
FileSave.js:85 Fetch failed loading: POST "http://localhost:3000/api/v1/designtypes/Spring%2FCompression/designs/Demo".
Server log message:
```
SERVER: 200 - OK
SERVER: ===========================================================
SERVER: In USE req.ip= ::ffff:127.0.0.1  req.method= POST  req.originalUrl= /api/v1/designtypes/Spring%2FCompression/designs/Demo
SERVER: In POST /api/v1/designtypes/Spring/Compression/designs/Demo user= 00u1oh7rgzjKvAAyv357
SERVER: 400 - BAD REQUEST
```
I attempt to recreate in 3.4.4 production system and report shortly.

**Comment by 1fifoto** [comment]
Great find. It was because after saving for the first time I forgot to add the new design's name to the array of names in File Save. So the second to nth File Saves would fail because it assumed it was a file-create and not an file-update. I've made the change, merged it into master and I'm tossing it over the wall to you to test it.

**Comment by grumpyinca** [comment]
Continuing summary of 7/2/2020 testing with v3.5rc3:

2. File : Export behavior not symmetric with File : Save As.
File : Save As will change the name of the current design to match the name given to the newly saved design.  Currently, File : Export does not.

**Comment by 1fifoto** [comment]
4. Repaired.
5. Defer to later release.
6. Defer to later release.

**Comment by grumpyinca** [comment]
Summary of 7/3/2020 testing with v3.5rc4plus in development:

7. The "double save" problem is back.

8. The Delete-yourself-then-Save problem:
Start with browser reload
Load a [Read/Write] design. 
File Delete the design that you just loaded
File : Save
Observe red error modal says: "PUT of 'Z' 'Spring/Compression' design failed with message: 'Not Found' "
Console says: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Server log says:
```
SERVER: 200 - OK
SERVER: ===========================================================
SERVER: In USE req.ip= ::ffff:127.0.0.1  req.method= PUT  req.originalUrl= /api/v1/designtypes/Spring%2FCompression/designs/Z
SERVER: In PUT /api/v1/designtypes/Spring/Compression/designs/Z
SERVER: 404 - NOT FOUND
```

**Comment by 1fifoto** [comment]
In "Summary of 7/3/2020 testing with v3.5rc4plus in development:"

7. The latest version branch 385 was not merged into master which included the repair of # 7. I don't know how I forgot to do this. I have now merged in branch 385 into master and pushed it to remote. I have not pushed it to heroku-staging.

**Comment by 1fifoto** [comment]
Merged into master, closing
