### ISSUE TITLE
Add Type Dropdown to File Delete

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#391]

**Comment by grumpyinca** [comment]
Summary of 7/3/2020 testing with v3.5rc4plus in development:

The Delete-yourself-then-Save problem:
Start with browser reload
Load a [Read/Write] design.
File Delete the design that you just loaded
File : Save
Observe red error modal says: "PUT of 'Z' 'Spring/Compression' design failed with message: 'Not Found' "
Console says: "Failed to load resource: the server responded with a status of 404 (Not Found)"
Server log says: 
```
SERVER: 200 - OK
SERVER: ===========================================================
SERVER: In USE req.ip= ::ffff:127.0.0.1  req.method= PUT  req.originalUrl= /api/v1/designtypes/Spring%2FCompression/designs/Z
SERVER: In PUT /api/v1/designtypes/Spring/Compression/designs/Z
SERVER: 404 - NOT FOUND
```

**Comment by grumpyinca** [comment]
Summary of 7/4/2020 testing with master in development (v3.5rc4 plus):

Possible for File : Delete to display mis-match of Design Type and design names
Browser refresh
Load any compression spring (initialstate will do)
Import any extension spring
File : Delete
Observe that file Type defaults to compression, but list of design names are extension names

**Comment by 1fifoto** [comment]
Merged into master, closing
