### ISSUE TITLE
File : Open can display inconsistent design names for design type

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#392]
Testing with v3.5rc4 has established that it is possible to get the File : Open dialog to display a set of design names that is inconsistent with the selected Design Type.  The easiest way to create the situation is to leverage Heroku's dyno startup lag. The situation illustrated in this screen capture was created by changing Design Type during the lag.  It persisted indefinitely with no spinner ever being displayed.  

I attempted to open a compression spring design name while the type selector was set for extension.  It failed with a red pop-up modal that said something about "not found".

 I speculate that there is some kind of race condition type of vulnerability in there somewhere.  While it becomes apparent as the result of Heroku's dyno startup lag, the vulnerability is always there.  I wonder if some kind of "await" would fix it.

![ExampleInconsistentNames](https://user-images.githubusercontent.com/39974784/86492498-30e46180-bd23-11ea-81d9-2e346e4fe8f0.png)

**Comment by grumpyinca** [comment]
I believe that at a high level, this issue can have many manifestations.  For example, when using the File menu for the first time after reloading the app, the spinner appears twice.  If the user makes a File menu selection too quickly (before the second spinner has exited) then the user will likely not get what he wants.

**Comment by grumpyinca** [comment]
This issue may share a common failure mechanism with #421.

**Comment by 1fifoto** [comment]
Mike will retest after 438 is available.

**Comment by grumpyinca** [comment]
Today's (12/31) test used the staging system (includes recent branch 438).

The screenshot below was taken during the delay required to start the Heroku dyno. It shows that the current model / design type is the rectangular Solid.  The File : Open dialog shows that the extension spring design type is selected but the Solid design names are displayed ... a mis-match that persists (without spinner) until the Dyno is started.  This seems to be an improvement over the initial report where the mis-match lasted indefinitely. 

While further testing may discover additional manifestations of the original report, closing this issue may require nothing more than getting a spinner to operate during the period of the display mis-match. 

![image](https://user-images.githubusercontent.com/39974784/103424267-081d1780-4b60-11eb-8a87-a1d6b8207efa.png)

**Comment by 1fifoto** [comment]
Made changes to set "names" property to an empty array ([]), merged into master, but not closing yet.

**Comment by grumpyinca** [comment]
Change to spinner.js:  style={{zIndex: 1100}}

**Comment by grumpyinca** [comment]
A big improvement.  Now shows "Running" but still no animated icon.  I think that it is time to quit while we are ahead.

![image](https://user-images.githubusercontent.com/39974784/103578417-6103ed00-4e8b-11eb-8cbe-e3858fb60aca.png)

Holding issue open for more testing and discovery of other manifestations of the original problem.

**Comment by grumpyinca** [comment]
Today's test provided an animated icon.  The modal did not accept inputs while the spinner was spinning.  

Continuing to hold the issue open pending more testing.

**Comment by grumpyinca** [comment]
In testing on the current staging system, I am unable to replicate the original problem.  Closing.
