### ISSUE TITLE
Seeking on the sole free IV has problems

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#403]
If  seeking the constrained extreme of a sole free Independent Variable and if that IV is not the first one, the results will be incorrect.  Specifically, setting IOOPT=6 and opening the console window shows Seek will attempt to move along the direction of the first IV, but since it is in FIXed status, the search will converge on Delmin and results returned by Seek will be unchanged.

For example in compression spring design, when L_Free is the only free IV, SEEK MIN L_Free will attempt to move along OD_Free.

There seems to be a **workaround**:
Free a second Independent Variable and set both its upper and lower constraint to the desired FIXed value.  Now that more than one IV is free, the results will be as anticipated.

**Comment by grumpyinca** [comment]
The significant code impact to implement the fix was in ActionSeek.js.

Testing is still in progress but I observe that the previous Seek variable and direction are no longer remembered as the default for the next use of Seek.  I would like to restore that remembering behavior.

To facilitate better understanding of issues raised in #404, I added:
```
        if (design.system_controls.ioopt > 5) {
            console.log('14 Merit Function = ', merit(design));
        }
```

**Comment by 1fifoto** [comment]
Updated: previous Seek variable and direction are remembered

**Comment by grumpyinca** [comment]
Merged to master, pushed to remote.  Closing.
