### ISSUE TITLE
Select Size, Catalog inconsistent; also, operation depends on prior Design Type

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#405]
The Solid Design Type has no standard size table and no catalog(s).  If Solid is the first Design Type opened, **Action : Select Size** is disabled but **Action : Select Catalog** is not.  If a design of the Solid Design Type is opened after a spring design, then **Action : Select Size** is enabled.

If a spring design is opened after a previously opened Solid design, then **Action : Select Size** is disabled for that Spring design.

This issue is tentatively assigned to milestone 3.6 because the fix might be relatively straightforward.  If that is not the case, then defer to a later milestone.

**Comment by grumpyinca** [comment]
Scenerio:
Start System, load Spring, Action:SelectSize shows enabled; File:Open select Solid, Select Action:SelectSize shows enabled.  This is wrong!
Start System, load Solid, Action:SelectSize shows disabled; File:Open select Spring, Select Action:SelectSize shows disabled.  This is wrong!

It appears the status of Action:SelectSize is only set on promptForDesign.  This is a systemic error.  Whenever the design type is changed the system does not respond to it.  For example, Select Size, Select Catalog, File:Open does not process the type change.

Deferring to milestone 3.7

Evaluate: Should this global problem be addressed before any changes to move login ?

**Comment by 1fifoto** [comment]
Sample console log shows constructor and componentDidMount when promptForDesign is executed, but later when the model type changes only render is executed.

**Comment by 1fifoto** [comment]
Added componentDidMount and componentDidUpdate to call an update function to refetch the size.js or catalog.js files when the type changes.

**Comment by 1fifoto** [comment]
Merged into master, closing
