### ISSUE TITLE
Improve extension spring default scaling denominators

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#412]
Improve extension spring default scaling denominators (sdlim) in initialState to improve catalog lookup behavior.
Also, improve consistency of cmin & cmax values.  
Make parallel changes to compression spring initialStates (US & metric) as required.
Torsion spring cmin & cmax values seem okay.

**Extension spring; US units**

OD_Free
cmax is now 2; increase to 10

 - Coils_T
cmax is now 20; increase to 100

 - Initial_Tension
cmax is now 0.0; increase to 40

- End_Extension
cmax is now 0.0; increase to 10

- Force_1
cmax is now 6; increase to 50

- Force_2
cmin is now 0; increase to 2
cmax is now 50; increase to 100

- Deflect_2
cmin is now 1; decrease to 0.1

- L_Body 
cmin is now 1; decrease to 0.1

- L_Free
cmax is now 20; increase to 100

- Stress_Initial
sdlim is now 2000; increase to 14000

- Stress_1
cmax is now 10000; increase to 30000

- Stress_2
cmax is now 10000; increase to 100000

- Stress_Hook
lmax is now 0; set to FDCL
sdlim is now 0; set to 150000  
cmax is now 10000; set to 52  (index)

- Cycle_Life - no change
sdlim increased 1000 to 10000 in v3.6

- %_Safe_Deflect
cmin is now 0; increase to 1

- Stress_Init_Lo
cmax is now 10000; increase to 20000

- Stress_init_Hi
cmax is now 10000; increase to 30000

**Extension spring; metric units**

- OD_Free
cmax is now 2; increase to 100

- Wire_Dia
cmax is now 0.5; increase to 20

 - Coils_T
cmax is now 20; increase to 100

 - Initial_Tension
cmax is now 0.0; increase to 100

- End_Extension
cmax is now 0.0; increase to 100

- Force_1
cmax is now 6; increase to 200

- Force_2
cmin is now 0; increase to 1
cmax is now 50; increase to 400

- Mean_Dia
cmax is now 10; increase to 100

- ID_Free
cmax is now 10; increase to 100

- Deflect_2
cmax is now 20; increase to 200

- L_Body
cmax is now 20; increase to 200

- L_Free
cmax is now 20; increase to 400

- L_1
cmax is now 100; increase to 500

- L_2
cmax is now 200; increase to 1000

- L_Stroke
cmin is now 0.05; increase to 0.5
cmax is now 100; increase to 500

- Weight
cmax is now 10; increase to 1000

- Stress_Initial
sdlim is now 20; increase to 100

- Stress_1
cmin is now 100;     decrease to 10
cmax is now 10000; decrease to 200

- Stress_2
cmax is now 10000; decrease to 1000

- Stress_Hook
lmax is now 0; set to FDCL
sdlim is now 0; set to 1000  
cmax is now 10000; set to 52  (index)

- %_Safe_Deflect
cmin is now 0; increase to 1

- Stress_Init_Lo
cmin is now 100; decrease to 10
cmax is now 10000; decrease to 200

- Stress_init_Hi
cmin is now 100; decrease to 20
cmax is now 10000; decrease to 400

**Compression spring; US units**

- OD_Free
cmax is now 2; increase to 10

- Wire_Dia
cmax is now 0.5; increase to 2

- L_Free
cmax is now 5; increase to 100

- Coils_T 
cmax is now 20; increase to 40

- Force_2 
cmax is now 50; increase to 1000

- L_1 
cmax is now 200; decrease to 100

- L_2 
cmax is now 100; decrease to 50

- Force_Solid
cmin is now 4; decrease to 1
cmax is now 100; increase to 1000

- Stress_1
cmin is now 100; decrease to 0

- Stress_2
cmax is now 10000; increase to 200000

- Stress_Solid
cmax is now 10000; increase to 200000

- PC_Avail_Deflect
cmin is now 0; increase to 1

**Compression spring; metric units**

- OD_Free
cmax is now 30; increase to 200

- Wire_Dia
cmax is now 3; increase to 50

- L_Free
cmax is now 100; increase to 400

- Coils_T 
cmax is now 20; increase to 40

- Force_2 
cmax is now 200; increase to 4000

- Mean_Dia 
cmin is now 0.2; increase to 1
cmax is now 50; increase to 200

- Deflect_1
cmax is now 20; increase to 200

- Deflect_2
cmax is now 20; increase to 400

- L_1 
cmax is now 500; increase to 1000

- L_2 
cmax is now 200; increase to 500

- L_Stroke 
cmax is now 100; increase to 400

- L_Solid
cmax is now 50; increase to 100

- ID_Free
cmin is now 2.54; decrease to 1
cmax is now 10; increase to 200

- Weight
cmin is now 0.1; increase to 1
cmax is now 100; increase to 10000

- Force_Solid
cmin is now 4; decrease to 1
cmax is now 100; increase to 4000

- Stress_1
cmin is now 10; decrease to 0

- Stress_Solid
cmax is now 10000; decrease to 2000

- PC_Avail_Deflect
cmin is now 0; increase to 1

&nbsp;

Note that operation of all extension spring Tutor & Demo sessions will need to be checked for unexpected behavior
and the introduction of inconsistencies with the discussion text.

To save effort, it may be best to include these changes in a release that has other changes to the initialState files.

**Comment by 1fifoto** [comment]
Merged into master, Closing
