### ISSUE TITLE
Add units designation to initialState

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#417]
Add an entry that designates units (US, metric or perhaps in the future, something else; SI perhaps) into initialState.  This should likely go into the "root" section (near the bottom).  This entry will allow a cleaner approach in future unit specific tests, for example in migrate.js.

Note that issue #368 (Add "model: ODOP") impacts the same section of initialState.  Perhaps both changes should be handled at the same time.

**Comment by 1fifoto** [comment]
Combine with #368, closing.

**Comment by 1fifoto** [comment]
Merged into master, closing
