### ISSUE TITLE
Integrate third-party downloadable 3-D CAD models

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#419]
[CADENAS PARTsolutions](https://partsolutions.com/)
[CADENAS / 3DfindIT](https://www.3dfindit.com/?lang=en_US)
[CADENAS / 3dfindit-freecad-integration](https://github.com/cadenasgmbh/3dfindit-freecad-integration)

[Dassault Systems 3D Content Central](https://www.3dcontentcentral.com)
http://www.3dpublisher.net/SWDownloads1/2044348281-259014/LeeSpring-MS24586-1.tif

[SolidComponents](https://www.solidcomponents.com)

Notes regarding a possible user interface:

Menu **View : CAD model**
If reasonable, the menu item could be disabled for cases that do not have a Catalog Name starting with MS24585 or MS24586.
If the catalog lookup had already occurred, simply selecting the menu item would produce a display of the CAD model.

More detail remains to be thought through.

**Comment by 1fifoto** [comment]
Initial first-pass.
![Screen Shot 2020-11-01 at 9 34 45 AM](https://user-images.githubusercontent.com/1581602/97808786-7ca20b80-1c2e-11eb-9562-c2c4de347dc3.png)

**Comment by 1fifoto** [comment]
There are still some hack left in the code that need repair...

* The app.js checks for Spring/Extension. If and when we get Compression that will need to be fixed. Maybe with a JS .startsWith("Spring/").
* In ViewCADModel.js the code is written exclusively for Extension springs. For example, it indexes into the symbol table with numbers which are only for Extension.

**Comment by grumpyinca** [comment]
Testing indicates that more lookup problems remain to be resolved.

The attached .zip file contains three exported extension spring designs, each named for the corresponding target Catalog_Number.  Each should produce the correct lookup to the corresponding entry in ODOP's MS24586 catalog.  However, in each case, the **View : CAD Model** lookup fails to  find the corresponding part in the CADENAS / SAE catalog.

[TroubledCADlookup.zip](https://github.com/thegrumpys/odop/files/5490199/TroubledCADlookup.zip)

**Comment by 1fifoto** [comment]
Could it be that those entries are just not in the CAD system? What is the behavior when they are not found? Does the system respond saying they are not available or does it just select some nominal spring?

P.S. I would prefer three independent attached files over a zip file.

**Comment by grumpyinca** [comment]
I don't think that it is missing entries.  Searching for -122 gets -124; -157 gets -61; -C257 gets -C209.  The last case appears to be a first-of-the-range response like we encountered with the L_Free rounding.  I haven't yet investigated the others.

P.S.  The .json file type is not an allowed attachment for GitHub comments.  Zip files are allowed.

**Comment by 1fifoto** [comment]
Modified branch 419 based upon email from Doug L. 

> Link one, The Basic Configurator.
> You can manually edit the OD, Wire Diameter, or number of coils.
> [(https://psdev-embedded.qa.partcommunity.com/3d-cad-models/sso?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj)](https://psdev-embedded.qa.partcommunity.com/3d-cad-models/sso?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj)
> 
> Link Two -, add your own parameters
> You can edit the parameter in this link, to bring up the spring with those characteristics
> [https://psdev-embedded.qa.partcommunity.com/3d-cad-models/?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj&varset={OD=12},{WD=3},{NOC=24}](https://psdev-embedded.qa.partcommunity.com/3d-cad-models/?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj&varset=%7bOD=12%7d,%7bWD=3%7d,%7bNOC=24%7d)
> 
> OD range =  8 to 20, in increments of .01
> Wire Diameter = 1 to 5, in increments of .001
> Number of coils = 5 to 100, in increments of 1
> You would programmatically add the values from your software, to build the link to build that spring.
> 
> Link Three, just the 3D view, and hides the table
> [https://psdev-embedded.qa.partcommunity.com/3d-cad-models/?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj&varset={OD=12},{WD=3},{NOC=24}&hidePortlets=navigation](https://psdev-embedded.qa.partcommunity.com/3d-cad-models/?info=usa_demo%2Fs%2Fspring_analysis_software%2Fspring_220mm_ss.prj&varset=%7bOD=12%7d,%7bWD=3%7d,%7bNOC=24%7d&hidePortlets=navigation)
> 
> To summarize, the idea is for your software to come up with the values from the analysis, build a link with those values in it, and call us to dynamically build the 3D view of that spring.
> 
> Also notice we can download a PDF summary ( can be rebranded and redesigned) and any CAD format. There are also image formats available in the list.
> 
> So give this a try and see if you like this type of tool and workflow.
> See if you can call this link with different parameters.
> See if you can put it inside an iFrame in the software.

Sample Screen shot based upon Link Three above.
![Screen Shot 2020-12-18 at 5 03 28 PM](https://user-images.githubusercontent.com/1581602/102669000-03fdfc80-4153-11eb-89ea-7715363b496e.png)

**Comment by grumpyinca** [comment]
Merged to master Jan 2, 2021.  This will become part of the 3.8 release.  Closing.
