### ISSUE TITLE
Add "model" property to top of hierarchy...

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#429]
Name the new top-level property "model". All existing redux state is underneath this new new top-level property. Move the existing inner "user" and "name" property up to be underneath this new new top-level property.

**Comment by grumpyinca** [comment]
Results of first testing session:

Open the Startup design of any design type.  Click the Action menu.  See:
```
ActionTrade.render
C:/Users/Mike/git/odop/client/src/menus/Action/ActionTrade.js:800
  797 |         <img src="favicon.ico" alt="Open Design Optimization Platform (ODOP) icon"/> &nbsp; Action : Trade : Not Feasible
  798 |     </Modal.Title>
  799 | </Modal.Header>
> 800 | <Modal.Body>
      | ^  801 |     The result is not feasible: obj = { parseFloat(this.props.design.model.result.objective_value).toFixed(6) }<br/>
  802 |     <ul>
  803 |         <li>Done &nbsp; - To return to the main page with these constraints</li>

```

**Comment by 1fifoto** [comment]
I have repaired the three aforementioned issues. Please retest and continue.

**Comment by grumpyinca** [comment]
Results of second testing session:

Open compression spring design named Startup.  User File : Preferences menu.  Change show_violations to zero.  Push "apply and Close".  See:

```
App.report
C:/Users/Mike/git/odop/client/src/components/App.js:100
   97 | 
   98 |        // Loop to create symbol_table
   99 |        var st = [];
> 100 |        this.props.symbol_table.forEach((element) => {
      | ^  101 |            st.push(Object.assign({},element));
  102 |        });
  103 | 
```

**Comment by 1fifoto** [comment]
I have repaired the one aforementioned issues.

**Comment by 1fifoto** [comment]
Merged into master, closing
