### ISSUE TITLE
Allow value inputs within Reports

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#432]
Details to follow.

**Comment by 1fifoto** [comment]
Here is a very rough first pass of converting to have inputs. Also the input fields do not allow entry yet. It's just a pretty picture that's not so pretty. Maybe it might be good for a discussion.
![Screen Shot 2020-11-18 at 4 04 27 PM](https://user-images.githubusercontent.com/1581602/99594031-38e22c80-29b8-11eb-95a1-45e9d9008437.png)

**Comment by 1fifoto** [comment]
Here is the latest after merging #433
![Screen Shot 2020-12-06 at 11 13 31 AM](https://user-images.githubusercontent.com/1581602/101287148-19b70d80-37b4-11eb-8ff9-cab08dc460a9.png)

**Comment by 1fifoto** [comment]
Fixed buckling message missing problem. Here is a sample of the current look & feel...
![Screen Shot 2020-12-06 at 10 31 19 PM](https://user-images.githubusercontent.com/1581602/101309864-fbccc580-3812-11eb-9d40-d5e0aa1799d5.png)

**Comment by 1fifoto** [comment]
Put units in middle table of Report1.
![Screen Shot 2020-12-06 at 10 34 19 PM](https://user-images.githubusercontent.com/1581602/101310010-59611200-3813-11eb-8408-6d65a5509f33.png)

**Comment by 1fifoto** [comment]
Still need to do Extension and Torsion Calculators.

**Comment by 1fifoto** [comment]
Here is the Extension Calculator
![Screen Shot 2020-12-09 at 2 38 42 PM](https://user-images.githubusercontent.com/1581602/101684615-53924900-3a2c-11eb-990f-54e68a8eaef6.png)

And the Torsion Calculator. Question: Should we show Coil_Spacing Independent Variable input? Why are we showing Arm_2 Dependent Variable which is input?
![Screen Shot 2020-12-09 at 2 39 52 PM](https://user-images.githubusercontent.com/1581602/101684741-7e7c9d00-3a2c-11eb-850c-5eaddc43cd05.png)

**Comment by 1fifoto** [comment]
Merged into master, closing
