### ISSUE TITLE
Move Reports to View menu

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#433]
The current Reports (1, 2, 3) should be moved to the View menu in order to free up the tabs for use as additional designs (see issue #434 ).

The currently favored approach has one entry on the View menu for each Report plus an entry to return to viewing the Design tab(s).

It is expected that this initial implementation will support only a single design rendered on a single tab.  Later, after issue #434 provides support for multiple concurrent designs, one per tab, then another issue / branch can extend this initial capability to view the same report on each of the multiple designs / tabs.

**Comment by 1fifoto** [comment]
Incorporated #371

**Comment by 1fifoto** [comment]
All coding complete. Please review for accuracy.

**Comment by 1fifoto** [comment]
Merge into master, closing
