### ISSUE TITLE
Reports sometimes fail after Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#445]
In testing with the current master branch, a traceback can be produced:

```
TypeError: Cannot read property 'toFixed' of undefined
Report1.render
C:/Users/Mike/git/odop/client/src/designtypes/Spring/Compression/Report1.js:36
  33 | <tr>
  34 |     <td>{this.props.symbol_table[o.Wire_Dia].name}</td>
  35 |     <td>=</td>
> 36 |     <td>{this.props.symbol_table[o.Wire_Dia].value.toFixed(4)}</td>
     | ^  37 |     <td className="text-left">{this.props.symbol_table[o.Wire_Dia].units}</td>
  38 |     <td> &nbsp; &nbsp; </td>
  39 |     <td>{this.props.symbol_table[o.End_Type].name}</td>

```
Steps to reproduce:

- Reset browser
- load compression spring initialState
- FIX Force_2  (at existing value of 40)
- Change L_Stroke MIN to a value of 1.7
- Seek Min L_Solid

Observe failure

Note:  The same sequence on the production system produces a good looking result with a Wire_Dia value of 0.1114656095433214 inch.

**Comment by 1fifoto** [comment]
Modifed steps to reproduce:

- Reset browser
- load compression spring initialState
- ~~FIX Force_2  (at existing value of 40)~~
- ~~Change L_Stroke MIN to a value of 1.7~~
- Seek Min L_Solid

**Comment by 1fifoto** [comment]
Was a subtle bug injected into RESTORE_INPUT_SYMBOL_VALUES. Merged into master, closing
