### ISSUE TITLE
Add Graphical Feasibility Indicator to Results Table

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#449]
Replace Objective Value with Graphical Feasibility Indicator & Tooltip to Results Table. The Tooltip should show both Objective Value and OBJMIN. 

See #365 for more details.  Specifically, 
 - Change Feasibilty Tooltip to now include the four FEASIBILITY strings.
 - Add in status indicator.

See:  [Example of graphical feasibility indicator](https://thegrumpys.github.io/odop/design/SimplifiedUI#advancedUI)

**Comment by 1fifoto** [comment]
It's getting there, but I haven't been able to get the Tooltip to work, Grrr!
![Screen Shot 2020-12-15 at 3 06 18 PM](https://user-images.githubusercontent.com/1581602/102272931-2b509180-3ee7-11eb-931f-0009a87084f4.png)

**Comment by 1fifoto** [comment]
Finally got it to work, but only on Text, so I added "Status". Suggestions welcome.
![Screen Shot 2020-12-15 at 3 39 01 PM](https://user-images.githubusercontent.com/1581602/102275929-bdf32f80-3eeb-11eb-8841-f65bfcb0832c.png)

I consider this now "Coded".

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
Nicely done !  I like it.  Questions:

 - Can the blue indicator triangle get larger ?  Can it overlap the color bar ?

- What do you think of making the red zone a tad wider ?  If the current is Green=30%, Orange=30%, Red=30%, what do you think of Green=25%, Orange=25%, Red=40% ?

- What about changing the scaling of the red section ?  Perhaps limit at 10**8 as opposed to the current 10**15 ?  What about breaking the red zone into two pieces: 4*OBJMIN to 1.0 and 1.0 to 10**8 ?

**Comment by 1fifoto** [comment]
1. Made the marker larger from 8px x 8px to 16px x 16px. Made the marker overlap to the middle of the color bar.
2. The width of each color is in pixels. Made the green 26%, orange 26%, and red 48%, in other words, 55px, 55px, and 100px.
3. Made the limit from log10 of 4*OBJMIN to log10 of 10**8, in other words from -3.7 to 8..
![Screen Shot 2020-12-16 at 5 21 40 PM](https://user-images.githubusercontent.com/1581602/102418833-2a416200-3fc4-11eb-9233-2cfca146f690.png)

**Comment by 1fifoto** [comment]
Merged into master, already closed.

**Comment by grumpyinca** [comment]
Now I REALLY like it.

At least on my monitor, the blue marker does tend to blend into the green section of the color bar.  It is fine the way that it is.  If you want to continue tweaking, I expect that less of an overlap (split the difference, 25% overlap?)  would mitigate that situation.

**Comment by 1fifoto** [comment]
Added white stroke around the marker to help eliminate the blend.
![Screen Shot 2020-12-16 at 7 52 26 PM](https://user-images.githubusercontent.com/1581602/102430834-8a420380-3fd8-11eb-962d-5bf067dfe0e1.png)

**Comment by 1fifoto** [comment]
Merged into master, already closed.

**Comment by grumpyinca** [comment]
Super !
