### ISSUE TITLE
Calculator view - select Wire_Dia from table

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#450]
Calculator view was developed on branch #432 (now closed).  This issue will provide a branch to develop the necessary code to add the ability to select Wire_Dia from the appropriate size table based on Material_Type.  

Includes compression, extension & torsion design types.  As with the operation of Select Size, after completion of a standard size selection, the value of Wire_Dia should be left in FIXed status.

See [View : Calculator](https://thegrumpys.github.io/odop/design/SimplifiedUI#simpleCalc) for background info on Calculator view.

**Comment by 1fifoto** [comment]
If the wire dia is 0.1055 in Advanced view and the size table has entries for ..., 0.105, 0.106, ... what should be selected in Calendar view? 

Or wire dia is 0.1055 in Advanced view and the size table has entries for ..., 0.105, 0.12, ...?

Right now I choosing the next largest, so 0.106 and 0.12 for the samples above. 

Also I only set FIXED is you select something. If you don't then the variable is not FIXED by default upon entering the Calculator. Is this OK?

**Comment by grumpyinca** [comment]
I like it !

Re: A. & B.
I believe that the current behavior of selecting the next larger size is correct for both A. and B.  Adding more metal is the more conservative, lower stress, higher cycle-life approach.  With case B., there will inevitably be situations where selecting the lower value will be closer to the designer's goals for Rate, specific deflections or minimum weight.  However, we are only talking about a default.  The user has the alternate choice right in front of them.  Anybody using a calculator has to be used to the notion of manual trial and error.

Re: setting FIXed
Yes, the current behavior is exactly what I expected.

**Comment by 1fifoto** [comment]
Based upon your above comments that what is there is acceptable, merging into master, closing.

**Comment by 1fifoto** [comment]
Added value_class and value_tooltip to number, text and table input types for SymbolValue and SymbolValueWireDia.

**Comment by 1fifoto** [comment]
Add option as first select entry to be the current value of wire diameter from the symbol table If this value is not in the table. Otherwise just choose the option that matches the value as the default. If this value is not in the table suffix the option value with the string "Not in table".

**Comment by 1fifoto** [comment]
How about changing "Not in table" to "Non-standard diameter" or simply "Non-std dia", for example, as in "0.1055 Non-std dia"?

**Comment by grumpyinca** [comment]
Yes, I think that either of those is an improvement.  Also, since "Dia" is in the variable name and "diameter" is in the tooltip, I could see leaving that out.  So,"Non-standard" or "Non-std".  While I haven't tested, I assume the Calculator View does not work well on small screens.  The "Non-std" alternative offers the best legibility as screen width diminishes.

**Comment by grumpyinca** [comment]
Made the "Not in table" to "Non-std" change described above (2 places).  Merged to master.  Pushed to remote.
