### ISSUE TITLE
Report1 buckling calculation / warning

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#453]
A problem with the compression spring buckling calculation and warning is apparent in the current master branch.  It was initially observed in branch 450.

Steps to reproduce:

1. Reset system
2. Load compression spring initialState
3. Observe the lack of buckling warning in Report1 & Calculator view seem correct for initialState.
4. Reduce the value of Wire_Dia enough to cause deflection greater than 100% of available deflection.
5. Observe the buckling result no longer matches the result of v3.6 on Heroku.
6. Re-establish the original value of Wire_Dia.
7. Observe the result does not change and no longer matches the initialState calculation and (lack of) warning.

**Comment by 1fifoto** [comment]
Please tell me a specific value for "the value of Wire_Dia enough to cause deflection greater than 100% of available deflection". I choose 0.01 and both the current master and ODOP on Heroku matched by producing.

    Given a deflection ratio of Infinity and a Slenderness ratio of 3.0,
    the spring will tend to buckle with fixed/free ends.
    The spring will not tend to buckle with fixed/fixed ends.

I was able to reproduce Step 6 and 7 thought.

**Comment by 1fifoto** [comment]
I have coded and checked-in the repair to Steps 6 and 7. It required setting this.error0=undefined, this.error1=undefined, and this.error2=undefined to reset these variable each pass through ReportBase's render function.

**Comment by grumpyinca** [comment]
Re: #4, With no other changes from initialState, imposing a Wire_Dia of 0.08 inch is the smallest change that will trigger the buckling warning.  It is also possible to trigger the warning by increasing the value of L_Free.

Operation of the buckling warning now appears to match the operation of version 3.6 on Heroku.  I think that it is appropriate to check this (453) branch into master and close it.

**Comment by 1fifoto** [comment]
Good catch, another message variable (this.pcadmsg) that needs to be initialized each time. Merging into master, closing.
