### ISSUE TITLE
Constraint highlighting problem in Advanced view

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#454]
I found this issue in branch #450.  While not yet confirmed, I expect that it is also observable in master.

Steps to reproduce:

1. Reset system
2. Load compression spring initialState
3. Change value of Wire_Dia to 0.111
4. Observe that the Min constraint on FS_2 is satisfied (viol= -48.1%); however, it is highlighted orange.  This Min constraint highlighting is incorrect.  The violation and highlighting of the Max constraint are as expected.

**Comment by 1fifoto** [comment]
Merged into master, closing
