### ISSUE TITLE
Extension, torsion Calculator constraint highlighting

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#455]
In branch 450 (and presumably the current master), the extension and torsion spring calculators fail to highlight a violation of %_Safe_Deflect in the sentence:

**Deflection at load point 2 is 94.61 % of total safe deflection.**

Steps to reproduce:

1. Reset system
2. Load extension spring initialState
3. Observe no constraint violations in Advanced or Calculator
4. Impose a value of 50 LbF for Force_2
5. Observe expected highlight of %_Safe_Deflect constraint violation in the Advanced View.
6. Observe no expected highlight of "Deflection at load point 2 is **94.61 %** of total safe deflection." in the Calculator View.

**Comment by 1fifoto** [comment]
Well this was an interesting problem. It took me a little while to unravel it. The reason why there is no highlight is this value is not the symbol table entry '%_Safe_Deflect" (shown on the Advanced view and highlighted) but is a computed value 'pc_avail_deflect' (computed by ReportBase, and shown on the Calculator view). 

The line in ReportBase

        this.pc_avail_deflect = 100.0 * this.props.symbol_table[o.Deflect_2].value / this.safe_travel;

The lines in the Calculator view are below use the <Value> tag which has no ability to highlight:

                    <table className="report-table">
                        <tbody>
                            <tr>
                                <td>
                                    Deflection at load point 2 is
                                </td>
                                    <Value value={this.pc_avail_deflect} />
                                <td>
                                    % of total safe deflection.
                                </td>
                            </tr>
                        </tbody>
                    </table>

We could change this to use <SymbolValue>, but you need to tell me. Also Report 1 needs to change too.

                    <table className="report-table">
                        <tbody>
                            <tr>
                                <td>
                                    Deflection at load point 2 is
                                </td>
                                    <SymbolValue element={this.props.symbol_table[o.PC_Safe_Deflect]} index={o.PC_Safe_Deflect} />                                <td>
                                    % of total safe deflection.
                                </td>
                            </tr>
                        </tbody>
                    </table>

**Comment by grumpyinca** [comment]
I have completed a superficial review.  A more careful cross-check and consideration of how to proceed remains.  Much has been lost to the fog of history.

I have confirmed that the old SpringSys had a pc_avail_deflect Dependent Variable that was used in compression spring Report1.  There was no comparable Dependent Variable, calculation or output for either extension or torsion springs.

While I have not searched through GitHub history to confirm, I speculate that the extension spring calculation of pc_avail_deflect local to Report1 was developed first. An equivalent was implemented in torsion spring Report1.  The next bit of speculation is that, somewhat later, the extension spring model (but not torsion spring!) got a Dependent Variable named %_Safe_Deflect.

At this point, I believe that your suggestion to switch extension spring Calculator and Report1 to use the SymbolValue of PC_Safe_Deflect is appropriate.  Do nothing with torsion spring in the short term.

Separately, I can open a new issue to add a Dependent Variable named %_Safe_Deflect to the torsion spring model and use that in torsion spring Calculator and Report1.  Migration should be included.

**Comment by 1fifoto** [comment]
Let's discuss this further on our next call. I want to make sure I fully understand.

**Comment by 1fifoto** [comment]
Awaiting input from the other grumpy.

**Comment by grumpyinca** [comment]
Coding complete.  More testing needed before merge to master.

**Comment by grumpyinca** [comment]
Added a Dependent Variable named %_Safe_Deflect to the torsion spring model and used that in torsion spring Calculator and Report1. Migration included.

Merged to master, pushed to remote.  Closing.
