### ISSUE TITLE
Develop "Welcome" execute sessions

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#459]
Once issue #388 is complete, "Welcome" execute sessions can provide users coming from the various SpringDesignSoftware.org landing pages a guided introduction.  Some experimentation will be required to determine how many of these sessions will be desirable.

Experiment with setting independent variables to null strings or NaN to see if that is helpful or introduces unintended consequences.

**Comment by 1fifoto** [comment]
From Slack...
> You can get a jump on weekend discussion.  Issue / branch #459 (Develop "Welcome" execute sessions) is ready for review & feedback. When you get a spare moment, switch to #459, Load compression spring, configure Calculator view and execute the "welcome1" script. Please visualize the impressions and response of an evaluator coming from SpringDesignSoftware.org website.  Please enter input values and watch the results. You can share your impressions in our phone conversation.

**Comment by grumpyinca** [comment]
We need a discussion about how the two welcome sessions should appear in execute.js.  Is it possible to keep then invisible to the end user ?

**Comment by 1fifoto** [comment]
Remove welcome0 and welcome1 from the table in execute.js to hide them. They should still be accessible via execute= parameter

**Comment by grumpyinca** [comment]
Renamed welcome0 to welcomeAdv and welcome1 to welcomeCalc.
Commented out the NaN from welcomeCalc (save for a future version).
Made corresponding changes to the text.
Merged to master.  Holding open for more testing.

**Comment by grumpyinca** [comment]
Copied to extension & torsion.  Merged to master. Encountered merge conflict in each execute.js. Repaired. Pushed to remote.  Tested.  Closing.

**Comment by grumpyinca** [comment]
Updated content.  Added many links.  Merged to master.  Pushed to remote. Closing for a second time.

**Comment by grumpyinca** [comment]
Both Welcome sessions really need a few words and a link to cover user accounts.

**Comment by grumpyinca** [comment]
Merged to master.  Pushed to remote.  Closing yet again.

**Comment by grumpyinca** [comment]
Added words to direct Firefox users to use Advanced mode.  
Merged to master.  Pushed to remote.
