### ISSUE TITLE
Improve FIX header and tooltip

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#463]
In the main page (Advanced) the header for the input group consisting of the value and Fix checkbox is:  "**Value (Fix)**".  It is possible that changing this text to: "**Value (Fix-Free)**" might better communicate the underlying concept.

Perhaps introducing a checkmark symbol adjacent to "**Fix**" and empty checkbox symbol adjacent to "**Free**" would be helpful.

The existing tooltip is: "Current values  (Check box at right to FIX)" should change to "Current values.  (Check box at right to FIX. Clear box to FREE)".

Consider breaking the Fix checkboxes out of the InputGroup so that they can have a separate tooltip.

**Comment by 1fifoto** [comment]
Please get a Font Awesome account at https://fontawesome.com/ so we can use their icons.

**Comment by grumpyinca** [comment]
***********************
Font Awesome account
***********************
Username:	Info@SpringDesignSoftware.org

1st used in:	2020
Fav icon: 	checkbox
02372b2b56
<script src="https://kit.fontawesome.com/02372b2b56.js" crossorigin="anonymous"></script>
https://fontawesome.com/kits/02372b2b56/use?welcome=yes
***********************

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
Changed tooltip wording.

![image](https://user-images.githubusercontent.com/39974784/103236987-3352fd00-48fb-11eb-9ef8-bf8370794221.png)

Merged to master. Pushed to remote.  Already closed.
