### ISSUE TITLE
Make "Message:" an array. Display as dropdown.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#465]
The "Message:" field in ResultTable.js should become an array.  It should display as a drop-down with the most recent entries at the top.  

It is reasonable to limit the size of the array to the 10 most recent entries.

The first entry can be pre-populated with something like "Welcome to ODOP!"

**Comment by grumpyinca** [comment]
The resolution of this issue should be coordinated with / integrated with the resolution for issue #569.

**Comment by 1fifoto** [comment]
Replaced by Alert facility.
