### ISSUE TITLE
Unexpected behavior observed with v0.3 on Heroku; Edge browser

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#47]
Steps to repeat:

Launch app from https://pcyl-web.herokuapp.com/
Observe expected: DP= 500, 0.4, 0.04; OBJ = 0.56051
Invoke Action : Search
Observe expected: DP= 697.2x, 0.582x, 0.0581x; OBJ = 0.14664
Click browser refresh
Observe unexpected: no change to displayed DP values; 
Observe expected change to SV & OBJ.
This is inconsistent !

Click on either piston icon or "PCyl-Web" in header field
Observe that DP values change; all is now consistent.

Note behavior with Chrome on localhost is as expected (not inconsistent).
Other combinations not tested yet.

**Comment by 1fifoto** [comment]
Please retest and write a comment about your results.

**Comment by grumpyinca** [comment]
Not able to replicate with v2.0 on Heroku and Edge browser.  The new PromptForDesign has changed operation considerably.

Closing.
