### ISSUE TITLE
Traceback in ViewCADModel.render 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#475]
Development environment. In master.
File : Open extension spring
load initialState
invoke View menu
Observe crash

TypeError: Cannot read property '0' of undefined
ViewCADModel.render
C:/Users/Mike/git/odop/client/src/menus/View/ViewCADModel.js:32
  29 | //        console.log('In ViewCADModel.render Catalog_Name=',catalog_name);
  30 | //        var material_type = this.props.symbol_table[37];
  31 | //        console.log('In ViewCADModel.render Material_Type=',material_type);
> 32 |         var od_free = this.props.symbol_table[0];
  33 | //        console.log('In ViewCADModel.render OD_Free=',od_free);
  34 |         var wire_dia = this.props.symbol_table[1];
  35 | //        console.log('In ViewCADModel.render Wire_Dia=',wire_dia);
View compiled
▶ 18 stack fr

No error messages in client command window

* * * * * * * * * * * * * * * * * 

On https://odop-staging.herokuapp.com/

Same initial steps
White screen
Console:
react-dom.production.min.js:209 TypeError: Cannot read property '0' of undefined
    at s.value (ViewCADModel.js:32)
    at Va (react-dom.production.min.js:182)
    at qa (react-dom.production.min.js:181)
    at xs (react-dom.production.min.js:263)
    at vl (react-dom.production.min.js:246)
    at ml (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Go (react-dom.production.min.js:122)
os @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
gi @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
wl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Go @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:248
sl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Go @ react-dom.production.min.js:122
Qo @ react-dom.production.min.js:123
Jo @ react-dom.production.min.js:122
M @ react-dom.production.min.js:287
Jt @ react-dom.production.min.js:68
react-dom.production.min.js:123 Uncaught TypeError: Cannot read property '0' of undefined
    at s.value (ViewCADModel.js:32)
    at Va (react-dom.production.min.js:18

**Comment by 1fifoto** [comment]
Only need to report details on development, and just mention it also occurs on odop-staging. I can't do anything with the traceback on staging because it's a production build.

**Comment by 1fifoto** [comment]
Fixed: change state.symbol_table to state.model.symbol_table. Merged into master, closing.
