### ISSUE TITLE
Add promptForDesign-like start with File : Open

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#477]

**Comment by 1fifoto** [comment]
Added "prompt" query parameter. Merged into master, closing. Mike to write short design article on URL query parameters such as type, name, view, execute and prompt

**Comment by grumpyinca** [comment]
See #388 for other link parameters.

**Comment by grumpyinca** [comment]
See: [URL syntax](https://thegrumpys.github.io/odop/design/URLsyntax)
