### ISSUE TITLE
ReferenceError: config is not defined getExecuteNames

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#478]
Traceback in development environment, current master branch:
```
ReferenceError: config is not defined
getExecuteNames
C:/Users/Mike/git/odop/client/src/designtypes/Spring/Compression/execute.js:3
  1 | export function getExecuteNames() {
  2 |     var result;
> 3 |     if (config.node.env !== "production") {
  4 |       result = [
  5 |         'mkHotWndStartup',        // Script to make Hot Wound Startup file from Load Initial State
  6 |         'mkHotWndStartup_Metric', // Script to make Hot Wound Startup Metric file from Load Initial State Metric
```
The problem was initially observed on the staging system.  White screen, Errors in console.

To re-create:
Launch with http://localhost:3000/
Drop down Action menu
Observe traceback

I have a hunch that this problem was introduced in #476.  If incorrect, my second guess would be #477 because the problem does not appear if ODOP is invoked with: https://odop-staging.herokuapp.com/?prompt

**Comment by 1fifoto** [comment]
Merged into master, closing
