### ISSUE TITLE
Execute "Back" not restoring values

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#483]
The "Back" feature of tutorial and demo sessions is correctly restoring text but failing to restore symbol table values.

I first noticed problems in the staging system. I an able to observe the same problems in the current master branch of the development environment. I checked the v3.6 production system on Heroku and confirmed that this problem does not occur there.

Steps to recreate:

Begin with a browser reload of the ODOP app and select compression spring Initial State from the File : Open menu. The Advanced view is used. If you see a red pop-up saying that AutoSave has been restored, reload the browser a second time.

Help : Demo, select longDemo, click Execute
Click Next, observe Objective Value = 0.000000
Click Next until page 6 of 13 is reached
Observe Objective Value = 1.3664... (all as expected so far)
Click "Back" button one or more times
Observe that the Objective Value does not return to 0.000000  (the problem!)

**Comment by 1fifoto** [comment]
Change next from "design.model" to just "design" to save and restore the entire Redux store. Merged into master, closing.
