### ISSUE TITLE
"Approaching Feasible" is confusing to user

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#485]
User wondered if "Approaching Feasible" should instead be "Approaching Not Feasible". Maybe it should not be associated or directed towards other feasibility labels (that is, Feasible and Not Feasible), but be more independent such as "Somewhat Feasible", "Possibly Feasible", "Approximately Feasible", "Nearly Feasible", OR "Somewhat Infeasible", "Possibly Infeasible", "Approximately Infeasible", "Nearly Infeasible", etc.

Also confused about "CONSTRAINT VIOLATION: Value outside constraint range from 1.000 to 1.500". Consider "CONSTRAINT VIOLATION: Value should be between 1.000 and 1.500" or "CONSTRAINT VIOLATION: Value should be from 1.000 to 1.500".

**Comment by grumpyinca** [comment]
"Close to Feasible" ?

OBJMIN represents a well defined boundary.  The search process considers Objective Values less than OBJMIN to be as good as feasible.  So, I am okay with calling a solution point with  Objective Value less than OBJMIN to be "Feasible".  Unfortunately, there is no precise definition for the other boundary of the orange zone currently named "Approaching Feasible".  That makes me less inclined towards "Approaching Not Feasible".  There is just no well defined boundary on the upper side of the orange zone that you can say that you are approaching.

Let's put this on the conversation agenda.

**Comment by grumpyinca** [comment]
Changed "Approaching" to "Close to".
Merged to master.  Pushed to remote.  Closing.
