### ISSUE TITLE
Execute scripts continue even after change of design type

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#494]
The Execute / Tutor / Demo feature is observed to continue execution (without any kind of alert) even if the user uses the File : Open menu to change the design type in mid-execution.  It seems that this situation might create great possibility for unintended behavior, including data loss.  Investigation with the version 3.6 production system suggests that this issue has been in place for a while, likely since the earliest days of the Execute / Tutor / Demo feature.

For whatever it is worth, the "Back" function seems to function as intended.  Thus, if alerted to the nature of the situation, the user should be able to "Back" his way out of the situation.

At the moment, I do not see any great usefulness in carrying execution of the script forward after the design or design type has changed.  While it might be reasonable to produce an alert and give the user a choice, I believe that it is also acceptable to immediately terminate execution of the script.

**Comment by grumpyinca** [comment]
Issue #536 is being closed as a duplicate of this one.

**Comment by 1fifoto** [comment]
Merged into master, closing
