### ISSUE TITLE
Unexpected result w/ load initialState after set FDCL to constant value 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#503]
This problem is carried forward from #480.

**Steps to duplicate the problem**
when working in the development environment master branch: 

Reload browser.
File : Open, Spring/Extension, Load Initial State.
Click in constraint entry field for Force_1 MIN.
Overwrite the value field with a new value (for example replace 6 with 7); Click Enter button.
Observe expected result in Main Page (Advanced View).
File : Open Load InitialState.
Force_1 MIN now incorrectly shows a value of 3 - (Note: 3 is the initialState cmin value)

**Note:**
This problem may not be easily observable in the production environment.  While initialState is routinely used in the demo and tutorial sessions, the user does not have direct access to it.  Loading the extension spring Startup design does not seem to produce the problem (at least not after migration anyway).  **Thus, it may be reasonable to push this issue into a future release.**

**Comment by grumpyinca** [comment]
Confirmed the described behavior is observable in current development master branch Oct 16, 2021.

**Comment by 1fifoto** [comment]
We should also test different combinations of open Startup & load initialState.

1. Present problem is load initialState, delete FDCL, load initialState.
2. Need to test is load initialState, delete FDCL, open startup.
3. Need to test is open Startup, delete FDCL, load initialState.
4. Need to test is open Startup, delete FDCL, open Startup.

**Comment by 1fifoto** [comment]
Presently Load-initial-state processes the initialState.js file into an object. Then operations are performed against that model which affect deeper components. So when a second Load-initial-state occurs, shallow entries are refreshed, but deeper components are NOT refreshed. Therefore it is necessary to make a deep copy of the initialState.js each time. This is so that Load-initial-state restores both the shallow entries and the deeper components too.

Change from 

    case LOAD_INITIAL_STATE:
        var module;
        if (action.payload.units === 'US') {
            module = require('../designtypes/'+action.payload.type+'/initialState.js'); // Dynamically load initialState
        } else {
            module = require('../designtypes/'+action.payload.type+'/initialState_metric_units.js'); // Dynamically load initialState
        }
        state = Object.assign({}, state, { 
            name: 'initialState',
            model: {
                ...module.initialState,
                system_controls: initialSystemControls
            }
        }); // Merge initialState and initialSystemControls
        return state;

to this by adding in: `module = JSON.parse(JSON.stringify(module)); // Make deep clone`

    case LOAD_INITIAL_STATE:
        var module;
        if (action.payload.units === 'US') {
            module = require('../designtypes/'+action.payload.type+'/initialState.js'); // Dynamically load initialState
        } else {
            module = require('../designtypes/'+action.payload.type+'/initialState_metric_units.js'); // Dynamically load initialState
        }
        module = JSON.parse(JSON.stringify(module)); // Make deep clone
        state = Object.assign({}, state, { 
            name: 'initialState',
            model: {
                ...module.initialState,
                system_controls: initialSystemControls
            }
        }); // Merge initialState and initialSystemControls
        return state;

Merged into master, closing
