### ISSUE TITLE
Active constraint highlights

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#505]
Question:
Should Calculator View display some kind of highlight (for example, the blue box highlight used in earlier ODOP versions when a Dependent Variable FIX was violated) when a constraint is active (checkbox is checked) ?

In Calculator View only versus all views ?

Should the highlight be a different color if FDCL is active ?  What about FIX ?

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
**Summary of what was implemented:**  (for transfer to docs)
<hr>
White background:  Input is enabled
Gray background:  Input is disabled

Bold left and right border:  This value is in FIXed status
Not-bold left border:  This value has an active (check in checkbox) MIN constraint
Not-bold right border:  This value has an active (check in checkbox) MAX constraint

Darker font:  This value is an Independent or Dependent Variable and can be FIXed or constrained
Lighter font:  This value is a Calculation Input or reference calculation and cannot be FIXed or constrained

Value color:  If a value is constrained and that constraint is violated, the value takes on the (Black, Green, Orange or Red) color of the Feasibility Indicator
