### ISSUE TITLE
Tutorial & demo changes for v3.8

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#506]
This issue provides a branch to develop changes in tutor & demo .js files associated with milestone 3.8.

**Comment by grumpyinca** [comment]
demo14 - changeSymbolConstraint('%_Safe_Deflect', MAX, 95.0); increased from default of 90

tutor0  - template code made available in non-production systems  
demo0 - template code made available in non-production systems

**Comment by grumpyinca** [comment]
After implementing this change in torsion spring initialState (see #510), the change to demo14 is unnecessary.  Reverting to the previous version of demo14.

**Comment by 1fifoto** [comment]
Merge into master, closing
