### ISSUE TITLE
Calc View violation tooltips words can be inappropriate

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#509]
There are two or more cases where the "outside the range of" wording of Calculator View tooltips can be inappropriate.  This can be an issue of applying the word "range" to a single sided constraint.  Also, Independent Variable FIX should not consider constraint levels, set or un-set.

The following cases start with extension spring Startup

**Case 1 Fixed Independent Variable**
apply value of 10.1 as MIN constraint for Coils_T
Coils_T has value of 10.0; observe expected color change of value (orange) indicating violation
observe tooltip "CONSTRAINT VIOLATION: value outside range of 10.1 to 100"  (not ideal, but OK)
un-set the constraint, set fixed status for Coils_T
observe tooltip "FIX VIOLATION: value outside range of 10.1 to 100"  (**NOT OK**)

**Case 2 FDCL Variable**
right click Force at point 1
change to constant (non-FDCL) constraint level of 7
change value of Force at point 1 to 5
Observe tooltip says: "CONSTRAINT VIOLATION: value outside range of 7 to 6"  (**confusing**)

**Comment by 1fifoto** [comment]
**Case 1** Added check If variable is an input (independent variable) then don't output FIX VIOLATION tooltip. Added checks if variable is only min constrained then output "CONSTRAINT VIOLATION: value less than 10.1", and if variable is only max constrained then output "CONSTRAINT VIOLATION: value greater than 100".

**Case 2** After the above change the following tooltip is now displayed "CONSTRAINT VIOLATION: value less than 7"

Merged into master, closing
