### ISSUE TITLE
Extension spring Calc View L_xxx values need lighter font

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#511]
In the Extension spring Calculator View (at bottom) the values of L_End, L_Body and L_Extended_End appear in darker (more bold) font.  Since they are Calculation inputs, they are not eligible to be FIXed or constrained.  To be consistent, they should appear in the lighter (less bold) font.

**Comment by 1fifoto** [comment]
I have a different interpretation of the font shade

Font Shade

* ~~Darker font: This value is an Independent or Dependent Variable and can be FIXed or constrained~~
* ~~Lighter font: This value is a Calculation Input or reference calculation and cannot be FIXed or constrained~~
* Darker font: Right click for context pop-up
* Lighter font: No right click for context pop-up

Therefore I don't think this is a problem. We should discuss this.

**Comment by grumpyinca** [comment]
The bottom line is that this issue should not have been written.  

I believe that I got off the rails by left-clicking on those values at the bottom of the page while expecting the response to a right-click.

Closing.
