### ISSUE TITLE
Calc View context modal tooltip partially hidden

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#513]
The FIX / FREE checkbox tooltip needs to be wider or more likely positioned below the target text.  See:

![image](https://user-images.githubusercontent.com/39974784/107169510-e2f7a200-6972-11eb-9797-250261f38ad5.png)

**Comment by 1fifoto** [comment]
Or, less text should be in the tooltip - tee her hee

**Comment by 1fifoto** [comment]
Added missing title. Merged into master, closing
