### ISSUE TITLE
Delete shows wrong design type selection after previous cross-type selection

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#518]
**Steps to reproduce the problem:**

Sign in
Confirm that compression spring designs are available for deletion 
Reload page  (establish consistent start point)
Open a torsion spring design
File : Delete - select compression spring design type
Click Cancel (not necessary to select a compression spring design or delete anything)
Go back into File : Delete
Observe that the compression spring design type is still selected (**this is wrong!**)
Observe that a custom torsion spring design name is selectable (this seems OK)

This screen capture illustrates the problem.
![image](https://user-images.githubusercontent.com/39974784/107894001-06769b80-6ee3-11eb-93b1-f058eeab96bf.png)

**Comment by 1fifoto** [comment]
Added setting the state's type when toggle is called to show the current model's type instead of the previous delete's type. Merged into master, closing.
