### ISSUE TITLE
Calculator view in FireFox - no right click for dependent variables

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#519]
In Calculator View, when using Firefox on Windows, the right-click context pop-up modal does not appear for dependent variables.  It does appear for independent variables.

Safari on Mac and iOS needs to be tested for this same issue.

**Comment by 1fifoto** [comment]
See: https://stackoverflow.com/questions/3100319/event-on-a-disabled-input. Specifically "Disabled elements don't fire mouse events. Most browsers will propagate an event originating from the disabled element up the DOM tree, so event handlers could be placed on container elements. However, Firefox doesn't exhibit this behaviour, it just does nothing at all when you click on a disabled element."

**Comment by 1fifoto** [comment]
This changes will not be done for this release. It is being scheduled for a later release. We tried "input[disabled] {pointer-events:none}" and "input::before { bottom: 0; content: ''; left: 0; position: absolute; right: 0; top: 0; }" without success but we could have applied this changes wrong. We did not try "place an element in front of the disabled input and catch the click on that element"

**Comment by grumpyinca** [comment]
Implementation of #577 will make this issue moot.  Closing without implementation.
