### ISSUE TITLE
Migrate: addition of Energy, %_Safe_Deflect is incomplete

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#528]
In Torsion migrate.js, for %_Safe_Deflect add:
```
        design.symbol_table[26].lmin = 0; 
        design.symbol_table[26].sdlim = 0.0; 
        design.symbol_table[26].tooltip = "Deflection of load point 2 as a percent of total safe deflection";
```
In Compression, Extension & Torsion migrate.js for Energy add:
```
            design.symbol_table[xx].lmin = 0; 
            design.symbol_table[xx].lmax = 0; 
```

**Comment by grumpyinca** [comment]
Having problems with %_Safe_Deflect & Force_Arm_2 in SMIp25FinalDesign of the ODOP_Tester@outlook.com account.  Need to discuss.

**Comment by grumpyinca** [comment]
Merged to Master. Pushed to remote.

**Comment by 1fifoto** [comment]
Removed FDCL migration from Compression and Torsion because there has never been any FDCL definition in initialState for COMPRESSION or TORSION. The user cannot create FDCL if it is not already configured in initialState. Merged into master, closing.
