### ISSUE TITLE
Dev sys Calculator View: console warning message on right-click

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#530]
In the development environment with the console opened, in Calculator View, when right clicking on a value in order to get  the FIX/FREE & constraint pop-up modal, a lengthy red warning message is observed in the console.  It begins:

```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
    in tr (at NameValueUnitsHeaderDependentVariable.js:11)
    in NameValueUnitsHeaderDependentVariable (created by Connect(NameValueUnitsHeaderDependentVariable))
    in Connect(NameValueUnitsHeaderDependentVariable) (at SymbolValue.js:243)
```

**Comment by 1fifoto** [comment]
Repaired by adding <thead> or <tbody> around Calculator SymbolValue's Table entries. Merged into master, closing.
