### ISSUE TITLE
Calc View context modal field backgrounds inconsistent

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#531]
Non-entry fields should have gray background. 

![image](https://user-images.githubusercontent.com/39974784/108604218-6648c880-7361-11eb-859a-94527ce91aaf.png)

In this case, Name, Units and Violation should be gray background.  Not sure about checkbox backgrounds.

**Comment by 1fifoto** [comment]
Added style={{backgroundColor: '#eee'}} to Calculator modal output in SymbolValue.
![Screen Shot 2021-02-20 at 12 39 22 PM](https://user-images.githubusercontent.com/1581602/108605351-35748d80-7379-11eb-8ed5-8fd7946a2c13.png)

Merging into master, closing
