### ISSUE TITLE
Crash invoking Action menu with migrated design containing catalog selection

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#534]
See Slack for exported design.
Reload
Import the design
Click Action menu
Observe that it cannot open the catalog files.
If the catalog files have been opened previously in the session, there is no crash

**Comment by 1fifoto** [comment]
There was a missing migration that needed to change from Catalog Name of 'catalog_ms_e_s' to 'MS24586_(SAE-AS24586)_e_stl' along with others in both Compression and Extension. There are no catalogs in Torsion so no change was made in its migration. Merged into master, closing.

**Comment by grumpyinca** [comment]
Oops! 
The generic catalogs need the same treatment.

**Comment by 1fifoto** [comment]
looks good, merge into master and close.
