### ISSUE TITLE
FDCL on dependent variables not updating

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#535]
In extension springs, there is an FDCL style constraint configured on the dependent variables Stress_Initial (Max & Min) and Stress_Hook (Max only).  The FDCL on Stress_Initial is Stress_Init_Lo (& Hi) which has a dependence on Wire_Dia, OD_Free and Calculation Inputs.  The FDCL on Stress_Hook is Stress_Lim_Bend which is dependent on Wire_Dia and Calculation Inputs.

It appears that the FDCL values do not update properly when underlying values like Wire_Dia change.

**Steps to illustrate the problem**

In development environment:  Reload browser  (establish repeatable starting point)
User authentication state should not matter
File : Open select Spring/Extension, Load Initial State
Note value of Wire_Dia (0.1055)
Note Min & Max constraint levels on dependent variable Stress_Initial (10183.372911818244, 16724.517555905873)
Change value of Wire_Dia to 0.120
Observe no change in Min & Max constraint levels on dependent variable Stress_Initial (still 10183, 16724) **The Problem!**
Click on the value of Stress_Initial Min
Observe the FDCL modal pops up
Click on the Stress_Init_lo button (re-establishes FDCL at the same values)
Observe that the Min constraint level on Stress_Initial is now 11623.  **Verification of the problem!**

This same scenario can be repeated with changes to OD_Free.
This same scenario can be repeated with the FDCL on dependent variable Stress_Hook Max.
This issue may be producing unexpected behavior in Action : Select Catalog

Dependent variables in the v3.6 production system on Heroku appears to operate correctly (as expected) with regard to this issue.  However there is a quirk with respect to the Independent Variable FDCL in the 3.6 system.

**Note:**  I have not been able to conclusively establish whether the FDCL values are getting updated properly in mid-search.  It is possible that this is simply a display updating problem and that the internal operations are actually operating as intended.

**Note:**  After this issue is resolved, go back and re-test Action : Select Catalog for unexpected behavior.

**Comment by 1fifoto** [comment]
Whenever invokeEquationSet is called then propagate(store) must be immediately called afterwards. Merged into master, closing.
