### ISSUE TITLE
Unable to open older compression spring designs

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#538]
Working with v3.8rc4 on the staging system, I do not have a problem opening older extension & torsion spring designs or newer compression spring designs. Attempts to open older compression spring designs fail with the red pop-up message:
`"GET of 'CompressB4Search' design failed with message: 'Cannot read property 'value' of undefined' "`

I am inclined to jump to the notion that this is a recently introduced problem in migrate.  However, I don't fully grasp the connection to a GET failure.

Since I am unable to open one of the failing designs so that I can export and attach it to this issue, I can only suggest looking in the staging database for a set of compression spring designs with names like: "Compress..." or "Pre-Set...".

**Comment by 1fifoto** [comment]
Screen shot of message
![Screen Shot 2021-02-24 at 3 30 59 PM](https://user-images.githubusercontent.com/1581602/109068343-5872aa80-76b5-11eb-93ec-6a96d160b31e.png)

**Comment by 1fifoto** [comment]
Repaired in #534, marking as duplicate and closing.
