### ISSUE TITLE
Stale data problem in Select Catalog

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#541]
It is possible for the Action : Select Catalog feature to show out-of-date information.  This can be corrected by switching to a different catalog and then switching back.

**Steps to create the problem:**

Browser reload; Reload the app (start from known conditions)
File : Open Spring/Extension; Load Initial State
   observe that the value of Initial_Tension is 6.0
Action : Select Catalog
   observe 4 designs available; 267-S is best
Switch to catalog MS..._e_stl
  observe "No acceptable entries were found in this catalog"
Cancel
Change the value of Initial_Tension from 6.0 to 3.0
Action : Select Catalog
  observe that it has remembered the selection of catalog MS..._e_stl  (not a problem)
  observe that it displays: "No acceptable entries were found in this catalog" (**This is the problem**)
Switch to the generic extension spring catalog
  observe that it displays: "No acceptable entries were found in this catalog"  (not a problem)
Switch back to catalog MS..._e_stl
   observe 4 designs available; #345 is best  (I believe that this is correct)

**Comment by 1fifoto** [comment]
Merged into master, closing
