### ISSUE TITLE
Review extension spring SI_Lo_Factor

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#544]
The extension springs in the MS24586 catalog consistently have an Initial_Tension value that is lower than that required by the default value of SI_Lo_Factor.  This presents a challenge for successful catalog lookups.  It needs to be determined if this is a quirk of the MS catalog or that there is a problem with the default value of SI_Lo_Factor.  A review of other spring catalogs may help.

**Comment by grumpyinca** [comment]
A survey of various extension spring catalogs available on the web shows that values of Stress_Initial always fall below the midpoint of the (Stress_Init_Lo to Stress_Init_Hi) range.  In some cases (typically larger springs), the Stress_Initial value falls well below the criteria provided by  Stress_Init_Lo.  The conclusion is that changes are appropriate to better align ODOP:Spring with industry practice and improve the reliability of catalog lookups.

Adding a new SI_Range entry was considered.  The name "Relaxed - improve catalog lookup" was proposed.  Conversation came to the conclusion that this approach would increase complexity and potentially introduce user confusion.  An alternative is to change the behavior of the existing "Special_Request" entry.  Prior to ODOP V4.2, selecting this entry increases the top end of the allowable Stress_Initial range but makes no change to the bottom end.  The proposal is to make the "Special_Request" entry increase the upper value and decrease the lower value.

A quick review of the code shows that the key values are contained in the material table columns labeled "silf","sihf" and"sisr" (Stress_Initial; lo factor; hi factor; special request).  The values are transferred into SI_Lo_Factor and SI_Hi_Factor in init.js.

Rather than introduce changes into the materials tables, it was decided to compute a reduced value for SI_Lo_Factor in init.js for the case where the SI_Range entry is set to Special_Request.

Corresponding documentation changes will be made in this issue in order to better synchronize the doc change with the code change.

**Comment by 1fifoto** [comment]
Merged into master, closing
