### ISSUE TITLE
AutoSave data causes startup problems

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#546]
Using the release 4.0 production system, I see various problems on startup, all related to the presence of AutoSave data.  I am still in the process of reproducing different variations / symptoms of the problem.  The flavor of startup seems to make a difference in the symptoms.

Variation #1:
A blue (merged) alert with the text:

`"Autosave file restored after interruption. Use FileSave, FileSaveAs or FileExport to save it permanently GET of 'USPS_MachinableParcels' design failed with message: 'Not Found' "`

when starting after a termination with AutoSave data.  The concern is the second portion of the message.

**Steps to recreate:**

Launch ODOP:Spring, 
Reload (create a repeatable starting point)
File : Open  Solid  USPS_MachinableParcels
Use Seek or Search to create AutoSave data.
Close the browser tab to terminate with AutoSave data preserved.
Navigate to SpringDesignSoftware.org website home page and click "Launch Software" in the upper right.
Observe the opportunity to re-open the Solid design type with USPS_MachinableParcels design
Select design type Extension; Select design Startup 
Click Open button
Observe the message:
![image](https://user-images.githubusercontent.com/39974784/109431747-e9e76280-79bc-11eb-817b-41deef9d8b17.png)

Different variations appear to be related to different startup parameters.  I will dig into those as time permits.

**Comment by 1fifoto** [comment]
Merged into master, closing - please re-test

**Comment by grumpyinca** [comment]
I have now convinced myself that my observed change in the default designs is the result of the changes made in this branch.  So, I am re-opening the issue.

More specifically ...
Load the current master with http://localhost:3000/  (no query parameters are required)
File : Open design type = Solid
Observe that the default design is 70PoundGoldBar  (should be Startup)
File : Open design type = Compression 
Observe that the default design is Demo  (should be Startup)

My conclusion is that the first (alphabetically) design is now the default.  The desired (& documented) behavior is to have Startup be the default design.

**Comment by 1fifoto** [comment]
Merged into master, closing - please re-test

**Comment by 1fifoto** [comment]
Mike said on Slack: I noticed that your latest fix in "AutoSave data causes startup problems #546" searched for a hard coded "Startup".  Why not use REACT_APP_DESIGN_NAME ?
Brian replied: Great idea!

Modified FileOpen.js to use config.design.name. Updated Staging to latest master.

**Comment by grumpyinca** [comment]
Slight variation on original problem report:

Reload (create a repeatable starting point)
File : Open Solid USPS_MachinableParcels
Use Seek or Search to create AutoSave data.
Close the browser tab to terminate with AutoSave data preserved.
https://odop-staging.herokuapp.com/?prompt
Observe the opportunity to re-open the Solid design type with Startup design.  (If Cancel, get AutoSaved data.)
Select design type Extension; Select design Startup
Click Open button
Observe the message:
![image](https://user-images.githubusercontent.com/39974784/110892186-7260df80-82a8-11eb-8c41-33addcd380ef.png)

There is at least one concern:   For this case, the message implies that AutoSave data was restored when it wasn't.

Note that the current milestone 4.1 contains issue #416 AutoSave Enhancements.  If fixing this latest problem introduces even more problems, I wonder if it may be expedient to disable AutoSave in a 4.0.1 and then bring it back after a careful rework at the time that #416 gets into the schedule.  In any case, I am reopening this issue to talk about it.

**Comment by grumpyinca** [comment]
For some reason, GitHub is not allowing me to edit the immediately preceding comment.  I am trying to insert the text:  

"**_It has somewhat belatedly dawned on me that the essence of the ?prompt query parameter is somewhat in conflict with the mission of AutoSave.  Perhaps we just need a clear specification of what should happen in this case.  My impression is that the current behavior is very close to the desired situation.  If it is possible / reasonable to suppress the incorrect message above in the case where the user has changed design type or design name, more complex changes may not be necessary._**"

above the final paragraph.

**Comment by grumpyinca** [comment]
Merged to master.  Pushed to remote & staging system.  Testing on staging system completed.  Closing.
