### ISSUE TITLE
Log usage improvement for tracing user behavior

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#552]

**Comment by grumpyinca** [comment]
Test results: 
Seems to work as designed.  No obvious negative impact on performance.

I view this implementation as a short-term situation.  Hopefully, it will provide enough information to guide short-term decision making.  In the longer term, it is a situation of improve it or remove it.

I am a bit concerned about the data multiplication.  A single user keystroke may turn into 30+ characters in the log.  Refinements in this area can wait until we better understand long term needs.

OK to merge to master and publish as part of v4.0.2.

**Comment by grumpyinca** [comment]
More changes included.

Merged to master, pushed to remote & published to staging & production as part of v4.0.2.  Closing.
