### ISSUE TITLE
Merit-biased Objective Value on-screen after Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#563]
This issue was originally observed in v4.04 on staging.  It is repeatable in V4.0.3 on the production system.  Thus it is not related to recent changes in #560. It is possible that this has been an issue for a long time.

To recreate, take the following steps in Advanced view of the Compression spring design type.

File : Open Startup    (get to a known consistent state)
Fix Force_1
Fix Force_2
Fix L_Stroke 1.75
Observe OBJ = 0.000525
Action : Search
Observe OBJ = 0.000007
Over-write the value of Force_1 (was 1) with 1.  This should not change OBJ.
Observe that OBJ does not change (is still 0.000007)
Seek Min Weight 
Observe OBJ = 0.00045
Over-write the value of Force_1 (was 1) with 1.  This should not change OBJ.
Observe that OBJ has changed to 0.000252  <--- This is the problem.

**Comment by 1fifoto** [comment]
After calling seek in the dispatcher.js we need to call updateViolationsAndObjectiveValue to recalculate the objective value WITHOUT the merit function value.

**Comment by grumpyinca** [comment]
Note: includes fix to logUsage of buffer/value.
Merged to master, pushed to remote.  Closing.
