### ISSUE TITLE
Improve consistency of spring weight calculations

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#564]
Spring weights are calculated separately in eqnset and reports (ReportBase).  In compression & torsion design types there are significant differences.  The comments in the code note that the eqnset calculations are "crude" and the report calculations are "more accurate".  The differences are greatest for compression springs with a large pitch and torsion springs with a large Coil_Spacing.

Perhaps the best approach to resolving the discrepancy is to move the more accurate calculation into each eqnset.  That will put the value into the symbol table (the model) where it can be accessed in the reports without recalculation.

**Comment by 1fifoto** [comment]
Merge into master, closing
