### ISSUE TITLE
Auto-Fix, Improve Calculator View ease of use

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#577]
This is a proposal for user interface features intended to address that significant fraction of evaluators that proceed into working with the software without first obtaining an appropriate conceptual grasp of FIX / FREE and constraints.  The proposal is visualized as changes to Calculator View inputs combined with a renaming from "Calculator View" to something else, perhaps     "{Compression | Extension | Torsion} Spring View".  **_Rename considered and deferred._**

While this proposal does not contemplate any changes specific to Advanced View, shared code may make it expedient for some changes in Advanced View behavior.  Also, if successful in guiding user behavior in desirable directions, future changes to make Advanced View more consistent may be desirable.

The most impactful aspect of this proposal is to eliminate Calculator View right-click while also eliminating direct "in cell" value changes.  Instead, any (left or right?) click on a cell that allows value inputs (the same independent & dependent variables where right-click is currently valid) would bring up an enhanced version of the dialog currently brought up by right-click.  Using this dialog to change a value would force that variable into FIXed status and provide a text message providing a reasonably detailed explanation of the implications.  See the embedded graphics for details.

This approach will force a change in handling of standard size table lookups.  Specifically in the spring design case, standard size tables for Wire_Dia and OD_Free.  Possible approaches include: 
 - have a checkbox or radio-button that selects between look-up behavior and key-in behavior.  
 - have a down-arrow (carrot? chevron?) field squeezed between the value field and the Fix checkbox.  If the user clicks the chevron, it expands into the current selection table.  If the user clicks into the value field (to the left of the chevron), it is possible to enter an arbitrary value.  

In either case depending on an "Auto-Fix" Preferences setting, a change in value causes the variable to be forced into FIXed status.  If desired, the variable can be put back in FREE status by clearing the checkbox.  The value is tagged as "Non-std" if appropriate.  The reasonably detailed explanation of the implications should dynamically change to correspond to FIX / FREE status.

As noted in the paragraph above, an "Auto-Fix"  Preferences setting can control if a user change in value forces the variable into Fix status.

Consider a "Cancel" button or the "Esc" key should reset any changes made prior to close of the dialog box.  **_Considered and deferred._**

Consider changing the name of the dialog box from "Advanced Settings" to "{Compression | Extension | Torsion} Spring Settings" or "{Compression | Extension | Torsion} Spring View Value Inputs".  

Consider adding a Help button (and appropriate Help content) along the lines of what is done for Action : Seek and Action : Trade.  See issue #578 and related Help content additions of issue #575, specifically settingValues.md.

Consider using a new Preferences setting ("ExpertMode" ?) to control value input behavior.  The default could be the behavior described above.  ExpertMode on could retain the current in-cell input / editing capability.  Setting the Preferences ExpertMode on and Auto-Fix off would approximate the current value input behavior.  **_Considered and deferred._**

Consider making Milestone 4.2 changes such as System-wide input validation #131.  **_Considered and deferred._**

![IndepFree](https://user-images.githubusercontent.com/39974784/132963658-753139c5-de87-4c0c-b1dc-5030bdd87042.png)
![IndepFixed](https://user-images.githubusercontent.com/39974784/132963661-1534699f-f4a4-4835-8ea8-ccd12af4e74c.png)
![DepFixed](https://user-images.githubusercontent.com/39974784/132963670-b2dcf31e-f500-4ece-af7e-cfc24ac9c281.png)

**Comment by 1fifoto** [comment]
Possible change to calculator view to mark all dependent variable fields with a white background (denoting input). Reset non-input values to normal font color (gray). Mark all independent variables with right-caret in upper left corner. Still has problem - after input the icon disappears and can be restored by clicking on another input field.

![Screen Shot 2021-10-10 at 5 55 37 PM](https://user-images.githubusercontent.com/1581602/136715592-2e492a3b-9ea8-4963-8046-5e13f186778c.png)

**Comment by 1fifoto** [comment]
Merged into master, closing
