### ISSUE TITLE
Add Help text to value entry dialog

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#578]
This issue provides a milestone 4.0.7 branch to experiment with the Help text that is part of the proposal of #577 in Milestone 4.1.  Perhaps it will allow earlier release of that part of the proposal.

**Comment by 1fifoto** [comment]
I messed around with it and came up with this. I don't know if this is any better.

![Screen Shot 2021-09-13 at 4 04 38 PM](https://user-images.githubusercontent.com/1581602/133156345-a3ad59fe-4867-47f1-908a-0f570a38843d.png)

                        <Table size="sm" style={{backgroundColor: '#eee'}} className="mb-0">
                            <tbody>
                                <tr className="table-light">
                                    <td>
                                        <em>
                                            Use the checkbox to control the value's <b>Fix</b> / <b>Free</b> status.
                                            <ul className="pt-1">
                                                <li><b>Fix</b>: Check to prevent <img src="designtypes/Spring/SearchButton.png"/> from changing the value.</li>
                                                <li><b>Free</b>: Uncheck to allow <img src="designtypes/Spring/SearchButton.png"/> to change the value.</li>
                                            </ul>
                                        </em>
                                    </td>
                                </tr>
                            </tbody>
                        </Table>

![SearchButton](https://user-images.githubusercontent.com/1581602/133156494-c053aebc-94b3-482b-9ee2-66157f894be6.png)

**Comment by grumpyinca** [comment]
This seems to be "over-the-top" word-smithing but do you find either of these preferable ?

![CandidateValueSettingDialog2](https://user-images.githubusercontent.com/39974784/133520119-02279e91-b256-4da6-8932-f82c2559420c.PNG)
![CandidateValueSettingDialog3](https://user-images.githubusercontent.com/39974784/133520069-b4fea0c0-72ec-4dc3-99fc-94c0ba528adc.PNG)

**Comment by grumpyinca** [comment]
I see that the Search Button image (.png file) is located in public/designtypes/Spring.  Considering that the button is located in the ResultTable it is not design type specific.  I will be happy to move the button image file further up in the directory tree and make associated path changes if you think that is the right thing to do.

**Comment by 1fifoto** [comment]
My question to you is: can you achieve a feasible design using FIX? If so, then you should also add it to the FREE statement. That is why I deleted "achieve a feasible design" phrase.

**Comment by grumpyinca** [comment]
Changes coming out of Sep 19 conversation are now implemented.  See also branch #575. Marking as "coded".

**Comment by 1fifoto** [comment]
merged into master, closing
