### ISSUE TITLE
View:Calculator disabled after click file name at top right

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#579]
Steps to recreate:

Launch ODOP or reload / refresh until reaching default design type (compression), design name (Startup) and view (Advanced).

Invoke menu View : Calculator

Click on file name (Startup) in upper right of page.

Observe unexpected switch to Advanced View.  **This is first part of bug.**

Invoke menu View : Calculator in attempt to switch back.

Observe no response !  **This is second part of bug.**

**Comment by 1fifoto** [comment]
Merged into master, closing
