### ISSUE TITLE
ResultTable message improvements

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#581]
There are near-term opportunities to improve messages visible to the user prior to implementing the Alerts facility described in issue #569.

It is already possible to define a default message in initalState.js.  Changes to initialState require associated migrate code. A possible default message would be:   
"Use the File : Open menu item to select a different design type (Compression, Extension, Torsion)  or units (US, metric)."

It is already possible to control ResultTable messages from an Execute script.  For example:
```
actions: [
        changeResultTerminationCondition('blah blah blah'),
      ]
```
Specifically, a query parameter script could replace the default message referenced above with something more appropriate. 

Note that many Execute script commands will reset the ResultTable message.  Thus, the changeResultTerminationCondition command noted above should be last in an actions: [] block.

New reducers.js code will be required to append to a previous message.  Use this branch to create the new code.

**Comment by 1fifoto** [comment]
Merged into master, clsoing
