### ISSUE TITLE
Display "non-std" entry in mid-table

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#585]
As of ODOP version 4.0.7 and including the changes in issue #477, a current "non-std" value is displayed at the beginning of the standard size table drop-down.  While not a high priority, it would be nice to have the "non-std" value displayed at the appropriate point in the drop-down table.

**Comment by 1fifoto** [comment]
Added labels, and sorted entries. Now non-std is in mid-table. 
<img width="515" alt="Screen Shot 2022-02-20 at 8 48 26 AM" src="https://user-images.githubusercontent.com/1581602/154848447-02ed5b84-4b56-41bc-8321-124281aebc04.png">

**Comment by 1fifoto** [comment]
Merged into master, closing
