### ISSUE TITLE
Changes in initialState: remove ioclass; sdlimit mods to support #452

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#589]
**sclden.js** is all about normalizing contributions to the objective function. It is active during system initialization and when constraints are changed. It is not active during search and thus there is no great concern about making its operation mathematically continuous or smooth.

The revisions to sclden.js in branch #452 (Investigate alternatives to behavior of smallnum in sclden.js; now closed) make appropriate scaling more dependent on the value of sdlimit that is established in initialState and the startup files and used in sclden.js. This is particularly true where an active constraint has a constraint level value of 0.0.  While not absolutely necessary, sdlimit should be non-zero and have a default value near the smallest reasonable value for the variable in its associated units system. There are special cases where sdlimit should be larger, for example, extension spring Initial_Stress.

**This issue provides a branch to handle the necessary updates to sdlimit in initialState for all design types.**  

Note that all startup files will need to be regenerated.

Additional thought needs to be put into the need to migrate older designs.  It is possible that it will not be possible to guarantee that designs saved in an older release with a "Feasible" objective function value remain as Feasible when opened in a newer release.    

**Remove ioclass property**

The ioclass property (independent, dependent & calculation inputs) is a vestigial remnant of the PL/I code.  ioclass should be removed from all initialState files.

**Comment by grumpyinca** [comment]
Note:  Be sure to include all design types including PCyl and Solid in these changes.  It may be necessary to change the automated test expected values.

As this issue will be making significant changes to each initialState, consider slipping in changes to Cycle_Life tooltips.

**Comment by 1fifoto** [comment]
Merged into master, closing
