### ISSUE TITLE
Model validity determination & response

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#590]
Per Oct 16, 2021 discussion, it is desirable to implement features that determine the physical & mathematical validity of various points in the design space and if invalid points are encountered, respond in an appropriate way.

In different words: determine "Model out of limits".  These boundaries and this validation would apply to Independent Variables, Dependent Variables and Calculation Inputs.

One possible implementation would be to incorporate a parallel to cmin and cmax.  A possible name is validmin and validmax.

Possible responses to a Model-out-of-limits condition include: 

- pass condition information back to Patsh where it can trigger a pattern break or a complete shutdown of the search 
- provide message and disallow closing a value entry dialog box where a Model-out-of-limits condition might be created
- provide a message (or Alert) if an Action menu function creates a Model-out-of-limits condition

**Comment by grumpyinca** [comment]
Don't forget to include **Extend ODOPPrecision to constraint values** #582.  That issue was closed in favor of doing the work in this issue.

**Comment by grumpyinca** [comment]
Per discussion earlier today ... In the Value Input modal dialog box of Calculator View, disable the close button if any input is invalid.

**Comment by grumpyinca** [comment]
Per discussion earlier today, the following entry has been transferred from a testing comment in issue #595.

Reload to Compression spring
Place a minus sign in front of the value for Wire_Dia.
Observe full screen message:
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops. 

Per discussion earlier today, the following entry has been transferred from a testing comment in issue #595.

Place a minus sign in front of the value for a different IV, for example, OD_Free.
Observe that there is impact on the objective function (good!), however, there is no alert about being "invalid".
I suspect that the lack of an "invalid" alert is because the valid range information is not available until branch #590 is incorporated.

**Comment by grumpyinca** [comment]
In the current (post 595 merge) development master, the "Maximum update depth exceeded" error described above will happen when supplying a Wire_Dia "Enter non-std value" that begins with a decimal point and zero.  It will also happen if the input is "decimal point {non-zero} {backspace}".

**Comment by 1fifoto** [comment]
Fixed "Maximum update depth exceeded" in branch #595, which is the first entry in [Two Comments Above](https://github.com/thegrumpys/odop/issues/590#issuecomment-1019686789) 

Fixed "Maximum update depth exceeded" in branch #595, which is in [The Comment Above](https://github.com/thegrumpys/odop/issues/590#issuecomment-1037761161)

Still open problem is the second entry in [Two Comments Above](https://github.com/thegrumpys/odop/issues/590#issuecomment-1019686789)

**Comment by 1fifoto** [comment]
Merged into master, closing
