### ISSUE TITLE
Add ODOPPrecision into Trade Arbitrary & Step size

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#594]
Bring the pattern used in Advanced & Calculator views (display full precision when an input gains focus and display ODOPPrecision onBlur) to Trade Arbitrary & Step size.

**Comment by 1fifoto** [comment]
Waiting for #595

**Comment by 1fifoto** [comment]
But using FormControlTyepNumber component (via #595) this issue has been completed. Closing

Arbitrary (without focus)
<img width="511" alt="Screen Shot 2022-02-20 at 7 50 34 AM" src="https://user-images.githubusercontent.com/1581602/154845890-b0cd56ae-e4d8-4e72-9bb3-4d576cce1012.png">

Arbitrary (with focus)
<img width="512" alt="Screen Shot 2022-02-20 at 7 50 43 AM" src="https://user-images.githubusercontent.com/1581602/154845935-10265575-df68-4683-b729-1ed3c9e395ed.png">

Step size (without focus)
<img width="512" alt="Screen Shot 2022-02-20 at 7 49 33 AM" src="https://user-images.githubusercontent.com/1581602/154845959-b8e65d66-529b-41fc-b4b0-3b8baf890e5f.png">

Step size (with focus)
<img width="508" alt="Screen Shot 2022-02-20 at 7 49 43 AM" src="https://user-images.githubusercontent.com/1581602/154845975-7b6a5043-569f-4a63-827e-67a24cd08cbd.png">
