### ISSUE TITLE
Improve tooltips related to point 1 & 2

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#608]
Review all tooltips defined in initialState and Calculator View related to operating point 1 and 2.  This includes the individual variables for Force / Moment, Deflection, Length, Stress and Factor of Safety as well as the Calculator View row headings.  Provide enhanced wording that makes it **over-the-top clear** that point 1 is minimum operating load and point 2 is maximum operating load.

**Comment by 1fifoto** [comment]
“Min load” and “max load” are great titles

**Comment by grumpyinca** [comment]
Merged to master, pushed to remote.  Closing.
