### ISSUE TITLE
Harp version update

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#620]
[Harp](https://github.com/sintaxi/harp) is used in the ODOP development process.  It is not contained within the final ODOP product.

At the time of this writing there is a Dependabot alert: "**Bump harp from 0.40.2 to 0.40.3**".  Earlier this year, an attempt to update the version of Harp was unsuccessful and had to be rolled back.  This issue will serve as a reminder to complete that work and also provide a branch for any required changes to be developed.

**Comment by 1fifoto** [comment]
Merged into master, closing
