### ISSUE TITLE
Repair design library problems created by unwanted v4.1 migrate in v4.2 Migrate

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#625]
A v4.1 development error caused compression spring design library entries Startup_Metric and HotWoundMetric to be migrated when they should not have been.  User designs saved after the unwanted migration have the label "Contact person" repeated multiple times beyond the end of the set of valid labels.  Discussion and review of the situation indicates that while this is unlikely to cause any short-term operational problems, it is theoretically possible that it would interfere with future migrations.  

This issue is being created as a reminder to ensure that V4.2 migrate cleans up (gets rid of) the multiple unwanted label entries having a value of "Contact person".

**Comment by 1fifoto** [comment]
Assumptions: I assume it does not affect Piston-Cylinder and Solid. I assume this affects Spring/Compression, Spring/Extension and Spring/Torsion. I assume that from the second "Contact person" label to the end of the array should be deleted.

I have copied a faulty Spring/Compression model from the production database as a Migrate Test sample. I have written the migrate code and it appears to work based upon the assumptions above, that is, delete from the second "Contact person" label to the end of the array.

**Comment by 1fifoto** [comment]
Merged into master, closing
