### ISSUE TITLE
Improve UI of Fix & Free checkboxes

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#632]
Conversation today touched on adding a tool-tip to the Fix / Free checkboxes.

As a hopefully less distracting alternative, I propose to adjust the column headers to look something like this:
![FixFreeProposal2](https://user-images.githubusercontent.com/39974784/154824039-fdb42a3c-8aac-4ce7-9078-a9dbf50ae5bc.png)

The layout would be common to both Advanced and Calculator Views.

**Comment by 1fifoto** [comment]
See #631
