### ISSUE TITLE
Replace violation value of satisfied constraint w/ icon+tooltip

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#635]
In ODOP v4.1 and earlier, a numeric violation value is displayed for all variables with enabled constraints.  The value is suppressed if the constraint is disabled and red if enabled and violated (positive).  When the constraint level is very small or zero, a variable might display a very large negative value for its violation (makes for a wide field).

This issue proposes retaining the display of numeric values for enabled constraints that have a positive violation value but replacing the violation value of satisfied constraints with an icon plus tooltip.  The icon could be a green (or dark gray) smiley face.  The tooltip should show the current value of the (negative) satisfied constraint violation.  The tooltip may also provide wording to indicate that the negative value is a (weighted) indication of constraint satisfaction.

While this change should free up some field width, the primary motivation is to de-clutter the user interface without significantly reducing the at-a-glance information conveyed to the user.

**Comment by 1fifoto** [comment]
Let's talk about this. I'm of mixed opinion about this one. The column title is "Violation" so is a green icon mean its a violation. Note: I did change to use toODODPrecision which improves some of the clutter. Also I changed the violation value (vmin/vmax) to be color the same as the constraint value (cmin/cmax).

**Comment by 1fifoto** [comment]
As an intermediate step to the future, we are not adding an icon or tooltip, but leaving the ODOP Precision and color change. We have talked about a "show_satisfaction" or maybe a "show_violations" with a new value that shows only violation but no satisfactions.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
While this is a rather minor, purely cosmetic issue, I will point it out for the sake of consistency.

The satisfied side of a Dependent Variable Fix should not appear when show_violations is set to 1.  See screen capture snippet below.
![image](https://user-images.githubusercontent.com/39974784/155919586-09580a75-fffb-45c7-9c1c-3d861a0550b7.png)

**Comment by 1fifoto** [comment]
Fixed "The satisfied side of a Dependent Variable Fix should not appear when show_violations is set to 1. "

<img width="1147" alt="Screen Shot 2022-02-28 at 4 10 03 PM" src="https://user-images.githubusercontent.com/1581602/156066878-36ba4254-8fc3-45ec-807d-c7ffe5ddc039.png">

Merged into master, closing
