### ISSUE TITLE
Move to latest React-Bootstrap

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#637]
Move to the latest release of React-Bootstrap.

This syntax needs to be confirmed: 
`npm install react-bootstrap@next bootstrap@5.1.3` 

Consider making this move as part of installing new development environments on new hardware (or not!).

This should also move to Bootstrap 5.x

**Comment by 1fifoto** [comment]
In branch 441 react-bootstrap was updated to version 5.3.3, therefore this issue has now been accomplished, closing.
