### ISSUE TITLE
Make action of AutoFix more visible

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#639]
As introduced in ODOP v4.1, the AutoFix feature can take users by surprise.  Specifically, the user is focused on entering a numeric value and does not notice that the action of entering a value has also put that variable in Fixed status.  Much later, the user does not get the solution behavior that was expected.  Troubleshooting then belatedly discovers that the variable was in Fixed status. 

The objective here is to briefly highlight the action of AutoFix without introducing the need for any additional keystrokes or clicks.

Possibilities include: 
- a very brief animation of the Fix/Free checkbox  
- a brief appearance / disappearance of the word "AutoFix" overlayed onto the value field or associated constraint violation fields.

It is possible that the AutoFix action could place the text "AutoFix" in the constraint violation fields and the next user entry could remove that text.

There are multiple websites and YouTube videos describing bootstrap animations and React-Bootstrap transitions.  For example: 
https://react-bootstrap.github.io/utilities/transitions/
https://mdbootstrap.com/docs/standard/content-styles/animations/

**Comment by 1fifoto** [comment]
Created branch 639. Added termination condition message to be "The value of <Variable> has been automatically fixed." Merged into Master, closing. MM to create new issue with current description.

**Comment by grumpyinca** [comment]
**Testing results:**

1. In both Advanced & Calculator Views, the first digit of a change in the value of an Independent Variable causes the termination condition message: "The value of {IV} has been automatically fixed.".  This is as expected and desired.  However, entering successive digits to that value clears the message.  This is not expected or desirable.

2. Any change, for example, a change in Fixed status on any variable (IV or DV) should (but does not) clear the termination condition message associated with a previously AutoFixed IV.  This is particularly troubling when the FIX on the variable that the message refers to is cleared. Note that unrelated enabling or disabling of constraints or changing of constraint values should also clear the message.  Is it possible that there is a central place to do this clearing ?

3. For consistency, Select Size should produce a message "The value of {IV} has been automatically fixed."

**Comment by 1fifoto** [comment]
Fixed, merged into master, closing
