### ISSUE TITLE
Possibilities to speed up Patsh operation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#643]
Today's conversation touched on opportunities to significantly improve the performance of most operations involving Pattern Search.

Specifically, because only the subset of variables that are subject to constraints (and during Seek, the variable selected as the merit function) actually contribute to the objective value that Patsh is using, it is necessary to calculate the values of dependent variables only if they influence the values of dependent variables that have enabled constraints, fixes or are Seek targets.  In spring design, there are a few dependent variables, notably Energy, Weight and Cycle_Life that are relatively expensive to compute and will frequently not be utilized during Pattern Search operation.

While it would be possible to selectively control execution in eqnset with conditionals (If or Case statements), that might incur enough additional overhead as to nullify the gains.  

Another possibility might be to hand code a small number of eqnset alternatives.  The appropriate alternative might be dynamically loaded in a mechanism similar to loading the eqnset of different design types.

Finally, the most intriguing option is conditional compilation.  This approach will likely take a fair amount of implementation and testing effort.  The cascading interdependence of the equations could introduce significant complexity in such an approach.

**Comment by grumpyinca** [comment]
Other alternatives coming to mind ...

A "compute intensive task" might be a complete Search or Seek; or might be only the part from Patsh on down.  In either case, it is likely that init and eqnset would be duplicated between the current system and something else (see below) handling the compute intensive task.  Considering the interaction currently required by Trade, it is likely that defining the "compute intensive task" to be only the part from Patsh on down would be more general.

A compute intensive task might be off-loaded to the server part of ODOP.  This might facilitate the current spinner challenges.  

An off-loaded task running on the server part of ODOP might be implemented in a language that facilitates multi-threading.  Presumably, this would involve significant re-coding of Patsh to take advantage of concurrent execution.

**Comment by 1fifoto** [comment]
Consider using a template engine to generate the code: See https://github.com/olado/doT

'doT Created in search of the fastest and concise JavaScript templating function with emphasis on performance under V8 and nodejs. It shows great performance for both nodejs and browsers. doT.js is fast, small and has no dependencies.'

**Comment by grumpyinca** [comment]
**Testing results:**

Note: As this entry is being written, there is a mis-match between the comments above and the code being implemented.  We will deal with that shortly.  This entry applies to the current state of code changes that reduce (eliminate?) writes to the redux model during operation of Pattern Search (Patsh.js).

Testing indicates that Seek is not working.  I am guessing that this failure is not related to FDCL or the recently introduced pxPropagate.  By setting File : Preferences ioopt = 6 and observing console output, I get the idea that the merit function is not making a contribution to the objective value.

To replicate the problem:
 1. Reload the browser.  Stick with default compression spring, startup (US units) and Advanced View
 2. Click "Seek (optimize)"
 3. Click "Seek Min Weight"
 4. Observe that there is no change to any of the independent variables.  Observe that this is very different that the result of the same sequence on either the production or staging systems.

**Comment by 1fifoto** [comment]
Merged into master, closing
