### ISSUE TITLE
Make restore from AutoSave optional

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#644]
In the scenario that a user gets design inputs seriously away from realistic values, they may try to recover by restarting ... all the way back to SpringDesignSoftware.org.  Unfortunately, the "auto-restore" aspect of AutoSave operation will just re-impose the values that they are trying to get away from.  It is even possible that a user returning to SpringDesignSoftware.org in order to switch to a new design type will get auto-restored back to the design type that they were previously working with.

I see two approaches to improving the situation:

 - Change the wording of the modal from "_Design restored from AutoSave data after interruption. See Help AutoSave for details. Use File Save, File SaveAs or File Export to save the design permanently._" to something like "_Design restored from AutoSave data after interruption. If AutoSave data is not desired, select the ODOP logo in the upper left to reestablish the default design type and design.  See Help AutoSave for details.  Use File Save, File SaveAs or File Export to save the design permanently._". 

 - Make the restore from AutoSave optional.  The modal could say words to the effect of "_AutoSave data is available_" and have two buttons, for example labeled as "Continue with AutoSave Data" and "Continue with default design".  Alternatively, there could be similarly labeled radio buttons and a "Continue" button in the modal footer.  The meaning of "default design" would be determined by the presence of query parameters.  If no query parameters, the default design type (compression) and design (Startup {US units}) should be applied.

Note that the words "See Help AutoSave for details." could be replaced with a context Help button in the footer.  The words "Use File Save, File SaveAs or File Export to save the design permanently." could be moved into the context Help section.

**Comment by 1fifoto** [comment]
Merged into master, closing
