### ISSUE TITLE
Remove Most of Old Root Docs Directory and Images Files

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#653]
1. Remove /docs BUT do not remove messageOfTheDay.md. 

1. Also remove public/designtypes/[Piston-Cylinder|Solid|Spring/Compression|Spring/Extension|Spring/Torsion]/*.[png|gif] files. Leave favicon.ico files.

1. In client/docs/procedures/release.md edit the entry/starting paragraph: 
`"Remember that if merged to master and pushed, changes to docs will be immediately published on GitHub Pages. Until all doc references are fully switched over to SpringDesignSoftware.org, documentation references to new features should not be merged to master until immediately before the version containing those features is published to Heroku production. This will delay closing the corresponding issue covering those documentation changes. Once documentation references are fully switched over to SpringDesignSoftware.org, it will be possible to merge doc updates to master but delay their publication to SpringDesignSoftware.org."`

1. Also in client/docs/procedures/release.md scan for references to docs in github.io and springdesignsoftware.org and re-write them to use odop.herokuapp.com or equiv.  Do the same for remaining procedures and design articles.

1. Modify all doc links in springdesignsoftware.org to use https://odop.herokuapp.com.

1. FOR ALL DOCS, change odop.herokuapp.com to odop.springdesignsoftware.org/docs

**Comment by 1fifoto** [comment]
TBD: FOR ALL DOCS, change odop.herokuapp.com to odop.springdesignsoftware.org/docs

**Comment by 1fifoto** [comment]
This is waiting on #662

**Comment by grumpyinca** [comment]
Item5 in the description above was moved to #685 in the next release.  

Changes complete.  Pushed to master.  Closing.
