### ISSUE TITLE
Okta failure after NPM audit fix

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#654]
Per the release procedure, npm audit fix was run. Now, launching the ODOP app encounters: 
 ```
okta-sign-in.entry.js:61354 
 Uncaught TypeError: Super expression must either be null or a function at okta-sign-in.entry.js:61354:1 
```
This problem will need a detailed diagnosis and repair, possibly re-coding to a recent Okta release.

**Comment by 1fifoto** [comment]
Not reproducible in the current version, closing
