### ISSUE TITLE
Incremental improvements in usage logging 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#656]
1.  Make a log entry when an execute script (Exec, Demo, Tutor) exits.
2.  In Action : Search, abbreviate "ButtonSearch Before 0.00006003 After 0.0000" to "ButtonSearch 0.00006003 --> 0.0000". 
3.  Log the Recover from AutoSave action (Recover versus Cancel); replace existing "load AutoSave".
4.  Log the Fixed / Free status of a variable after changing its value (was AutoFix turned off?).

**Comment by 1fifoto** [comment]
Done, merged into master, closing
