### ISSUE TITLE
Apply npm audit fix --force (as appropriate)

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#657]
As noted in the release procedure, **npm audit fix** was applied as part of the v4.2 release process.  An issue with Okta resulted.  

**npm audit fix --force** needs to be researched and applied as appropriate.

**Comment by 1fifoto** [comment]
We have run 'npm audit fix --force' and have the issues down to the following:

    12 vulnerabilities (3 moderate, 9 high)

If we run 'npm audit fix --force' multiple times it doesn't seem to fix anything further. Indeed it seems to get worse and ping-pong between the above output and '165 vulnerabilities (1 low, 87 moderate, 74 high, 3 critical)' output. The 'client/package-lock.json' file has been updated. So we merged it into master, marking this as complete, and closing.
