### ISSUE TITLE
Make action of AutoFix even more visible.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#661]
This issue was used in the development of an Auto Fix checkbox at the right of the Alerts accordion.  That checkbox is viewed as an interim measure until a more comprehensive solution, including an improved File : Preferences feature (see #638, #100) and including AutoSearch, can be developed. 
<hr/>
The words below have been copied to #775. 

As introduced in ODOP v4.1, the AutoFix feature can take users by surprise. Specifically, the user is focused on entering a numeric value and does not notice that the action of entering a value has also put that variable in Fixed status. Much later, the user does not get the solution behavior that was expected. Troubleshooting then belatedly discovers that the variable was in Fixed status.

The objective here is to briefly highlight the action of AutoFix without introducing the need for any additional keystrokes or clicks.

Possibilities include:

a very brief animation of the Fix/Free checkbox
a brief appearance / disappearance of the word "AutoFix" overlayed onto the value field or associated constraint violation fields.
It is possible that the AutoFix action could place the text "AutoFix" in the constraint violation fields and the next user entry could remove that text.

There are multiple websites and YouTube videos describing bootstrap animations and React-Bootstrap transitions. For example:
https://react-bootstrap.github.io/utilities/transitions/
https://mdbootstrap.com/docs/standard/content-styles/animations/

A first step in the direction of resolving this issue was taken in branch #639 (now closed).

**Comment by grumpyinca** [comment]
Various conversations have touched on how it might be possible to make it obvious how the user can over-ride the default AutoFix behavior.  Ideas include: 
 -  a radio button in the currently unused area to the right of the Alerts buttons. 
 -  A settings "hamburger" button that invokes an enhanced **File : Preferences** menu item.  This could be placed either in the menu bar or in area to the right of the Alerts buttons

See Also:  #638, #469.

**Comment by 1fifoto** [comment]
Coded

**Comment by grumpyinca** [comment]
This issue was used in the development of an Auto Fix checkbox at the right of the Alerts accordion.  That checkbox is viewed as an interim measure until a more comprehensive solution, including an improved File : Preferences feature (see #638, #100) and including AutoSearch, can be developed.  As this issue will soon be closed, the comments above are being copied to a new issue (#xxx) that can remain open.

**Comment by 1fifoto** [comment]
Merged into master, closing
