### ISSUE TITLE
Full text search of docs

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#662]
A full text search capability on the ODOP documentation (on-line Help) is desired.

There are various implementation possibilities producing various capabilities.  For example: [15 Open-source Full-Text Search Engine Solutions for developers](https://medevel.com/os-fulltext-search-solutions/)

As of this writing, a Google search with a **site:**  parameter seems to offer a limited capability for minimum implementation difficulty.

**Example** ... Pass this search string (search criteria) as input to Google Search: 
`site:SpringDesignSoftware.org/odop/docs  Prop_Calc_Method `

If the search string is unique to ODOP, the results can be focused and quite helpful.  If the search string is generic, the result set is both less useful and includes ads.

If it was possible to automatically apply a browser "Find on page" to a page selected from the result set by the user, the leverage (utility) of this function would be greatly increased. 

It is currently visualized that this feature would be implemented as an entry on the Help menu.  Possible titles might include "Full Text ...", "Full Text Search ..." or "Full Text Search of Docs ...".  See the next comment for more on this point.

One possible interim approach is to have the **Help : Full Text Search** entry simply go to a Help entry that describes the process of using the site: syntax in Google search followed by a browser "Find on Page".

Note:
It appears that only Google uses the "site:" syntax.  No luck with Bing, Yahoo, Baidu & DuckDuckGo.

**Comment by grumpyinca** [comment]
From today's conversation on the subject:

[Text Fragments](https://web.dev/text-fragments/?msclkid=91dde195b2ed11eca1b5767db85af0fe)

[Google's Programmable Search Engine](https://support.google.com/programmable-search/answer/4513751?hl=en&ref_topic=4513742)

Rather than positioning a "Full Text Search of Docs ..." entry on the Help menu, it would be better aligned with industry practice to have a text entry box on the menu line (to the right of Help and to the left of the design type icon).  There should be a magnifying glass icon to the right of the text entry box.  The lookup action should be initiated with a carriage return or a click on the magnifying glass icon.  The results can be presented in a new browser tab.  The entry box could have a dimmed text saying something like "On-line Help lookup".  See client/src/components/MainPage.js.

**Comment by 1fifoto** [comment]
Added a text input field and magnifying glass icon button. The input responds to 'enter' key.
<img width="999" alt="Screen Shot 2022-04-03 at 8 34 07 AM" src="https://user-images.githubusercontent.com/1581602/161430687-79b3d3b5-2a8e-4baa-ae7f-55046812737d.png">

Entered 'default design' and separate windows appears showing the following entries:
<img width="997" alt="Screen Shot 2022-04-03 at 8 35 40 AM" src="https://user-images.githubusercontent.com/1581602/161430701-35e5d5d1-3120-4042-9081-3ce4bad0da39.png">

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
Reopening for two reasons.

 1. It appears that contrary to initial impressions, the CNAME odop.springdesignsoftware.org/docs has not actually been indexed by Google.  For example, try the current development master with a search spring like "stress" or "Prop_Calc_Method".  The search will fail.

2. More testing is needed with a default Search engine that is not Google and default browser that is not chrome based.

**Comment by 1fifoto** [comment]
Removed from production release. Disabled for production

**Comment by grumpyinca** [comment]
Opened issue #676 to provide a place to experiment with [Lunr](https://lunrjs.com/).

Note that Lunr is the first item on the list of 15 full-text indexing solutions noted in the original description of this issue.

**Comment by grumpyinca** [comment]
The attached spreadsheet provides a summary of indexing "hits".


[HelpLookupIndexing.ods](https://github.com/thegrumpys/odop/files/8549971/HelpLookupIndexing.ods)

**Comment by grumpyinca** [comment]
An indexing approach based on Lunr is looking like the superior alternative.  Closing in favor of #676.
