### ISSUE TITLE
Action : Seek modal fails to clear 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#665]
When using the Seek button, the Action : Seek modal appears, the user selects a pre-configured button, the Seek operation completes and the Seek modal disappears.  This is all as expected and as desired.

When using the Action Seek menu, the Action : Seek modal appears, the user selects a pre-configured button, the Seek operation completes and the Seek modal fails to disappear.  This is not as expected and not as desired. The work-around is to click Cancel or click outside the modal to make it disappear.

I observe that if using the Action Seek menu with the older drop-down selection of Seek direction, the modal clears as expected.

Separately, when using the Action : Search menu, the log usage entry is still of the pre v4.2 long form:
`{"tag":"event","action":"ActionSearch","note":{"event_label":"ActionSearch Before 0.8925 After 0.000"}} `
This might be a good opportunity to update to the v4.2 (slightly) abbreviated form:
`{"tag":"event","action":"ActionSearch","note":{"event_label":"ButtonSearch 0.0001354 --> 0.00002326"}} `

**Comment by 1fifoto** [comment]
Fixed, merged into master, closing
