### ISSUE TITLE
Improve specific usage log message

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#669]
The usage log message:
{"tag":"event","action":"Index","note":{"event_label":""}}
is created  when responding to AutoSave prompt or perhaps when clicking the ODOP icon to cause restart.  It is thought to be index.js line 44.  The null field is the result of no query parameters in the URL that invokes the ODOP app.  

This usage log entry would be easier to interpret if it contained some reference to query parameters.

**Comment by 1fifoto** [comment]
Added to event_label the prefix 'window.location.search='.
