### ISSUE TITLE
Demo script "back" then "next" does not get same values

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#670]
In theory, an execute script "back" operation followed by a "next" operation should return to the same state, even if a Search is involved.  There is at least one case, extension spring demo7 page 6 of 11, where that is not the case.

To replicate the problem:

 1. load the extension spring model
 2. Help : Demo, select demo7
 3. Click "Next" until page 6 of 11.  (observe / preserve the state)
 4. Click "Next".  Observe the search goes for 117 iterations (observe / preserve the state)
 5. Click "Back". (compare objective value & state to step 3)
 6. Click "Next".  Observe that the search goes for 36 iterations and that the result is very different than step 4.  **What?**
 
It is quite possible that this problem will occur in other, simpler, quicker to repeat cases.

**Comment by grumpyinca** [comment]
I have discovered that the 
`                freeSymbolValue('End_Extension'), `
line on page 6 of 11 of the demo7 script is not getting re-executed.  It does not get re-executed even if backing up all the way to page 5 or page 4.  Based on my rather limited analysis so far, this seems to be the crux of the problem.

**Comment by 1fifoto** [comment]
It appears that our current 'macro' support is NOT doing a deep copy so I added a JSON.stringify when saving the model and a JSON.parse when going back to the previous model.

Merged with master, closing
