### ISSUE TITLE
Msg set in WelcomeCalc script works only for Compression

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#671]
The WelcomeCalc.js scripts should be identical for all spring types.  There should be no dependence on units.

Line 59 of WelcomeCalc.js:
`                changeResultTerminationCondition('When finished reading all four of the Welcome pages above, use the gray "Exit" button in the upper right to close the light green panel.'), `
works as expected for compression springs and US units.  It fails for extension, torsion and all metric units.

Behavior is identical in both production and development systems.

A second set of eyes will be helpful to figure this out.

**Comment by 1fifoto** [comment]
Fast query parameters: ?view=Calculator&type=Spring%2FCompression&name=Startup
Slow query parameters: ?view=Calculator&type=Spring%2FCompression&name=Startup_Metric and all other types with or without Metric.

It has nothing to do with executing a welcome script, but the missing message display is another symptom.

Fast approach seems to use: In Routes.componentDidMount loadInitialState config.env.type= Spring/Compression config.env.units= US
Whereas slow approach seems to use: In Routes.componentDidMount getDesign config.url.type= Spring/Compression config.url.name= Startup_Metric

So it looks like fetching the file from the database and its I/O is possibly the culprit.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
Problem discovered during testing:

Steps to replicate:
 1. In development environment, load ODOP app or reload browser
 2. Action : Execute, select welcomeCalc, click Execute button
 3. Click "Next".
 4. Click "Back", Observe traceback as pasted below.

```
ExecutePanel.onBack
C:/Users/Mike/git/odop/client/src/components/ExecutePanel.js:130
  127 | if (prev < 0) prev = 0; // Stop going backwards if it is on the first step
  128 | // Put steps[prev].state into current store state - that is, time travel back
  129 | const { store } = this.context;
> 130 | store.dispatch(load(JSON.parse(this.state.steps[prev].state)));
      | ^  131 | this.setState({
  132 |     step: prev,
  133 |     title: this.state.steps[prev].title
```

In console log:
```
VM96:1         
       Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at ExecutePanel.onBack (ExecutePanel.js:130:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238:1)
    at invokeGuardedCallback (react-dom.development.js:291:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:391:1)
```

etc.

**Comment by 1fifoto** [comment]
Merged into master, closing
