### ISSUE TITLE
Full-text Help doc indexing with Lunr

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#676]
This issue provides a branch to experiment with Full-text Help doc indexing with [Lunr](https://lunrjs.com/). 

See #662 for prior efforts using the Google **Site:** parameter.

**Comment by 1fifoto** [comment]
Found during my investigation and thought they were interesting/insightful

* [Add Search to Your Static Site with Lunr.js (Hugo, Vanilla JS)](https://aaronluna.dev/blog/add-search-to-static-site-lunrjs-hugo-vanillajs/). See CodePen sample (next item below)
* [Lunr.js Static Site Search Example](https://codepen.io/a-luna/pen/GRooENM)
* [Lunr-Index-and-Search-for-Static-Sites](https://github.com/BLE-LTER/Lunr-Index-and-Search-for-Static-Sites) - contains script to process the HTML files.

Sounds like pre-building the Lunr index would be a good idea: [PRE-BUILDING INDEXES](https://lunrjs.com/guides/index_prebuilding.html). 

I'm considering the Lunr search to be added to our server as an API call. At server start up it loads the pre-built index, Then when the client gets a search docs request is fires a Search API GET to the server. The server queries the Lunr index and returns the results. The client displays the results in a modal window.

**Comment by 1fifoto** [comment]
Still to be done:

1. Fix error with 'extension spring' causing a "SyntaxError: Invalid regular expression: /(+extension|+spring)/: Nothing to repeat"
1. Fix no blank between sentences such as "value.The" as in "Double-click (double-tap a touch screen) to replace the entire value.The AutoFix feature, introduced in ODOP version 4.1, automatically applies Fixed status to variables whose values are changed by user input" for search term "status".

**Comment by 1fifoto** [comment]
From cheerio documentation on [filtering](https://zetcode.com/javascript/cheerio/#:~:text=on%20the%20elements.-,filtering,-.js): 
```
const cheerio = require('cheerio');
const request = require('request');

request({
    method: 'GET',
    url: 'http://localhost:8000'
}, (err, res, body) => {

    if (err) return console.error(err);

    let $ = cheerio.load(body);

    let allEls = $('*');

    let filteredEls = allEls.filter(function (i, el) {
        // this === el
        return $(this).children().length > 3;
    });

    let items = filteredEls.get();

    items.forEach(e => {
        console.log(e.name);
    });

});
```

**Comment by 1fifoto** [comment]
Added this.metadataWhitelist = ['position'] to build_index.js when creating the lunr index. See: [Search Results](https://lunrjs.com/guides/core_concepts.html#search-results)

Then on the [Moonwalkers site](https://github.com/olivernn/moonwalkers) there is an example of processing the metadata.

```
  results.forEach(function (result) {
    var doc = documents[result.ref],
        li = buildSearchResult(doc)

    Object.keys(result.matchData.metadata).forEach(function (term) {
      Object.keys(result.matchData.metadata[term]).forEach(function (fieldName) {
        var field = li.querySelector('[data-field=' + fieldName + ']'),
            positions = result.matchData.metadata[term][fieldName].position

        wrapper(field, positions)
      })
    })

    ol.appendChild(li)
  })
```

**Comment by grumpyinca** [comment]
It would be nice if it were possible to provide a negative boost to all documents in the design and procedures sub-directories.  Considering that may be difficult, one alternative may be to move those directories to a place where they do not get indexed.

**Comment by 1fifoto** [comment]
Merged into master, closing
