### ISSUE TITLE
Optimize Help docs for indexing w/ Lunr

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#677]
Titles (top level headings) with multiple "#" have already been converted to single "# ".

Section headers (second level headings) should be converted from bold to "## ".

"On this page" entries should be unstructured list (start with "-") and have no more than one trailing blank.

Index files should get brief introductory text.

___

Create Help topic that describes how to use the "Help lookup" feature.  Syntax for forming a multi-word search string that is AND, not OR.  Syntax to restrict search to doc titles only.  Syntax to get a "fuzzy" search.  This topic will be the target of the context help button at the bottom of the modal that presents full-text search results.

**Comment by 1fifoto** [comment]
Merged into master, clsoing
