### ISSUE TITLE
Seek w/fixed IV can operate on wrong variable

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#678]
I have been able to demonstrate this problem in development, staging and production systems.  

**Steps to reproduce:**

 1. Load or reload ODOP: Spring app.  Use default design type & design, Advanced View.
 2. File : Preferences, ioopt = 6
 3. open developer tools console log window.  Clear it.
 4. Fix OD_Free
 5. Change Force_2 MIN 40 (optional, only necessary if you are interested in a well-formed design problem)
 6. Seek min Wire_Dia (Since OD_Free is fixed Wire_Dia becomes default.  Just hit Seek button in lower right)
 7. Observe 0% improvement.  
 8. Observe in console that Seek actually attempted to operate on OD_Free (but that was Fixed so no progress).

**Comment by 1fifoto** [comment]
merged into master, clsoing
