### ISSUE TITLE
Seek can report dis-improvement as improvement

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#680]
From usage log 2022-04-27 19:20:18.  Seek Min Weight produced:
**Seek completed. Weight 0.001403 --> 0.01449 pounds; 933.0% improvement.**

If starting with newly imposed fixes or constraints creating a sufficiently large objective value and then using the Action : Seek menu, it is possible for the Seek to move in the opposite direction as desired yet have the result reported as an "improvement".  

Hopefully, there is a way to report this situation as something other than "improvement".

Note 1:
The warning produced by Seek.js lines 29-34 is not visible by the user.    In this specific case, the user might have been better off with a visible warning.

Note 2:
Perhaps the right way to deal with the situation is to disable the Seek menu when OBJ > OBJMIN.  Currently, Trade has an internal test and will pass back a termination message of "OBJ < OBJMIN - USE OF TRADE IS NOT APPROPRIATE".  Going forward, Seek and Trade should handle the situation in symmetric / parallel ways.

Note 3:
A minimal set of steps to reproduce this problem is not currently available.  If the root cause is not apparent by inspecting the code, it should be possible to invent such a minimal test case.

**Comment by 1fifoto** [comment]
A number of warnings were left out when the ResultsTable's Seek is requested. These were in the Menu's Seek request. I have now put them in both Menu's Seek and ResultsTable's Seek. I don't know if this will help. This included

* No free independent variables
* One (or more) Independent Variable(s) is (are) Not a Number
* Objective Value is Not a Number. Check constraint values
* <element.name> constraints are inconsistent

Additional warnings can be added, such as the one you describe in your Notes.

**Comment by 1fifoto** [comment]
Checks were added in #678 to check whether ActionSearch, ActionSeek, and ActionTrade should or should not be disabled when the objective_value is > objmin.

**Comment by 1fifoto** [comment]
Merged to master as part of #678, closing
