### ISSUE TITLE
Improvements to full-text Help doc indexing w/ Lunr

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#684]
This issue lists possible improvements to the full-text Help document indexing that was created as part of #676.

 1. DONE: Add an additional "Close" button at the top of the "Help lookup for terms "xxx" modal.
 2. DONE: Add a context Help button (or two).
 3. Limit the number of hits displayed on the "Help lookup for terms "xxx" modal to (10?) entries. Page forward / back ?
 4. DONE: Document how to apply multi-word terms to get intuitive results ("and", not "or" between the words)
 5. DONE: Change blurb sentence algorithm to always show the found words and highlight around them
 6. DONE: Improve build_index/blurb sentence algorithm. See below comment.

**Comment by 1fifoto** [comment]
I have created docLookup.md. In it I referred to Lunr [Searching](https://lunrjs.com/guides/searching.html) Guide, but that page is written in "programmer-eeze" explaining Lunr search parameters. I need Mike to write a detailed description of the search syntax from a user's point-of-view (using that article). Alternatively see [Refine web searches](https://support.google.com/websearch/answer/2466433?hl=en) for how Google explains their search syntax to users.

**Comment by grumpyinca** [comment]
I have integrated content from docLookup.md into branch #677 helpLookup.md.  Also, I used the Lunr [Searching](https://lunrjs.com/guides/searching.html) Guide to create a short bullet list of control characters with examples there.  I propose that #677 helpLookup.md supersede docLookup.md.

**Comment by 1fifoto** [comment]
Change blurb sentence algorithm to always show the found words and highlight them with n words surrounds it. for example, a b c d e f g. If f is found them show 2 words around it. ... d e f g ...

Somehow mark the content with sentence boundaries by the build_index algorithm. Then in the blurb algorithm use these boundaries instead of using '\b\.\s reg ex. This should enhance blurb algorithm to not include lists of topics, etc.

**Comment by 1fifoto** [comment]
https://react-bootstrap.github.io/components/pagination/

**Comment by 1fifoto** [comment]
Merged into master, closing. Will split off Item 3 in description to a separate later issue: Filter amount by Page, Sentence, and Word.
