### ISSUE TITLE
Post validity-integration tweaks

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#703]
This issue is intended to provide a branch supporting a range of small-scale changes applied after the validity changes of branches 590 and 569.

Changes associated with Alerts.js, AlertsModal.js & Help/Alerts.md: 
 - introduce the message prefix "INVALID CONSTRAINT VALUE" 
 - provide Help URLs & associated content for constraint validity
 - tweak the tooltip wording  
 
Also include: 
 - increase default MAXIT 
 - corresponding changes to MAXIT in Br590TestScript & tweakPrefs script, etc.  
 - a couple selected design type specific alerts conditioned on OBJ > OBJMIN
 - reduce the default value of OBJMIN from 0.00005 to 0.00001.  
 - add a digit in the format of the objective value output in the feasibility status tooltip.
 - keep Help/alerts.md synchronized with changes design type specific alerts files.

Update new Patsh.js:
 - modified the new patsh to count iterations in a similar manner as that of the old patsh

**Comment by 1fifoto** [comment]
Also consider adding to patsh: s + tol * Math.abs(ssi) >= ssi

**Comment by grumpyinca** [comment]
### Validity and Alert handling before & after Search, Seek & Trade

**Before Search**

 - remove tests for:
     Objective Value less than OBJMIN.	(_tested before menu enable or button display_)
     One (or more) Independent Variable(s) is (are) Not a Number  (_input filtering blocks non-number_)
     Objective Value is Not a Number.  (_Necessary? input filtering blocks non-number_)

 - keep tests for:
     No free independent variables  (_Alert only warns; there is no other block_)
     constraints are inconsistent   (_Alert only warns; there is no other block_)


**After Search**

Add test for any variable or Calc Input invalid
If so, 
`displayMessage(errorMsg, 'danger', 'Errors', '/docs/Help/errors.html#searchErr')`
where errorMsg is something along the lines of:
"This design has one or more variables or Calculation Inputs with an invalid value.
See Alerts and Help (below) for details."


**Before Seek**

- remove tests for:
     One (or more) Independent Variable(s) is (are) Not a Number  (_input filtering blocks non-number_)
     Objective Value is Not a Number.  (_Necessary? input filtering blocks non-number_)

     Is validity test really necessary (moot) ?  
     Won't invalid create enough of an objective value to block the availability of Seek ?

 - keep tests for:
     No free independent variables  (_Alert only warns; there is no other block_)
     constraints are inconsistent   (_Alert only warns; there is no other block_)

 - add test for Calc Input validity ? (_Necessary? Will objective value block availability of Seek ?_)


**After Seek**

Test for any variable or Calc Input invalid
If so, 
`displayMessage(errorMsg, 'danger', 'Errors', '/docs/Help/errors.html#seekErr')`
where errorMsg is something along the lines of:
"This design has one or more variables or Calculation Inputs with an invalid value.
See Alerts and Help (below) for details."


**Before Trade**

Add same tests as before Search


**After Trade**

Add same test as after Search

**Comment by 1fifoto** [comment]
Merged into master.

**Comment by grumpyinca** [comment]
Issue #698 is now closed.  Ongoing initialState changes being handled as part of this issue.

**Comment by grumpyinca** [comment]
Added alerts for Cycle_Life for case when Prop_Calc_Method > 1 and also case where FS_2 < 1.0.

**Comment by grumpyinca** [comment]
Changes in the past several days: 
 - add See Also link to Cycle_LifeNA_FS_2
 - Add alert for Excess Force

These changes resulted in merge conflicts versus branch 707.  It appears that it is time to close this branch and move on to a greater number of new and short-lived issues based on the then current master.

Merged to master.  Pushed to remote.  Closing.
