### ISSUE TITLE
Failure to highlight constraint violation in initialState

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#708]
Potentially relevant factoid: The Piston-Cylinder demonstration problem (test case) is the only one where a constraint violation is present in the initialState.  

This issue occurs when using the current (v4.3) master branch and using the admin-only "Load Initial State" button.  This issue does not occur if opening the PCyl Startup design (migrate happens) or if using the admin-only "Load Initial State" button in the v4.2.2 staging system. 

**Steps to replicate the issue: **

1. Reload the ODOP app in the development environment.
2. File : Open Piston-Cylinder.
3. Click the admin-only "Load Initial State" button.
4. Observe that both Value and (non-zero!) Violation in the DV Min Constraint column for FORCE are black.  
**_This is the bug._**
5. Make any change to the model, for example, change the value of PRESSURE from 500 to 501.
6. Observe that both Value and Violation in the DV Min Constraint column for FORCE are now red. 
**_This is the expected starting behavior._**

While this may not technically be the classic "stale data" problem, I have a hunch that it is pretty close.

**Comment by 1fifoto** [comment]
Fixed, merged into master, closing.
