### ISSUE TITLE
Seek MAX Weight produces OBJ contradiction - Solid

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#709]
While the Rectangular Solid demonstration problem (test case) illustrates this issue, the behavior has not yet been observed in other testing.  However, it is not obvious why this issue would be design-type specific.

This issue occurs when using the current (v4.3) master branch and both loading via the admin-only "Load Initial State" button and loading via Startup (migration).  Results with the v4.2.2 staging system are different ... and based on inspection of the numbers, more correct. 

**Steps to replicate the issue: **

1. Reload the ODOP app in the development environment. 
2. File : Open Solid.
3. Click "Load Initial State" button
4. Click "Seek (optimize)" button
5. Click "Seek MAX Weight" button
6. Observe NOT FEASIBLE, OBJ=0.4885444, 244.1% improvement
_(results for v4.2.2 staging system: FEASIBLE, OBJ=0.000025,103.6% improvement)_
7. Click "Search (solve)" button
8. Observe **_contradictions_**: NOT FEASIBLE, "Search terminated when design reached feasibility (Objective value is less than OBJMIN)" and OBJ=0.3770102.

The huge difference with the v4.2.2 result is a concern.  It is not clear to me what is cause and what is effect.

**_Note:_** 
In an attempt to better understand the origin of this issue, I loaded branch 569 and observed the same behavior there.

**Comment by 1fifoto** [comment]
Fixed in #709
