### ISSUE TITLE
Compression - limit deflection and length at solid condition

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#712]
Since the beginning of the compression spring mathematical model, it has permitted sufficiently large values of Force_1 & Force_2 to drive the values of deflection (Deflect_1 & Deflect_2) and length (L_1 & L_2) below the limits realized by the solid condition.  In extreme cases, L_1 and L_2 can become large negative values.  This unrealistic situation was maintained so as to avoid a discontinuity in the objective function and also provide a guiding influence that takes the solution back in the direction of validity. 

This issue is being created to provide a branch in which to experiment with alternatives.  Specifically, I am curious about the possibility of creating one or two new (probably hidden) Dependent Variable(s) with names something like "Excess_Force(_n)".  These variables would be calculated as `Force_Solid - Force(_n)` and constrained to be greater than or equal to zero.  The same effect would likely be achieved with validMAX & validMAX.  This would hopefully provide the "restoring influence" to guide the solution back to validity even if other constraints were disabled.

**Comment by grumpyinca** [comment]
Work in progress.
Can't figure out why it blows up with: 
"`TypeError: Cannot read properties of undefined (reading '26')"`.

The changes in eqnset seem to work as intended.  The "restoring influence" seems to be necessary.

**Comment by grumpyinca** [comment]
As of this writing, this approach seems to be producing the desired results.  

There are a few loose ends:  
 - The Excess_Force variable gets an alert which brings a hidden variable to the user's attention.  Perhaps the alert code needs to be modified to not alert on hidden variables.  Perhaps Excess_Force should not be hidden.
 - There are a small number of < zero versus <= zero comparisons that need a bit more work.

I ran into a problem with an early attempt.  When the Excess_Force variable was added in to initialState immediately after Energy, I got a compile-time message referencing index 26 and mentioning a line of code that deals with the material file and its "mo" offsets.  I was unable to trace the source of the problem.  I finally resolved the problem by positioning Excess_Force absolute last in the Symbol Table.  Note that this position is after all the Calculation Inputs ... specifically, the material file. This is not ideal and should be cleaned up.

**Comment by 1fifoto** [comment]
I added migration to fix the 'index 26' problem.

**Comment by grumpyinca** [comment]
Changes made on July 27th:
- made Excess_Force visible
- updated metric initialState & migrate
- Flipped to Excess_Force = Force_2 - Force_Solid

Branch 703 has added an excess force alert.  Branch 707 has provided a supporting help entry.  Those are merged to master but so far, not into this branch.

Testing is on-going.

**Comment by 1fifoto** [comment]
See #714 which includes extensions to this issue.

**Comment by grumpyinca** [comment]
The last of the changes developed as part of this issue were removed in #730.
