### ISSUE TITLE
Alerts not up to date on load default design

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#715]
I have just observed this issue in the master branch.  As it seems to be recent and the symptoms are vaguely similar to #708, I am wondering if this issue was triggered by the fix to #708. 

**Steps to reproduce this issue:** 
 1. Using the current Master branch, Reload the app. 
 2. Close the migration dialog
 3. Observe that no alerts are active ("badge" not present, Alerts button disabled). **_This is the bug!_**
 4. Select (drop down) the Action menu.
 5. Observe that there are now two Alerts active.  This is the expected situation for step 3.

**Comment by 1fifoto** [comment]
Fixed in branch #709.
