### ISSUE TITLE
Review FS_1 when Force_1 = 0

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#719]
Need to re-examine the calculation of FS_1 when Force_1 (M_1) is zero for all spring types and all views.

**Comment by grumpyinca** [comment]
When Force_1 = 0, compression & extension springs show stale FS_1 value in Calculator View only.

When M_1 = 0, torsion spring shows FS_1 as zero in Calculator View, and all three reports.

**Comment by grumpyinca** [comment]
I repaired a coding problem in each of the spring types & pushed into this branch.  As of this writing, the stale FS_1 value in Calculator View is the only known remaining problem. 

Separately, there are a couple of cleanup items (for example, "infinite" versus "infinity") that I plan to deal with before closing this issue.

**Comment by 1fifoto** [comment]
Fixed display of fs_1 in Compression Calculator view by changing the
Value component to display 'Infinity' or '-Infinity' via toFixed
function call.

Make Calculator view of Static FS Free to be right-justified 'Infinity'

**Comment by grumpyinca** [comment]
Move "allowable stress for preset" line into comment block.
Remove comment re tensile values now superseded by alert.

**Comment by grumpyinca** [comment]
Merged to master.  Pushed to remote.  Closing.
