### ISSUE TITLE
Include propagated variable name in FDVL alert

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#723]
It would be "nice-to-have" the other (propagated) variable name appear in the alert when a FDVL (dynamic validity limit) is active.  Specifically, having line #1 in this screen capture look more like line #2: 
![image](https://user-images.githubusercontent.com/39974784/183525324-f828bc25-764e-425c-8545-64e47f29668a.png)

_From Slack entry:_ 
For contraint min and max we have
      "cminchoices": [ "Initial_Tension" ],
      "cminchoice": 0
And we'd need to make it generic, that is, cminchoices/cmaxchoices to propagatechoices with a Name and a MIN,  MAX, VALID_MIN or VALID_MAX parameter, etc.

While this issue is opened against v4.3, it is possible that it could be pushed back to a future release.

**Comment by 1fifoto** [comment]
Sample output after change
![Screen Shot 2022-08-13 at 8 10 33 PM](https://user-images.githubusercontent.com/1581602/184518412-30b9e5d6-e783-4e6a-8070-17a471d1e6db.png)

Merged into master, closing
