### ISSUE TITLE
Test results - regression of issue #708

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#725]
Testing on V4.3rc1 in staging indicates that the symptoms described in issue #708 have returned.

**Comment by grumpyinca** [comment]
I believe that the following sequence is not a problem. However, since constraint colors are involved, I will mention it.  Perhaps the mention will help focus the investigation into the subject issue.

Steps: 
1. Reset browser, load the app
2. File : open Compression initialState
3. Constrain Force_2 to be greater than 40 pounds
4. Fix L_Stroke at 1.75 inches
5. Search
6. Observe that the result is FEASIBLE. The Objective Value is greater than zero, in the green zone, as result of a small residual FIX violation on L_Stroke MAX.
7. Observe that the color of the L_Stroke MAX constraint level is black, not green.  There is no corresponding Alert panel entry for the Fix violation.  I believe that that **the color and Alert entry are being suppressed by the fact that the design is FEASIBLE** (obj < OBJMIN). 
8.

**Comment by 1fifoto** [comment]
Working as expected, not an issue.
