### ISSUE TITLE
FIXing var w/ default constraint triggers alert

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#728]
Fixing a variable configured with a default constraint will trigger a "Warn: Default constraint has been disabled." alert.

While not a blatant bug, this is not desirable.  The conditional that triggers the alert should be modified to not generate this alert in the case that a FIX is present.

**Comment by grumpyinca** [comment]
Perhaps it would be best to defer work on this issue until #726 is fixed.  When working in development with v4.3rc2, I am having difficulty reproducing this issue. 

Is the following line the correct / best syntax ?
`if (!(design.model.symbol_table[o.Coils_A].lmin & CONSTRAINED) && !(design.model.symbol_table[o.Coils_A].lmin & FIXED)) add_DCD_alert(design.model.symbol_table[o.Coils_A], '');`

**Comment by 1fifoto** [comment]
No longer a problem. Fixed in #726. Closing.

**Comment by grumpyinca** [comment]
See changes made in #744.
