### ISSUE TITLE
Tutor & Demo script updates driven by recent changes

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#729]
Script changes associated with validity are mostly in place.  Additional changes corresponding to the Alerts facility and compression spring length and deflection limits at the solid condition are appropriate.  Scripts impacted include:

- demoDesignValidation - Search failure
- demo3
- demo10
-
- tutor 3 - p9 - Search failure
- tutor 7 - p10 - Search failure
- tutor 8 - p3 - Search failure

Remove demo start point from all tutor scripts.
Update tutor8 Trade parameters.
Remove double seeks
Improve wording in Alert Help C105

**Comment by grumpyinca** [comment]
Deferring these changes until the resolution of #730.  Making changes now would upset the reference point and require yet another test pass through all the demo & tutor scripts.

**Comment by 1fifoto** [comment]
merged into master, closing
