### ISSUE TITLE
Dep Var hint msg also appears for Indep Var & Calc Inputs

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#732]
A recent change (applying to Calculator View only) with the words: 

> To control the value of a Dependent Variable either FIX it or enable its MIN and/or MAX constraints and then set its constraint values. This allows SearchButton to find the Dependent Variable's value that is within this constraint range.

also appears in the pop-up dialog to change Independent Variables and Calculation Inputs.

**Comment by 1fifoto** [comment]
Added conditional logic to display words only if Dependent Variable.

Independent Variable display
![Screen Shot 2022-08-27 at 9 34 19 AM](https://user-images.githubusercontent.com/1581602/187034902-bc70f79a-552c-4536-a4bb-551af89d180d.png)

Dependent Variable display
![Screen Shot 2022-08-27 at 9 34 41 AM](https://user-images.githubusercontent.com/1581602/187034919-d75702ec-c1a9-4198-8048-d3bea8769a7b.png)

Calculation Input display
![Screen Shot 2022-08-27 at 9 34 31 AM](https://user-images.githubusercontent.com/1581602/187034928-608e533c-2370-482f-ba57-35420f2f2a23.png)

Merged into master, clsoing
