### ISSUE TITLE
Alert for invalid doesn't list name of propagated var

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#734]
Page 8 of the DemoNewDesign script illustrates this issue.  Note that the #8 entry:

8	Info	INVALID VALUE: L_2 (0.5988) <= 1.055	L_2
should say: 
8	Info	INVALID VALUE: L_2 (0.5988) <= L_Solid (1.055)	   ...

**Comment by 1fifoto** [comment]
Repaired in #730, clos
![Screen Shot 2022-08-28 at 8 08 03 AM](https://user-images.githubusercontent.com/1581602/187075601-35722e30-d1b6-4931-915b-093c93dad85e.png)
ing
