### ISSUE TITLE
<p> cannot appear as descendant of <p>

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#741]
Red traceback message in Developer tools console appears when running the tutor8 script on the p6 --> 7 transition.  It is not necessary to interact with the script.  Just keep pressing "Next". 

index.js:1437 
        
       Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    in p (at tutor8.js:289)
    in p (at tutor8.js:288)
    in div (at ExecutePanel.js:164)
    in div (created by Row)
    in Row (at ExecutePanel.js:163)
    in div (created by Container)
    in Container (at ExecutePanel.js:151)
    in div (created by Alert)
    in Transition (created by Fade)
    in Fade (created by Alert)
    in Alert (at ExecutePanel.js:150)
    in ExecutePanel (created by Connect(ExecutePanel))

**Comment by 1fifoto** [comment]
Change tutor8.js from

                    <p>
                    <p>
                    Based on the Objective Value, it appears that moving the constraint from
                    its original value of 2.0 inches to a new value of approximately 2.6 inches 
                    produces a result that is is right at the edge of feasibility.
                    </p>
                    
                    Of course it is possible to combine any or all of these approaches.
                    Trade will be happy to calculate how far it is necessary to move
                    if multiple constraints are to be adjusted concurrently ... 
                    just give more than one non-zero entry
                    when defining the weights at the beginning of Trade's process.
                    </p>

to

                    <p>
                    Based on the Objective Value, it appears that moving the constraint from
                    its original value of 2.0 inches to a new value of approximately 2.6 inches 
                    produces a result that is is right at the edge of feasibility.
                    </p>
                    
                    <p>
                    Of course it is possible to combine any or all of these approaches.
                    Trade will be happy to calculate how far it is necessary to move
                    if multiple constraints are to be adjusted concurrently ... 
                    just give more than one non-zero entry
                    when defining the weights at the beginning of Trade's process.
                    </p>

Merged into master, closing
