### ISSUE TITLE
Restore autoSave does not restore preferences & properties

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#761]
Restore autoSave does not restore preferences & properties.  Should it ?  Answer is not clear.

**Comment by 1fifoto** [comment]
Working as designed, both FilePreferences and FileProperties have always save the autosave file since it was originally written. Documentation should be updated to reflect the actual behavior.

**Comment by grumpyinca** [comment]
Documentation for v4.4 was updated in #753.
