### ISSUE TITLE
Improve ObjectiveValue Viewer tool

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#764]
Add checks for ObjectiveValue divide by zero

**Comment by 1fifoto** [comment]
![Screenshot 2023-01-01 at 4 26 41 PM](https://user-images.githubusercontent.com/1581602/210186318-cc7da65b-6a39-48b7-84e4-40f650e14c1a.png)

**Comment by grumpyinca** [comment]
It is my understanding that this branch is currently in a "double update" situation.  It has been included in the released version of 4.3.3, but not yet integrated into the master branch.

**Comment by 1fifoto** [comment]
Go find where ObjectiveValue Viewer tool has changes in other branches/issues.

**Comment by 1fifoto** [comment]
Merged into master, closing
