### ISSUE TITLE
Calculator view of OD_2 and ID_2 are stale

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#766]
Two ways reproduce the problem: 
 - open extension spring initialState in V4.3.2 and enter a value of 0.054 for Wire_Dia.  The Calculator View for OD_2 and ID_2 will show a stale value.  The values of NaN display in Report 1 and the Alerts.  That NaN value should have displayed in Calculator View.
 - open torsion spring initialState in V4.3.2 and enter a value of 10.0 for M_1.  OBJ and the alerts will show infinity.  Advanced & Calculator views will show a stale value for Cycle_Life. The (now repaired in branch #765) value of infinity is what should have been displayed. 

We did a bit of investigation.  The trail starts with components/Value.js.

This fix is now in this branch.

**Comment by grumpyinca** [comment]
Today's conversation brought of the idea of extending this issue to cover similar problems in SymbolValue.

**Comment by grumpyinca** [comment]
It is my understanding that he fix for this issue has **not** been included in the released version of 4.3.3, and it is not yet integrated into the master branch.

**Comment by 1fifoto** [comment]
Merged into master, closing
