### ISSUE TITLE
Add logging to DisplayMessage

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#771]
- Add log usage call into DisplayMessage
 - Add  'return' after displayMessage in RequestTable, ActionSearch and ActionSeek. 

This improves logging detail & accuracy and prevents unwanted invocation of the succeeding function(s).

**Comment by grumpyinca** [comment]
It is my understanding that the fix for this issue has **not** been included in the released version of 4.3.3, and it is not yet integrated into the master branch.

**Comment by 1fifoto** [comment]
Merged into master. closing
