### ISSUE TITLE
Message after Seek if constrained in that direction

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#781]
### Original thinking preserved here.  See below for update(s).

Consider adding code that will block Seek and produce a termination condition message in the case that there is a pre-existing constraint on the target variable in the specified direction. 

For example:
If there is a MIN constraint established on Weight, then Seek MIN Weight will immediately return with no changes and produce a termination condition message similar to "Seek Canceled.  Remove the MIN constraint on Weight and try again.".

**Comment by grumpyinca** [comment]
### New thinking prompted by today's discussion:

Considering; 
 - when run, the pending Seek operation may never reach the constraint in question
 - Seek is intended to explore the feasible region.  The constraint in question is part of that feasibility boundary and philosophically it should be discoverable in a consistent way.

It is better to not block the Seek operation but instead, if after Seek finishes, an active constraint on the variable in question is violated, provide a message (pop-up?, part of the termination condition message?, Alert?) that explains to the user that the constraint is limiting further progress in the specified direction.

For example:
If there is a MIN constraint established on Weight, then Seek MIN Weight runs when requested with no interruption.  After the Seek operation completes, if an enabled MIN constraint on Weight is violated, words similar to "**_The MIN constraint on Weight is limiting further progress.  You may want to relax or disable this constraint and then run Seek again._**" are appended to the termination condition message.

**Comment by 1fifoto** [comment]
Completed update, see screen shot with ioopt = 6

<img width="1870" alt="Screenshot 2023-04-09 at 2 56 27 PM" src="https://user-images.githubusercontent.com/1581602/230793874-c2ef85ee-9580-4120-bd0a-51601b532ad5.png">

Merged into master, closing
