### ISSUE TITLE
CalcView Stress@MaxSafe background color 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#784]
When Extension & Torsion spring Calculator View renders the value of Stress in the Max Safe loading condition, the background should be light gray for Prop_Calc_Method = 1 and = 2.  Currently (v4.3.3) for those values of Prop_Calc_Method, the background is white (indicating that the user should be able to change that value).  A white background is appropriate for Prop_Calc_Method = 3.

See line 92 of Spring/Extension/Calculator.js
See line 96 of Spring/Torsion/Calculator.js

**Comment by 1fifoto** [comment]
Checked into branch 784 based upon master-4.3.3

**Comment by 1fifoto** [comment]
Merged into master, closing
