### ISSUE TITLE
Ignore odop.herokuapp.com/?NNNN= requests

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#785]
See the comments below for more background on this issue.

**Comment by grumpyinca** [comment]
Chat transcript for Google Analytics case: 3-8598000033398
Nov 3, 2:53 PM (Pacific Time)

2:54:36 PM Spring Design Software: Spring Design Software joined the conversation
2:54:37 PM Anonya: Anonya joined the conversation
2:54:47 PM Anonya: Thank you for contacting Google Ads Support. My name is Anonya. How are you today?
2:55:10 PM Spring Design Software: Hello
2:55:31 PM Spring Design Software: I am well.
2:56:45 PM Anonya: Glad to hear that.
2:56:54 PM Anonya: I see that you've listed 7233556823 as the CID. Can I confirm this is the account we're looking into?
2:57:05 PM Spring Design Software: I get a continuing stream of these visits.  I know that they originate in China.  The geolocation is not set.
2:57:41 PM Anonya: I see. Is the Analytics property id - UA-146047130-1 ?
2:58:04 PM Spring Design Software: That number was automatically filled in.  I don't know how to confirm it.
2:58:34 PM Spring Design Software: I got the UA number by clicking in the upper left of the page.
2:59:17 PM Anonya: You can check that under Admin >> property
3:00:59 PM Spring Design Software: Under All accounts it says ODOP:Spring and then that UA number.
3:01:20 PM Anonya: Thank you for confirming.
3:02:39 PM Spring Design Software: Again, I am concerned that this specific stream of bounce visits is a negative impact on page rank.
3:03:05 PM Anonya: I understand, let me check the screenshot you shared.
3:04:31 PM Spring Design Software: The "page URL" is of concern.
3:05:10 PM Spring Design Software: It tells me that there is something bogus about this visitor.
3:05:55 PM Anonya: I am checking further on this.
3:06:10 PM Anonya: Please give me 9-10 minutes while I get this checked for you.
3:07:45 PM Spring Design Software: You should know that SpringDesignSoftware.org and odop.herokuapp.com are tied together as a single Google Analytics property.  I am not sure of the terminology ... GTID ?
3:15:46 PM Anonya: Thank you for staying connected.
3:16:06 PM Spring Design Software: Sure.  Thanks for your help.
3:18:02 PM Anonya: I got this checked further, if you are considering blocking such users, you can check with your web developer and block such ip addresses from the website. In Analytics we have an option to exclude internal traffic through the dashboard, however for external traffic exclusion, you would have to check with your web developer
3:18:54 PM Spring Design Software: I believe that the IP addresses change with each new visit.
3:20:14 PM Anonya: I understand.
3:20:42 PM Spring Design Software: Are you saying that these bounce visits are actually impacting page rank ?
3:23:04 PM Anonya: Well, it depends, high bounce rate can be both a  good and bad thing. However to address this you can use the external ip exclusion form website,.
3:23:57 PM Spring Design Software: Do you have a link for the external ip exclusion form website ?
3:24:27 PM Spring Design Software: Do you have a link for that the external ip exclusion form website ?
3:25:26 PM Anonya: Well no, we do not have that. It is done through the website, please check with the web developer. We only have the provision for internal traffic exclusions - https://support.google.com/analytics/answer/1034840?hl=en
3:26:57 PM Spring Design Software: Yes, I understand. I have already excluded my own activities on the website
3:28:39 PM Anonya: Right! I got this checked again, for external traffic exclusions in Analytics, we do not yet have an option. It can only be done through the website. As we are not trained on coding and web development, you might have to reach out to your web development provided
3:28:54 PM Spring Design Software: Now I think that I understand the confusion.  You typed "form" when you meant "from".
3:29:15 PM Anonya: I truly apologize for that.
3:30:36 PM Spring Design Software: OK, I think that we have taken this conversation as far as it will go.  We can wrap up.
3:31:06 PM Anonya: Sure! Please tell me if you have any other question for me.
3:31:59 PM Spring Design Software: I will start a new chat session as new questions come up.  Thanks for your help today.  Bye for now.
3:32:08 PM Anonya: Thanks for using Chat and have a great rest of your day!
3:32:11 PM Anonya: Anonya left the conversation
3:32:12 PM Anonya: Please take a minute to provide your feedback about this interaction. We'll use your responses to improve our products and services. Thanks! Click here to access the short survey: https://support.google.com/google-ads/contact/survey_transactional?&cxtype=1&caseid=ANT8d0EwQeGgv-NXBqeTr8t9EP5Zx7V2LXSb5-dAJr7IJfG_zJTO5szJlJQ=
For your reference, your case number is 3-8598000033398. 

3:32:12 PM Anonya: Anonya ended the conversation

**Comment by grumpyinca** [comment]
<img width="1777" alt="ChinaBounce" src="https://user-images.githubusercontent.com/39974784/200158710-726843b0-c4da-4b4c-a8dd-9c3d8baf1608.PNG">

**Comment by 1fifoto** [comment]
Merged into master, closing
