### ISSUE TITLE
Eliminate use of Heroku create-react-app-buildpack

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#786]
Eliminate use of Heroku create-react-app-buildpack and possibly replace with [heroku-cra-node](https://github.com/mars/create-react-app-buildpack)

**Comment by grumpyinca** [comment]
From the Heroku build log:

=====! create-react-app-buildpack has reached end-of-life 🌅
       This build may succeed, but the buildpack is no longer maintained.
       On the Heroku-22 stack and beyond, this may fail to build at all.
       Please consider migrating to https://nextjs.org or https://remix.run to develop React apps which are deployable using Heroku's Node.js buildpack https://github.com/heroku/heroku-buildpack-nodejs, or you may develop your own create-react-app deployment with Node.js and Nginx buildpacks.

**Comment by 1fifoto** [comment]
We have replaced the https://github.com/mars/create-react-app-buildpack.git with our own https://github.com/thegrumpys/create-react-app-buildpack.git. We have also updated it from Ruby to Node, and from Static to NGINX.

**Comment by grumpyinca** [comment]
Per Slack conversation, this issue involved both changes on the Heroku website config and two new GitHub repos but no code.  There is no branch.  Closing.
