### ISSUE TITLE
Min and Max Constraint Table output when narrow has no names

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#79]
This what it looks like with no names on the left side
![screen shot 2018-08-05 at 7 29 28 pm](https://user-images.githubusercontent.com/1581602/43691712-1b539164-98e6-11e8-831a-48c9126bd4ac.png)

And this is what is should look like
![withnames](https://user-images.githubusercontent.com/1581602/43691841-85b9b064-98e7-11e8-91b2-6ebdd3d03fab.png)

**Comment by grumpyinca** [comment]
Note the relationship to issue #219.

**Comment by grumpyinca** [comment]
See issue #313.

**Comment by 1fifoto** [comment]
Completed in #313, closing
