### ISSUE TITLE
Improvements to Help : About dialog

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#800]
### Possible improvements to the Help : About dialog:

1. "Model Description:" should link to the documentation description page associated with the currently active design type.  See the image below for possible positioning on the About dialog.

2. Add a database size status line to the Help About dialog ... visible to admin only 

<img width="257" alt="HelpAboutEdited" src="https://user-images.githubusercontent.com/39974784/213795234-89aee750-d594-4d28-a0bd-2f2903b11e23.png">

**Comment by grumpyinca** [comment]
See #807.

**Comment by 1fifoto** [comment]
Added Item 1 above "Model Description". Screen shot of output.
![Screenshot 2023-01-21 at 1 17 13 PM](https://user-images.githubusercontent.com/1581602/213883494-5b91fb78-fda6-44e8-9bbd-deda783c44d6.png)

**Comment by 1fifoto** [comment]
Merged into master, closing
