### ISSUE TITLE
Add Search & Seek in SymbolValue and SymbolValueWireDia Components

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#809]
It is believed that adding Search & Seek in SymbolValue and SymbolValueWireDia Components will encourage users to repeatedly invoke Search on an incremental basis as new values are entered.  Hopefully, this will highlight the point at which constraints are first violated and / or an over-specified design situation is first encountered.  Highlighting these issues sooner should reduce the potential distraction of values that have not yet been entered, thus improving the troubleshooting process.

**Comment by grumpyinca** [comment]
### Feedback from initial testing of the current state of this branch

1. SymbolValueWireDia does not yet have the changes to get the new "button treatment" 
2. The modal correctly drops after a Seek.  It should drop after a Search as well.
3. "Stgatus" should go back to "status"
4. The linked Help article (settingValues.html) needs a significant update before release.

None of these items blocks further testing.

**Comment by grumpyinca** [comment]
### Feedback from next round testing of the current state of this branch 

The Reset button is not restoring constraints properly.  Example:
1. Start from initialState
2. Menu : View : Calculator
3. Click in FS_2
4. Observe that FS_2 Max is 1.5
5. Change the value of FS_2 Min to 1.03 (any value will do)
6. Click Reset
7. Observe that the value of FS_2 Max has become 1.02 **<--- This is the bug !**

**Comment by grumpyinca** [comment]
Discussion of entry 8 in Jan 29 comment:
Consider: rather than add a tooltip, don't display the Seek button.

**Comment by grumpyinca** [comment]
Regarding item 6 in the January 29 and January 31, 2023 comments above.

In the ideal case, the round "info" spot and its associated tooltip would be limited to appear only immediately after a search that produces a "NOT FEASIBLE" result.  It would clear at the same time that the termination message is cleared. 

If restricting the appearance of the "info" spot and its associated tooltip in this way provides implementation challenges, a compromise might involve suppressing it when "NOT FEASIBLE" and the termination message is empty (null, blank).

**Comment by grumpyinca** [comment]
#### Current version test results:

The exact sequence is not well documented.  Clicked something (Reset?) and got traceback in red: 
```
Error: In reducers.RESTORE_OUTPUT_SYMBOL_CONSTRAINTS, No old value exists for restore
(anonymous function)
C:/Users/Mike/git/odop/client/src/store/reducers.js:268
  265 |             smax: sclden(state.model.system_controls, element.value, cmax, element.sdlim, lmax)
  266 |         });
  267 |     } else {
> 268 |         throw new Error('In reducers.RESTORE_OUTPUT_SYMBOL_CONSTRAINTS, No old value exists for restore');
      | ^  269 |     }
  270 | }
  271 | return element; 
```

The last few lines in the usage log are: 
```
6375, 2023-03-06 00:25:41, 2023-03-06 00:25:41, 127.0.0.1, {"tag":"event","action":"ActionSearch","note":{"event_value":21,"event_label":"Element Wire_Dia 66.72 --> 0.1417"}}, , , , 
6376, 2023-03-06 00:27:34, 2023-03-06 00:27:34, 127.0.0.1, {"tag":"event","action":"Values","note":{"event_value":22,"event_label":"Wire_Dia(FixedFlag)=FREE"}}, , , , 
6377, 2023-03-06 00:27:34, 2023-03-06 00:27:34, 127.0.0.1, {"tag":"event","action":"ActionSearch","note":{"event_value":23,"event_label":"Element Wire_Dia 0.1417 --> 0.000009015"}}, , , , 
6378, 2023-03-06 00:27:48, 2023-03-06 00:27:48, 127.0.0.1, {"tag":"event","action":"ActionSeek","note":{"event_value":24,"event_label":"Element Wire_Dia MIN"}}, , , , 
6379, 2023-03-06 00:28:00, 2023-03-06 00:28:00, 127.0.0.1, {"tag":"event","action":"ActionSearch","note":{"event_value":25,"event_label":"Element Wire_Dia 0.00002081 --> 0.000009302"}}, , , , 
6380, 2023-03-06 00:28:44, 2023-03-06 00:28:44, 127.0.0.1, {"tag":"event","action":"ActionSeek","note":{"event_value":26,"event_label":"Element Wire_Dia MIN"}}, , , , 
6381, 2023-03-06 00:29:22, 2023-03-06 00:29:22, 127.0.0.1, {"tag":"event","action":"ActionSearch","note":{"event_value":27,"event_label":"Element Wire_Dia 0.00002888 --> 0.000009710"}}, , , , 
6382, 2023-03-06 00:30:22, 2023-03-06 00:30:22, 127.0.0.1, {"tag":"event","action":"ActionSearch","note":{"event_value":28,"event_label":"Button 28.67 --> 0.1416"}}, , , , 
```

I will attempt to reproduce this bug and document the sequence more carefully.

**Comment by grumpyinca** [comment]
Should Search and Seek buttons appear in the "Edit Independent Variable Wire_Dia" modal when the "Select std size" radio button is active ?  Having the std size option selected might imply that the results of Search and Seek might be restricted to standard wire sizes.  Such a feature is proposed in #825, but is not available in the current code.

**Comment by grumpyinca** [comment]
There seems to be a recently introduced problem in the way that user input of numeric values is validated. The problem described here does not appear in the 4.3.3 staging system. 

1. Reset the app.
2. View : Calculator
3. Click in Wire_Dia input field.
4. Observe "Edit Independent Variable Wire_Dia" modal appears.
5. Select "Enter non-std value" radio button
6. Double click in Wire_Dia input field
7. Observe that the entire existing value is highlighted.
8. Enter a decimal point
9. Observe a single pixel red border
10. Enter "0"  (single digit zero)
11. Observe that the decimal point disappears.  <-- This is the problem.

**Comment by 1fifoto** [comment]
(6613, '2023-03-11 18:56:38', '2023-03-11 18:56:38', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"Index\",\"note\":{\"event_value\":0,\"event_label\":\"window.location.search=\"}}', NULL, NULL, NULL, NULL),
(6614, '2023-03-11 18:56:38', '2023-03-11 18:56:38', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"Routes\",\"note\":{\"event_value\":1,\"event_label\":\"type: null load defaultDesign\"}}', NULL, NULL, NULL, NULL),
(6615, '2023-03-11 18:56:46', '2023-03-11 18:56:46', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"Routes\",\"note\":{\"event_value\":2,\"event_label\":\"type: Spring/Compression name: Startup\"}}', NULL, NULL, NULL, NULL),
(6616, '2023-03-11 18:56:53', '2023-03-11 18:56:53', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"ViewSelect\",\"note\":{\"event_value\":3,\"event_label\":\"Calculator\"}}', NULL, NULL, NULL, NULL),
(6617, '2023-03-11 18:57:50', '2023-03-11 18:57:50', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"Values\",\"note\":{\"event_value\":4,\"event_label\":\"Wire_Dia(FixedFlag)=AUTOFIXED\nWire_Dia(NumericValue)=0.10498\nForce_2(MinConstraintFlag)=Enabled\nForce_2(MinConstraint)=41\nL_Stroke(MinConstraintFlag)=Enabled\nL_Stroke(MinConstraint)=1.75\"}}', NULL, NULL, NULL, NULL),
(6618, '2023-03-11 18:57:50', '2023-03-11 18:57:50', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"ActionSearch\",\"note\":{\"event_value\":5,\"event_label\":\"Element Wire_Dia 0.06588 --> 0.000005880\"}}', NULL, NULL, NULL, NULL),
(6619, '2023-03-11 18:58:17', '2023-03-11 18:58:17', '127.0.0.1', '{\"tag\":\"event\",\"action\":\"Values\",\"note\":{\"event_value\":6,\"event_label\":\"Wire_Dia(FixedFlag)=FREE\"}}', NULL, NULL, NULL, NULL);

**Comment by 1fifoto** [comment]
Merged into master, closing
