### ISSUE TITLE
Test results from v4.4 (alpha)

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#828]
Testing has discovered the following issues in the current development version of v4.4.  This version may be considered at the "alpha" stage of development.  Branch #599 and various documentation branches have not yet been merged.

1. Weird things going on. At first, I thought that it might be just with operations that interact with the server.  Now I am thinking that it is broader than that.  Perhaps it is something about the development environment.  For example: 
   1. After a few operations, an attempt to reload the browser tab produces no result except the browser spinner running indefinitely.  It is necessary to close the browser tab to recover.
   1. After multiple consecutive File : Open operations, an open will "hang" with the spinner running.  It is necessary to execute a browser reload. 
   1. Clicking on the context sensitive Help button in Calculator View IV, DV or Wire_Dia modal dialog boxes produces a blank screen with browser spinner animation that persists indefinitely.  Observe CPU utilization corresponding to one thread at 100%.  The browser spinner continues after the Help tab is closed.  A browser re-load is required to restore normal operation.  The associated Help topic is not reliably accessible through the Help : Index menu. 
2. /odop/client/.env contains: `REACT_APP_DESIGN_TYPES=["Hookes-Law/Compression","Hookes-Law/Extension","Hookes-Law/Torsion", ` and thus these design types appear on the File : Open menu and a `Error: Cannot find module` traceback occurs if they are selected. 

Note: I renumbered the items under item 1 above, so I could reference them in my comments below.

**Comment by grumpyinca** [comment]
I did another pull but continue to get the previously described behavior in master with both Edge and Chrome.  Just to prove that my successful operation in branch 809 was not a fluke, I switched to branch 764, pulled and observed correct behavior (using Chrome).  So, my problems are observed only with the master branch. 

I switched to master, ran npm run harp-compile, and (localhost:3000) loaded the app into Chrome.  I did File : Open on extension Startup and torsion Startup_Metric.  I then did (iii) above and observed the failure as described.  

I wonder if rather than troubleshooting the infrastructure of my development environment, it might be better to go forward with building a new VM from scratch.  It will take much longer but I am looking to do that anyway.

**Comment by 1fifoto** [comment]
Repaired problem in #785 which was hanging File Open in loop. Merged that branch back into master. I feel this repairs item 1.ii.

**Comment by grumpyinca** [comment]
Currently, the Search button in the Calculator View Edit Independent Variable xxx dialog box does not appear if the xxx independent variable is in Fixed status.  While this may be the appropriate action for a Seek, it may be overly restrictive in the case of a Search.  A bit more thought may be appropriate.  I am currently thinking that the Search button should appear unless the Fix on xxx leaves no other Free independent variables.

**Comment by 1fifoto** [comment]
For Item 1 in the previous comment we choose not to make the Search button appear in Calculator View Edit Independent Variable xxx dialog box, because the user is focused on the specific independent variable which is fixed and will NOT BE changed by the Search.

For item 2 in the previous comment Bri ran the steps and was unable to reproduce the failure, instead he was not able to run out of memory and the Seek operation completed successfully. However it did take 30-60 seconds to complete the Seek.

**Comment by 1fifoto** [comment]
Merged in 599 to rename from .js to .jsx.

**Comment by grumpyinca** [comment]
## Testing of v4.4rc1 in the staging system

1. Opened Issue #xxx Memory utilization of Search & Seek operations

I used Windows Task Manager to focus on Edge memory utilization of the system.  I noted that the Memory-in-use value changes dynamically and is only loosely connected to user input.  When the system was first launched, I observed 77.1 MB.  Before loading the extension spring model: 49.3 MB.  After loading the extension spring model: 92.6 MB.  When running the final Seek of the usage_log_18Mar23debug.txt test case from the comment above, the Memory-in-use value continuously increased until it reached a peak greater than 1,961 MB.  After several user inputs (Fix, Search, etc.) the Memory-in-use value dropped to a number in the 400's.  

Screen captures:  [MemoryScreenCap828.zip](https://github.com/thegrumpys/odop/files/11012556/MemoryScreenCap828.zip)

**Comment by 1fifoto** [comment]
Fixed in branch #599, checked in, more testing can now be done...

**Comment by grumpyinca** [comment]
Merged to master, closing.

Changes coming out of from additional testing on v4.4rc? will be done on a new issue.
