### ISSUE TITLE
Create demoNewDesign test case

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#830]
Base it on the current demoNewDesign.js execute file.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by grumpyinca** [comment]
### Concerns about current operation of the script generator 

1. Is it possible that `// Page nn of mm` comments can appear after the action as opposed to before ? 

2. In some cases, an extra semi-colon can appear in the translation.  For example: 
    `setSymbolFlag('L_Solid', MAX, CONSTRAINED),`
can translate to 
    `store.dispatch( setSymbolFlag("L_Solid",MIN,CONSTRAINED); ); `

3. In one case, a MAX gets translated to a MIN.  For example: 
```
                setSymbolFlag('L_Solid', MAX, CONSTRAINED),
                changeSymbolConstraint('L_Solid', MAX, 1.060),
```
gets the very spooky translation to: 
```
    store.dispatch( setSymbolFlag("L_Solid",MIN,CONSTRAINED); ); 
    store.dispatch( changeSymbolConstraint("L_Solid",MIN,1.06); ); 
```

**Comment by grumpyinca** [comment]
### Idea for improvement of script generator

Include a comment, likely near the top (near "`// This is a mapping of the` ..."), that provides the RegEx syntax for "ExecutePanel.jsx:nnn " where nnn is any 3 digits. 

This will facilitate the mass replacement of all such strings with four blanks.

**Comment by 1fifoto** [comment]
Update branch 830 for improvements 1, 2 and 3 in the previous comment, and merged into master
