### ISSUE TITLE
Execute to Test View

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#832]
Presently in #830 we generate console output when a macro (AK an execute file) runs. This output is used to create a test case by dispatching redux calls and checking the objective value. Then this console output must be copied and edited into an actual test case. The edits remove function name & line numbers along with deleting any spurious [Violation] output. This issue is to enhance this capability by creating a new ExecuteToTest view which no longer needs to be edited but can be copied directly into a test case file.

**Comment by 1fifoto** [comment]
Sample screen shot

<img width="1431" alt="Screenshot 2023-04-08 at 3 01 12 PM" src="https://user-images.githubusercontent.com/1581602/230740423-6b37f9de-46a4-4ec0-b125-a1194d092e2a.png">

Merged into master, closing.

**Comment by grumpyinca** [comment]
### Possible refinements

1.  If an import entry is missing, test fails.  If an import entry is included but unnecessary, test does not even produce a warning.  Thus, I suggest that the import template become a superset of all possible entries. 

2. It may be possible to save an edit for "xxx" in: 
`// This is a mapping of the xxx execute file to an equivalent test case file`
