### ISSUE TITLE
Provide Calc View Search shortcut for Fixed I.V.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#836]
ODOP version 4.4 provides Search and Seek shortcuts in the Edit Variable pop-up modal dialog of Calculator View.  This feature is intended to lead the user to invoke Search earlier and more frequently in the hope of improving user insight into exactly which change forces a transition from feasible to infeasible.  For the case of Independent Variables in Fixed status, the shortcuts are suppressed.  The thinking here is that because the dialog is specific to that Independent Variable, the user would be expecting to see Search make changes in that variable but that cannot happen because the variable is in Fixed status.

Observation of user behavior suggests that this suppression of the Search shortcut for Fixed Independent Variables negatively impacts the original objectives for the shortcuts in a significant way.  This is particularly true for evaluators because it is common for them to begin by evaluating ODOP's results with a known good spring.  Those evaluators enter a sequence of Independent Variables.  The fact that the AutoFix feature is on by default mean that each of those values are assigned Fixed status and thus the evaluator user may never see the Search shortcut. 

This issue proposes to improve the situation by enabling (not suppressing) the Search (but not Seek) shortcut button in the Edit Variable pop-up modal dialog of Fixed Independent Variables in Calculator View when OBJ > OBJMIN.  In order to address the original concern about user confusion of Search not changing the value of the currently selected Independent Variable when it is in Fixed status, I propose a tooltip on the Search button with wording along the lines of: 
"_{current Independent Variable name}_ is Fixed.  Search will change the values of Free variables, specifically, _{list of Independent Variables in Free status}_, to find a feasible solution." 

The tooltip should not appear if the variable is in Free status.  The proposed changes should be made to the Edit Independent Variable Wire_Dia dialog box as well.

The changes proposed here are only one possibility.  Other approaches to resolving the fundamental problem are possible and should be considered.

**Comment by grumpyinca** [comment]
#### Proposed change to tooltip wording:
"The Independent Variable {current Independent Variable name} is Fixed. Search manipulates only the values of Free Independent Variables.  Press this Search (solve) button to have Search alter the values of {list of Independent Variables in Free status}, to locate a feasible solution (if available)."

#### While I am reluctant to make the tooltip any longer, it may be helpful to add:
"As always, Dependent Variables change to reflect the current values of Independent Variables."

**Comment by grumpyinca** [comment]
The tooltip pop-up does not clear after Search completes.  The only way out is to manually close the dialog.  Should the dialog close after Search completes?

**Comment by 1fifoto** [comment]
Merged into master, closing
