### ISSUE TITLE
messageOfTheDay - changes prior to v4.4.1 release

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#838]
This issue provides a branch to isolate changes to messageOfTheDay.md.  MOTD updates can be published to GitHub Pages independently of publishing the new release to odop.herokuapp.com.

Whenever this branch is merged into master, updates to messageOfTheDay are published to GitHub Pages within minutes.

**Comment by 1fifoto** [comment]
Merged into master, closing
