### ISSUE TITLE
Cleanup obsolete bits in SpringDesignSoftware.org

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#842]
Remnants of previous efforts in SpringDesignSoftware.org (DreamHost) remain.  Also, supporting remnants remain in the master branch.  This stuff should be cleaned up.  Specifically:

 - In master branch, remove scripts/build.sh.

 - In SpringDesignSoftware.org, remove git/hooks/post-receive.

 - In SpringDesignSoftware.org, remove npm, node, nvm, etc.

 - In /home/mikmil36/springdesignsoftware.org, remove the odop directory.
 
 - In /home/mikmil36, remove the build, and git directories.

**Comment by 1fifoto** [comment]
All done...
* In master branch, remove scripts/build.sh - DONE
* In SpringDesignSoftware.org, remove git/hooks/post-receive - DONE
* In SpringDesignSoftware.org, remove npm, node, nvm, etc - DONE
* In /home/mikmil36/springdesignsoftware.org, remove the odop directory - DONE
* In /home/mikmil36, remove the build, and git directories - DONE
