### ISSUE TITLE
On start, check for AutoSave. If found, take these actions

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#845]
When ODOP starts, check for the existence of AutoSave data.  If found:

 - Write a Google Analytics event / usage log entry indicating that it was found. 
  -- This will be a more reliable indication of a returning user than IP address alone
 - Suppress execution of the welcome script (if it was scheduled) 
  -- The user will have already had an opportunity to review the welcome script.  For unknown reasons, many users fail to exit the welcome script and thus are forced into unnecessary scrolling.

**Comment by 1fifoto** [comment]
Also changed Execute Panel's Exit button to be Close button and made script and documentation changes throughout.

**Comment by 1fifoto** [comment]
Merged into master, closing
