### ISSUE TITLE
Calc View Wire_Dia Search tooltip sometimes fails to clear

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#846]
Given a poorly understood set of circumstances, the tooltip associated with the Search button in the Calculator View **Edit Independent Variable Wire_Dia** dialog can fail to clear after Search completes.  The screen capture below illustrates a case where the tooltip persists after Search has completed.  

<img width="254" alt="image" src="https://github.com/thegrumpys/odop/assets/39974784/978d4f08-50a1-4908-a9f0-edb37af6cf80">

&nbsp;

Note that the failing case is highly invalid.  Search failed to increase the coil diameter; Spring_Index is barely greater than 1.0.  The numerics of the math model are in trouble.  Is it possible that the numeric issues relate to the tooltip failing to clear ?

#### Steps to replicate the problem:
_Specifically, the problem does not appear with values of Wire_Dia <= 0.51 but does appear with values of Wire_Dia >= 0.52._

1. Launch (or reload) ODOP with defaults: Compression spring, US units
2. View : Calculator
3. Click Wire_Dia value field.  Observe Edit Independent Variable Wire_Dia dialog.
4. Change value of Wire_Dia to 0.51 (inches) 
5. Hover mouse cursor over the Search button.  Observe tooltip.
6. Click Search
7. Observe that the tooltip clears, the Search button disappears, and the search result is STRICTLY FEASIBLE. **<-- This is correct (desired) behavior**

&nbsp;

8. Launch (or reload) ODOP with defaults: Compression spring, US units
9. View : Calculator
10. Click Wire_Dia value field.  Observe Edit Independent Variable Wire_Dia dialog.
11. Change value of Wire_Dia to 0.52 (inches) 
12. Hover mouse cursor over the Search button.  Observe tooltip.
13. Click Search
14. Observe that the tooltip does not clear, the Search button DOES NOT disappear, and the search result is NOT FEASIBLE. **<-- This is the bug; (not desired behavior)**

**Comment by 1fifoto** [comment]
Merged into master, closing
