### ISSUE TITLE
Gtag changes associated with GA4

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#849]
The transition from Google Analytics older "Universal Analytics" to the newer "GA4" has introduced a new recommended approach to Gtag creation.  In an Aug 23 email message, Pat writes:

**_The new GA4 property is connected to the old Universal Analytics tag (and that has been working properly on springdesignsoftware.org), but I think that we should instead try replacing the Universal Analytics tracking code with the actual GA4 tracking code below in all uses to try to fix this cross-domain tracking issue:_** 

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-PJ64GHQX6P"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PJ64GHQX6P');
</script> 
```

Note that some changes in #840 impacted Gtag code.

**Comment by 1fifoto** [comment]
Merged into master. closing
