### ISSUE TITLE
Inverted constraints do not block Search & Seek

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#857]
A situation of no free independent variables appears to correctly block Search and Seek.  A situation of inverted (inconsistent) constraints appears to fail to block Search & Seek.  A pause while Search or Seek happens is followed by the red error message pop-up.  Once that is cleared, it is possible to see the resultTable message indicating the results of the Search or Seek.

There appear to be as many as 8 possible cases: 
- Action : Search & Action Seek  
- Search button & Seek button  
- Calculator View value setting pop-up (non-Wire_Dia) for Search & Seek  
- Calculator View value setting pop-up (Wire_Dia) for Search & Seek  

### Details of the Action : Search case

1. Launch v4.5dev10 (current development or staging systems)
1. Remain in Advanced View.  Observe resultTable button is "Seek".
1. Change Coils_T MIN 10.1 
1. Change Coils_T MAX 9.9
1. Observe Button is now "Search"; Err level Alert for INVERTED CONSTRAINT RANGE; Coils_T=10.0 (all is OK) 
1. Invoke menu **Action : Search** 
1. Observe red pop-up
1. Observe Coils_T=9.997; resultTable message is set (indicating Search executed)  {**This is the bug**}

**Comment by 1fifoto** [comment]
This branch was built upon #854.

**Comment by grumpyinca** [comment]
Merged to master; pushed to remote (origin); closing.
