### ISSUE TITLE
Interim enhancements to ResultTable

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#869]
### Background 
Issue #866 presents a proposal for improvements to ResultTable which would include a summary of validity results from the Alert facility.  Such changes would likely require changes to the model and thus be inappropriate to include in the current "patch" release.  This issue is a proposal for changes to ResultTable that rely only on the Objective Value and thus are a better match for this release. 

For reference, after a search returning an infeasible result, the current ResultTable looks like:
![image](https://github.com/thegrumpys/odop/assets/39974784/f4b8431e-7e4b-4e4d-827a-92bf057266d3)

### Details
1. Remove the colon after "Message"
2. Add a tooltip to Action with text similar to:
"**Seek if feasible. Search if not.  Same functions as Action menu.**" 
3. Change the Status tooltip text to something similar to: 
"**Visual summary of feasibility status.  Search works to minimize Objective Value.  Search stops if Objective Value falls below OBJMIN = {objmin}**" 
4. Add a narrow (black?, purple?, crosshatch?) bar to the extreme right of the multi-color feasibility indicator. Associate it with non-finite Objective Values.
5. Add an icon to the right of the multi-color feasibility indicator. 
If the objective value is not finite, the icon should be a red-circle-with-white-exclamation-point and the tooltip text should be something similar to:
"**See Alerts for details. Objective Value = {OBJ}**" 
If the objective value is finite, the icon should be a blue-circle-with-white-i and the tooltip text should be something similar to:
"**Strictly Feasible. Objective Value = {OBJ}**" or
"**Feasible. Objective Value = {OBJ}**" or
"**Close to Feasible. Objective Value = {OBJ}**" or
"**Not Feasible. Objective Value = {OBJ}**" 
6. If Objective Value is not finite, append to the ResultTable message text to include words similar to "INVALID VALUES. See Alerts for details.". 
7. Add "INVALID VALUES" tier to the Feasibility tooltip.
8. No changes to:
- the info icon and tooltip that appears adjacent to red NOT FEASIBLE in the feasibility field after a search.
- the Search / Seek button and its tooltips

**Comment by grumpyinca** [comment]
See related work accomplished under #871.

**Comment by 1fifoto** [comment]
Merged into master. closing
