### ISSUE TITLE
Improve Search / Seek response to non-finite objective value

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#871]
An experiment with blocking Search & Seek when the Objective Value (OBJ) was not finite was coded but later removed when it was discovered that a small modification to Pattern Search allows appropriate results when the Objective Value is infinity.  The modification is described in the next comment.

**Comment by 1fifoto** [comment]
Changed patsh from '<' to '<=' to allow s_psi to be infinity. Make sure to check both +inifinity and -infinity cases.

**Comment by grumpyinca** [comment]
Added code to provide a warning pop-up if the objective value is not finite when a Search is requested.
<img width="479" alt="image" src="https://github.com/thegrumpys/odop/assets/39974784/398b2e2e-d2b1-4926-8009-c7f1ba4ff4cd">

**Comment by grumpyinca** [comment]
Added context specific Help for the button in the pop-up described above.  It is in client\docs\Help\errors.md.  The file selected to contain the content is a change that required changes in the link(s) referring to that file. 

Related changes and improvements in other documentation files are included.

**Comment by grumpyinca** [comment]
Merged to master; pushed to remote.  Closing.
