### ISSUE TITLE
http_parser is deprecated.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#877]
I believe that the following message started with the shift to node 16.

When issuing the "npm start" command, just before switching from the command window to the browser tab, I see a warning message that quickly disappears as the app GUI appears.  The message is:
```
"(node:11280) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use node --trace-deprecation ... to show where the warning was created)" 
```
I observed that there is a certain amount of StackOverflow conversation on the subject.  I have not attempted the suggestion of --trace-deprecation. 

This issue should be pursued as part of the set of activities moving the infrastructure forward.

**Comment by 1fifoto** [comment]
Message is no longer seen, closing.
