### ISSUE TITLE
Add info icon for Fix and Free checkboxes

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#883]

**Comment by grumpyinca** [comment]
Merged to master; pushed to remote.  Closing.

**Comment by 1fifoto** [comment]
Change Info icon to the word 'Fix'. See screen shot below.
<img width="1154" alt="Screenshot 2023-11-19 at 9 48 23 PM" src="https://github.com/thegrumpys/odop/assets/1581602/a135a8ac-44e8-4d08-9440-dfa674d3d9d4">
