### ISSUE TITLE
ODOP release 4.5.1 and Message Of The Day 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#887]
This issue provides a branch to isolate changes to messageOfTheDay.md. MOTD updates can be published to GitHub Pages independently of publishing the new release to odop.herokuapp.com.

Whenever this branch is merged into master, updates to messageOfTheDay.md are published to GitHub Pages within minutes.

Message Of The Day changes immediately after the release of version 4.4.2 were handled on issue / branch #860.

To-Do notes and other reminders related to making this release can be captured as comments to this issue.

**Comment by 1fifoto** [comment]
Merged into master, closing
