### ISSUE TITLE
Improve tooltip formatting 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#890]
Improve tooltip formatting for tooltips associated with: 
 - Alerts info icon 
 - Alerts header Severity tooltip
 - AutoFix info icon
 - ResultTable Seek button
 - ResultTable Search button

Note:  This issue was inspired by feedback from AndyR.

**Comment by 1fifoto** [comment]
How is this? Changed from 200px to 400px. It is checked into branch #890.
<img width="1238" alt="Screenshot 2023-12-08 at 3 50 09 PM" src="https://github.com/thegrumpys/odop/assets/1581602/6a3399a9-69a7-4629-b412-bc129bb5fae5">

**Comment by 1fifoto** [comment]
Merged into master, closing
