### ISSUE TITLE
Upgrade MySQL from 5.7 to 8.0

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#899]
Create new V8 JAWS DB database

    Connection Info
    Connection String
    
    mysql://agquyk27bpv35s60:cqdmcrpmrsyuef2o@ohunm00fjsjs1uzy.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/pgyb3toxyk59fz2w
    
    
    You can use your connection information to connect manually through a client such as HeidiSQL to administer your database.
    
    Property	Value	Action
    Host	ohunm00fjsjs1uzy.cbetxkdyhwsb.us-east-1.rds.amazonaws.com	
    Username	agquyk27bpv35s60	
    Password	See Heroku addons	
    Port	3306	
    Database	pgyb3toxyk59fz2w

Updated create.sql for MySQL 8.0 by changing Collation and removing Int width

[create.sql.zip](https://github.com/thegrumpys/odop/files/13929558/create.sql.zip)

Also ran compression spring load.sql

And was able to bring up the application successfully.

**Comment by 1fifoto** [comment]
Checking our current databases version

* Production - 8.0.35
* Staging - 8.0.35
* Test - 8.0.35
* Development - 8.0.35
* Other - 8.0.35

So, in other words, we have already be upgraded by JAWS DB to the 8.0 release.  I have used the aforementioned unzipped create.sql.zip, replaced it into the current create.sql, and checked it into branch 441.

Merged into 441, closing
