### ISSUE TITLE
Implement Sub-Problems

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#90]
Design Parameter and State Variable Rows should be displayed or not depending on the value of IOCLASS.

See ideas for the View menu and related discussion of IOCLASS for Sub-Problems in menu.md. 

Per discussion, this feature should be part of the spring problem implementation.

**Comment by grumpyinca** [comment]
See issue #170.

**Comment by 1fifoto** [comment]
Duplicate of 170, closing
