### ISSUE TITLE
Cleanup unused images from client/public/designtypes

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#902]
It appears that some image files in /ODOP/client/public/designtypes are redundant / left-over from a previous configuration. This should be confirmed, and any unnecessary images removed. The currently active ones are in the /ODOP/client/docs directory.

**Comment by 1fifoto** [comment]
The list of deleted files are:

* client/public/designtypes/Spring/Compression/ForceVsDeflection.png
* client/public/designtypes/Solid/RectangularSolidDiagram.png
* client/public/designtypes/Spring/Compression/SpringDesignWorkflowDiagram1.png
* client/public/designtypes/Spring/Compression/SpringDesignWorkflowDiagram2.png
* client/public/designtypes/Spring/Compression/SpringDesignWorkflowDiagram3.png
* client/public/designtypes/Spring/Compression/SpringDesignWorkflowDiagram4.png
* client/public/designtypes/Spring/Compression/SpringDesignWorkflowDiagram.png
* client/public/designtypes/Spring/Torsion/TorsionNames.png

**Comment by 1fifoto** [comment]
Merged into master, closing
