### ISSUE TITLE
Violated constraint not highlighted on File:Open

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#906]
### Summary:

There is something not quite right about (red) constraint highlighting on  File:Open immediately after system initialization.  Currently, the problem is observed only in the Startup & Startup-Metric of Piston-Cylinder because those are the only startup files that contain a violated constraint. 

**Note:** 
- the problem does not occur if starting from initial_State 
- the problem occurs on a File:Open only immediately after system initialization.  Once things are up and running, I have not been able to observe the problem. 
- making changes to any variable value or FIX / Free status will clear the problem

**Steps to duplicate the problem:**

1. Initialize the system (refresh browser or click ODOP icon at upper left; expect things to default to compression spring)
2. File:Open Piston-Cylinder Startup
3. Observe that the violated constraint on FORCE is not highlighted  **<--- this is the bug**

**Comment by grumpyinca** [comment]
The repairs in this branch also fixed issue #907 which has now been closed without any code changes.

**Comment by 1fifoto** [comment]
Merged into 441, closing
