### ISSUE TITLE
Fix displayMessage in File Save and File SaveAs

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#908]
Fix File Save and File SaveAs to display correct method in message output.

Change File Save and File Save As from

            .catch(error => {
                displayMessage('GET of \''+name+'\' design failed for type \''+type+'\' with message: \''+error.message+'\'');
            })

to

            .catch(error => {
                displayMessage(method+' of \''+name+'\' design failed for type \''+type+'\' with message: \''+error.message+'\'');
            })

**Comment by 1fifoto** [comment]
Secondary problem with FileImport does not show the filename instead it shows "undefined". Change from

    if (migrated_design.jsontype === "ODOP") {
      dispatch(load(migrated_design));
      dispatch(changeName(filename));
      dispatch(deleteAutoSave());
      logUsage('event', 'FileImport', { event_label: migrated_design.type + ' ' + migrated_design.name });
    } else {
      displayMessage('Invalid JSON type, function ignored');
    }

to 

    if (migrated_design.jsontype === "ODOP") {
      dispatch(load(migrated_design));
      dispatch(changeName(filename));
      dispatch(deleteAutoSave());
      logUsage('event', 'FileImport', { event_label: migrated_design.type + ' ' + filename });
    } else {
      displayMessage('Invalid JSON type, function ignored');
    }

**Comment by 1fifoto** [comment]
Merged into 441, closing
