### ISSUE TITLE
Problems with numeric input to independent variable

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#919]
There seems to be a problem entering the sequence:  . 0 {any digit} to replace the current value of an independent variable.  The pop-up text: "Please enter a valid value.  The two nearest values are _ and _" seems inappropriate.

Steps to reproduce problem: 
1. Launch OODP app.  Observe that it defaults to Compression Spring.
2. Highlight the current value of OD_Free with intent to change its value to ".09"
3. Enter decimal point.  Observe expected result (Red, "Please enter a number.")
4. Enter "0".  Observe that decimal point disappears, 
prompt "Please enter a valid value.  The two nearest values are _ and _" appears
This is the first part of the problem.
5. Enter "9".  Observe that the zero disappears.
This is the second part of the problem

**Comment by 1fifoto** [comment]
Very good catch, fixed.

**Comment by 1fifoto** [comment]
Merged into master, closing.

**Comment by grumpyinca** [comment]
See #932 for the solution to #4 above.
