### ISSUE TITLE
Improve Performance of our use of Redux Tool Kit (RTK)

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#921]
Possibly replace/regress Redux Tool Kit (RDK) to use original Redux.

**Comment by 1fifoto** [comment]
Taken from Issue 441

> medium priority
> 
> Performance concerns: compression spring demo10 is my recommendation for a test case to reproduce the performance problem.
> 
> From June 23 3:30pm PST Slack entry:
> Performance testing:
> A quick review of demo sessions discovered that in compression spring demo10, the transition from page 09 to page 10 of 15 contains a search that runs for 70 iterations.
> I set up my two VMs side-by-side. The left side was the branch 441 development environment (v5.0dev). The right side was the master branch development environment (v4.6dev).
> I used the stopwatch app of my smartphone to do the timing.
> The average page 9 to 10 transition time for branch 441 was roughly 21 seconds. The average page 9 to 10 transition time for the master branch was roughly 1.5 seconds.
> If you want to run this test many times and eliminate having to hit "Next" a bunch of times, it would be pretty easy to create a stripped-down version of the demo10 script.
> Just a side observation ... many operations (demo page transitions) in branch 441 are perceptibly slower than their equivalents in the master branch. So, my guess is that the root performance issue is pretty low-level and impacts a lot more than just Search. Using a Search that requires a large number of iterations makes for a good test case because it makes the differences easy to see. Also, Search is so fundamental to the app, it provides confidence that we are not wasting time on some rare corner case.
> Let me know if you think that I can do more along these lines.

**Comment by 1fifoto** [comment]
See #622 & #675 for potential performance improvements separate from RTK issues.

**Comment by 1fifoto** [comment]
See and read the following:

* [https://github.com/reduxjs/redux-toolkit/issues/2405](Reducers without immer)
* [https://immerjs.github.io/immer/freezing/](Immer Auto freezing)
* [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze](Javascript Object.freeze())
* [https://github.com/reduxjs/redux-toolkit/issues/242](RFC: Make immer optional for createReducer)
* [https://github.com/reduxjs/redux-toolkit/issues/183](Consider adding an option to remove immer)

**Comment by grumpyinca** [comment]
Testing results on Branch 921 -createstore 
Oct 13, 2024

1 - Account SignIn produces a message in the browser console:  "`No routes matched location "/undefined"` "
This message does not seem to have a negative effect on operation while signed in.

2 - Fixing all independent variables and then invoking Search or Seek does not produce a red warning message pop-up with text similar to "`Search cannot continue because there are no free independent variables. Help button provides more information.`".  Basically, from the user's point of view, nothing happens.

**Comment by 1fifoto** [comment]
Status: 

* Number 1 above is deep inside of routing and is probably related to how we use Okta.
* Fixed 2 above. 
* Spinner is still not working in 3 above. 
* Mike working on 4 above.

**Comment by 1fifoto** [comment]
Merged into master, closing
