### ISSUE TITLE
Transient error message in command window after "npm start"

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#923]
This issue is transcribed from #441 (now closed).

Test result number 22
low priority

June 14. Confirmed July 20, 2024.
Message that briefly appears in development environment client command window when loading following "npm start":

(node:9656) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] Deprecation Warning: 'onAfterSetupMiddleware' option is deprecated. 
Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9656) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. 
Please use the 'setupMiddlewares' option.

**Comment by 1fifoto** [comment]
Please run 'node -v' and tell your node version. For example, my system:

    brianwatt@Bris-M1-MBP odop % node -v
    v20.11.1
    brianwatt@Bris-M1-MBP odop %

**Comment by 1fifoto** [comment]
When you issue 'npm start' change to 'npm start >> error.txt' to capture the console output & attach it here as a comment

**Comment by 1fifoto** [comment]
See: https://github.com/facebook/create-react-app/issues/12035

The above refers to YouTube: https://www.youtube.com/watch?v=ifSTp9WEHpo, and his github repo with the change in it at: https://github.com/DrVipinKumar/ReactAllProjects/blob/main/reactwithspring/public/MiddlewareDeprecationSolution.txt

I have made the change in my node modules and the message is no longer being generated. Now the only problem is this is a modification to node_modules which is lost upon installing our app. As a result why might need a 'patch' facility (see: https://www.npmjs.com/package/patch-package).

**Comment by 1fifoto** [comment]
Fix added to branch 923. This requires you to delete node_modules and run 'node install' then, which applies the patch to eliminate this error.

**Comment by 1fifoto** [comment]
Merged into master, closing
