### ISSUE TITLE
Option to not terminate Execute macro on File : Open

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#934]
### Overview
One of the many changes included in branch #441 was the introduction of a behavior that terminates execution of an Execute macro on **File : Open** or **File: Import**.  Subsequent testing has shown that the **_guidedDesign_** tutorial session advises the user to save a candidate design and then later re-open it.  So, changes that impact the new introduced-in-branch-441 code, the **_guidedDesign_** content, or likely both, are necessary.  

### Implementation possibilities
 - Initial discussion brought up the possibility of a **File : Preferences ...** value, perhaps named something like "**_StopExecuteMacro_**", that could be controlled by the coding of the Execute macro to alter the stop on **File : Open** and **File : Import** behavior.  The default behavior should be to stop execution of the macro (the safer, more conservative approach).  The macro itself could over-ride this default behavior to not stop execution for specific cases.  A concern that the **File : Preferences ...** change would become the one item that incurs the overhead of a migrate for the v5.0 release was mentioned. 

 - Later discussion touched on a slightly different implementation possibility, specifically, a new state variable for the Execute panel slice that is a flag indicating stop on **File : Open** or not.  The Execute macro could then set or look at this flag.  Perhaps this alternative would not require the migration procedure.

**Comment by 1fifoto** [comment]
Merged into master, closing
