### ISSUE TITLE
Implement "shadow" model to improve performance

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#938]
### Overview 
Many discussions of how to improve performance, mostly the time required to execute a Search and mostly after implementation of branch #441, have introduced the term "shadow" model.  In summary, this is an approach to disconnect React and its display updates from the heavy computation of Search (and therefore, Seek & Trade).  More detail and prototype shadow model code are available in issue & branch #745. 

As currently visualized, changes to implement the shadow model should not require associated changes to the user interface.

It is possible that implementation of #921 will be sufficiently successful to decrease the priority of further performance improvements.  In that case, this issue may be pushed into a future milestone.

### See also:
 - #717 
 - #622

**Comment by 1fifoto** [comment]
This was added to #921 (branch 921-createStore) at the end of the commits as were were testing performance. Merged into master, closing
