### ISSUE TITLE
Problems with design type switch

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#947]
The current development code (v5.1dev, branch 921 -createStore, soon to be merged to master) gets a traceback:
```
ERROR
Cannot find module './Spring/Extension/demo10.js'
    at webpackContextResolve (http://localhost:3000/static/js/bundle.js:265415:11) 
```

after running an execute script (compression spring demo10 in this case) and then switching to a different design type.  Only compression springs have a demo10 execute script.

The traceback does not occur if the two design types share an execute file of the same name.

**Comment by 1fifoto** [comment]
This was accidentally done in #921-createStore branch. Merged into master, closing
