### ISSUE TITLE
Calc View field width concerns

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#953]
The image embedded below is a full-screen screen capture of v5.1rc1 Calculator View from an MS Surface Pro 9 while held in portrait mode.  The screen is relatively high resolution (2880x1920).  There is no shortage of available pixels.  Rather, I suspect that the problem is one of aspect ratio.

Comparing this screen capture to the equivalent display of v4.5.1 bring up a field width concern in four (circled in red) places.  

Is it possible to make improvements here ? 

![CalcViewFieldWidthConcerns](https://github.com/user-attachments/assets/dd7e711b-d731-4ede-8817-ea59a5fbd7a5)

**Comment by 1fifoto** [comment]
Merged into master, closing.

**Comment by grumpyinca** [comment]
Equivalent screen capture after format changes.

![AfterFormatChanges](https://github.com/user-attachments/assets/ac9d0278-64a2-453d-b1e8-a6edc01ae226)
