### ISSUE TITLE
Modify lifetarget.json of extension & torsion

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#959]
Today's conversation about the material properties file produced the suggestion that simply truncating the lifetarget.json file for extension and torsion springs could make shot peened options invisible (not selectable) to the user.  

Extension and torsion springs are not commonly shot peened.  Thus, removing the shot peened options is not a significant loss of capability, does simplify things for the user and also avoids questionable values.

**Comment by grumpyinca** [comment]
Is migrate necessary?  What happens to the Life_Category field if no migrate ?

**Comment by 1fifoto** [comment]
Merged into master, closing
