### ISSUE TITLE
Action:Trade disabled after using non-default stepsize

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#965]
While it takes a lot of input, it is possible to achieve a situation where the Action:Trade menu is disabled, even for a design that is NOT FEASIBLE.  Once achieved, this situation will persist until the next reload of the app.

I believe that this is a bug created by the recent repairs to the Trade default stepsize code.

### Steps to recreate the problem:
1. Reload the App
2. Help / Tutorial / Tutor8 / Execute 
3. Next until at page 5
4. (follow tutorial instructions) Action:Trade / Arbitrary / 0, 1, 0 0 / Continue
5. Override default exploration stepsize to 30 / Continue
6. Resize
7. Override default exploration stepsize to 15 / Continue
8. Accept / Repeat 
9.  Arbitrary / 0, 1, 0 0 / Continue 
10.  Override default exploration stepsize to 1 / Continue
11. Accept
12. Close
13. Help / Tutorial / Tutor8 / Execute 
14. Next until at page 5
15. Observe that Action:Trade is disabled.  **_<--- This is the bug_**

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by 1fifoto** [comment]
Note: Add more use of useSelector to access the model and get control whenever part of the model changes. We tried to do this, but it failed miserably. So we backed-off to only useSelector on objective_value and objmin.
