### ISSUE TITLE
Create "Prompt For Design Type" React Component

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#98]
There may be multiple scenarios where it is necessary to allow the user to enter a design type (PCyl, Solid, spring, etc.).

In the current opening dialog (PromptForDesign.js), if the database is not available and if the user is to proceed in "demo mode", it will be necessary to proceed with initialState … but for which problem ?

In a multi-user future, it may be necessary to have the user specify what type of problem that they want to work on.  This is particularly true of a newly created user.

**Comment by 1fifoto** [comment]
Needed once we have more than one design type, so when Solids is added.

**Comment by 1fifoto** [comment]
Already done in release 1.0, closing
